"""GENERATED by scripts/upgrade_flagship_labs.py — do not edit by hand.

Real-simulation presets for flagship academy labs. Each preset breaks a genuine
OS state (failed service, missing user, closed firewall port, stopped compose
stack). Validation reads that real state back via the scenario's check.sh, so a
fresh lab is fail-closed until the genuine fix is applied. The matching fix is
performed by scripts/e2e_simulation_fix.py using the *_FIX maps exported here.
"""
from __future__ import annotations

from .rhel_os import SimService


def _break_service(state, unit: str, desc: str) -> None:
    state.services[unit] = SimService(
        unit, active="failed", enabled="enabled", description=desc,
        loaded="loaded", sub_state="failed", unit_file=f"[Unit]\nDescription={desc}\n",
    )


def _preset_users(state) -> None:
    # The dedicated service account must be created by the learner.
    state.users.pop("appuser", None)
    state.sync_passwd_files()


def _preset_systemd(state) -> None:
    _break_service(state, "nginx", "The nginx HTTP and reverse proxy server")


def _preset_chrony(state) -> None:
    _break_service(state, "chronyd", "NTP client/server (chrony)")


def _preset_syslog(state) -> None:
    _break_service(state, "rsyslog", "System Logging Service")


def _preset_crond(state) -> None:
    _break_service(state, "crond", "Command Scheduler (cron)")


def _preset_ansible(state) -> None:
    # No OS-level break: the managed hosts are unreachable until the learner
    # distributes SSH keys (engine._ssh_key_fixed stays False at boot). Nothing
    # to set on the state itself.
    return None


def _close_http(state) -> None:
    fw = state.firewall
    for scope in (fw.runtime, fw.permanent):
        zone = scope.get(fw.default_zone)
        if not zone:
            continue
        zone["services"] = [s for s in zone.get("services", []) if s != "http"]
        zone["ports"] = [p for p in zone.get("ports", []) if p != "80/tcp"]


def _preset_firewall(state) -> None:
    _close_http(state)


def _preset_docker_compose(state) -> None:
    # Daemon is up; the compose stack is simply not running yet.
    if "docker" not in state.services:
        state.services["docker"] = SimService(
            "docker", active="active", enabled="enabled",
            description="Docker Application Container Engine",
            loaded="loaded", sub_state="running",
        )


_BUILDERS = {
    "users": _preset_users,
    "systemd": _preset_systemd,
    "syslog": _preset_syslog,
    "crond": _preset_crond,
    "chrony": _preset_chrony,
    "firewall": _preset_firewall,
    "docker-compose": _preset_docker_compose,
    "ansible": _preset_ansible,
}


# slug -> preset kind (generated)
FLAGSHIP_SLUG_KIND = {
    'academy-ansible-001-learn-inventory': 'ansible',
    'academy-ansible-002-build-playbooks': 'ansible',
    'academy-ansible-011-learn-inventory-2': 'ansible',
    'academy-ansible-012-build-playbooks-2': 'ansible',
    'academy-ansible-021-learn-inventory-3': 'ansible',
    'academy-ansible-022-build-playbooks-3': 'ansible',
    'academy-ansible-031-learn-inventory-4': 'ansible',
    'academy-ansible-032-build-playbooks-4': 'ansible',
    'academy-ansible-041-learn-inventory-5': 'ansible',
    'academy-ansible-042-build-playbooks-5': 'ansible',
    'academy-ansible-051-learn-inventory-6': 'ansible',
    'academy-ansible-052-build-playbooks-6': 'ansible',
    'academy-ansible-061-learn-inventory-7': 'ansible',
    'academy-ansible-062-build-playbooks-7': 'ansible',
    'academy-ansible-071-learn-inventory-8': 'ansible',
    'academy-ansible-072-build-playbooks-8': 'ansible',
    'academy-ansible-081-learn-inventory-9': 'ansible',
    'academy-ansible-082-build-playbooks-9': 'ansible',
    'academy-ansible-091-learn-inventory-10': 'ansible',
    'academy-ansible-092-build-playbooks-10': 'ansible',
    'academy-docker-003-operate-compose': 'docker-compose',
    'academy-docker-013-operate-compose-2': 'docker-compose',
    'academy-docker-023-operate-compose-3': 'docker-compose',
    'academy-docker-033-operate-compose-4': 'docker-compose',
    'academy-docker-043-operate-compose-5': 'docker-compose',
    'academy-docker-053-operate-compose-6': 'docker-compose',
    'academy-docker-063-operate-compose-7': 'docker-compose',
    'academy-docker-073-operate-compose-8': 'docker-compose',
    'academy-docker-083-operate-compose-9': 'docker-compose',
    'academy-docker-093-operate-compose-10': 'docker-compose',
    'academy-linux-001-learn-users-groups': 'users',
    'academy-linux-003-operate-systemd-services': 'systemd',
    'academy-linux-004-troubleshoot-journald-logs': 'syslog',
    'academy-linux-006-security-networking-firewalld': 'firewall',
    'academy-linux-008-observability-cron-timers': 'crond',
    'academy-linux-011-learn-users-groups-2': 'users',
    'academy-linux-013-operate-systemd-services-2': 'systemd',
    'academy-linux-014-troubleshoot-journald-logs-2': 'syslog',
    'academy-linux-016-security-networking-firewalld-2': 'firewall',
    'academy-linux-018-observability-cron-timers-2': 'crond',
    'academy-linux-021-learn-users-groups-3': 'users',
    'academy-linux-023-operate-systemd-services-3': 'systemd',
    'academy-linux-024-troubleshoot-journald-logs-3': 'syslog',
    'academy-linux-026-security-networking-firewalld-3': 'firewall',
    'academy-linux-028-observability-cron-timers-3': 'crond',
    'academy-linux-031-learn-users-groups-4': 'users',
    'academy-linux-033-operate-systemd-services-4': 'systemd',
    'academy-linux-034-troubleshoot-journald-logs-4': 'syslog',
    'academy-linux-036-security-networking-firewalld-4': 'firewall',
    'academy-linux-038-observability-cron-timers-4': 'crond',
    'academy-rhel-linux-003-operate-firewalld': 'firewall',
    'academy-rhel-linux-009-backup-chrony': 'chrony',
    'academy-rhel-linux-013-operate-firewalld-2': 'firewall',
    'academy-rhel-linux-019-backup-chrony-2': 'chrony',
    'academy-rhel-linux-023-operate-firewalld-3': 'firewall',
    'academy-rhel-linux-029-backup-chrony-3': 'chrony',
    'academy-rhel-linux-033-operate-firewalld-4': 'firewall',
    'academy-rhel-linux-039-backup-chrony-4': 'chrony',
    'academy-rhel-linux-043-operate-firewalld-5': 'firewall',
    'academy-rhel-linux-049-backup-chrony-5': 'chrony',
    'academy-rhel-linux-053-operate-firewalld-6': 'firewall',
    'academy-rhel-linux-059-backup-chrony-6': 'chrony',
    'academy-rhel-linux-063-operate-firewalld-7': 'firewall',
    'academy-rhel-linux-069-backup-chrony-7': 'chrony',
    'academy-rhel-linux-073-operate-firewalld-8': 'firewall',
    'academy-rhel-linux-079-backup-chrony-8': 'chrony',
    'academy-rhel-linux-083-operate-firewalld-9': 'firewall',
    'academy-rhel-linux-089-backup-chrony-9': 'chrony',
    'academy-rhel-linux-093-operate-firewalld-10': 'firewall',
    'academy-rhel-linux-099-backup-chrony-10': 'chrony',
}

FLAGSHIP_PRESETS = {
    slug: (lambda state, _k=kind: _BUILDERS[_k](state))
    for slug, kind in FLAGSHIP_SLUG_KIND.items()
}

# Maps consumed by scripts/e2e_simulation_fix.py to apply the genuine fix.
_SERVICE_UNIT = {
    "systemd": "nginx",
    "chrony": "chronyd",
    "syslog": "rsyslog",
    "crond": "crond",
}
FLAGSHIP_SERVICE_FIX = {
    slug: _SERVICE_UNIT[kind]
    for slug, kind in FLAGSHIP_SLUG_KIND.items()
    if kind in _SERVICE_UNIT
}
FLAGSHIP_USER_FIX = {
    slug: "appuser" for slug, kind in FLAGSHIP_SLUG_KIND.items() if kind == "users"
}
FLAGSHIP_FIREWALL_SLUGS = {
    slug for slug, kind in FLAGSHIP_SLUG_KIND.items() if kind == "firewall"
}
FLAGSHIP_DOCKER_SLUGS = {
    slug for slug, kind in FLAGSHIP_SLUG_KIND.items() if kind == "docker-compose"
}
FLAGSHIP_ANSIBLE_SLUGS = {
    slug for slug, kind in FLAGSHIP_SLUG_KIND.items() if kind == "ansible"
}
FLAGSHIP_SLUGS = set(FLAGSHIP_SLUG_KIND)

