"""GENERATED by scripts/gen_monitoring_scenarios.py — do not edit by hand.

Grafana + Prometheus simulation presets. Each writes the scenario's config file
in a BROKEN state (no FIXED-OK marker). The e2e fix (scripts/e2e_simulation_fix.py
_RS_MARKER_FIX) rewrites it WITH the FIXED-OK sentinel, and validation.py's
generic `grep -q FIXED-OK <file>` branch reads the real file content — so every
scenario is fail-closed (Check Solution cannot auto-pass before the fix).
"""
from __future__ import annotations

import os


def _mon_marker(state, path: str, slug: str) -> None:
    """Write a monitoring config file in a broken state (no FIXED-OK)."""
    d = os.path.dirname(path)
    if d:
        state._mkdir(d)
    # NOTE: the broken placeholder must NOT contain the success marker, or the
    # `grep -q FIXED-OK` check would pass before the fix (fail-OPEN). Keep this
    # text marker-free.
    state._write_file(
        path,
        f"# broken configuration for {slug}\n"
        "# the monitoring stack is misconfigured here\n"
        "# apply the documented remediation, then re-run Check Solution\n",
    )


def _preset_mon_grafana_datasource_misconfigured_no_data(state):
    _mon_marker(state, '/etc/grafana/provisioning/datasources/prometheus.yaml', 'grafana-datasource-misconfigured-no-data')

def _preset_mon_grafana_datasource_wrong_auth(state):
    _mon_marker(state, '/etc/grafana/provisioning/datasources/prometheus.yaml', 'grafana-datasource-wrong-auth')

def _preset_mon_grafana_datasource_tls_skip_verify(state):
    _mon_marker(state, '/etc/grafana/provisioning/datasources/prometheus.yaml', 'grafana-datasource-tls-skip-verify')

def _preset_mon_grafana_datasource_default_missing(state):
    _mon_marker(state, '/etc/grafana/provisioning/datasources/prometheus.yaml', 'grafana-datasource-default-missing')

def _preset_mon_grafana_datasource_duplicate_uid(state):
    _mon_marker(state, '/etc/grafana/provisioning/datasources/prometheus.yaml', 'grafana-datasource-duplicate-uid')

def _preset_mon_grafana_loki_datasource_down(state):
    _mon_marker(state, '/etc/grafana/provisioning/datasources/loki.yaml', 'grafana-loki-datasource-down')

def _preset_mon_grafana_datasource_scrape_interval_mismatch(state):
    _mon_marker(state, '/etc/grafana/provisioning/datasources/prometheus.yaml', 'grafana-datasource-scrape-interval-mismatch')

def _preset_mon_grafana_panel_wrong_promql(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-panel-wrong-promql')

def _preset_mon_grafana_panel_wrong_unit(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-panel-wrong-unit')

def _preset_mon_grafana_panel_no_data_state(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-panel-no-data-state')

def _preset_mon_grafana_panel_legend_broken(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-panel-legend-broken')

def _preset_mon_grafana_panel_threshold_wrong(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/api-slo.json', 'grafana-panel-threshold-wrong')

def _preset_mon_grafana_panel_time_range_override(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/api-slo.json', 'grafana-panel-time-range-override')

def _preset_mon_grafana_panel_transform_broken(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/api-slo.json', 'grafana-panel-transform-broken')

def _preset_mon_grafana_panel_stat_reducer_wrong(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-panel-stat-reducer-wrong')

def _preset_mon_grafana_dashboard_json_invalid(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-dashboard-json-invalid')

def _preset_mon_grafana_dashboard_uid_collision(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/dashboards.yaml', 'grafana-dashboard-uid-collision')

def _preset_mon_grafana_dashboard_folder_missing(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/dashboards.yaml', 'grafana-dashboard-folder-missing')

def _preset_mon_grafana_dashboard_version_drift(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/dashboards.yaml', 'grafana-dashboard-version-drift')

def _preset_mon_grafana_variable_query_wrong(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-variable-query-wrong')

def _preset_mon_grafana_variable_regex_filter(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-variable-regex-filter')

def _preset_mon_grafana_variable_chained_broken(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-variable-chained-broken')

def _preset_mon_grafana_variable_multi_value_quote(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/api-slo.json', 'grafana-variable-multi-value-quote')

def _preset_mon_grafana_variable_all_value_wrong(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/api-slo.json', 'grafana-variable-all-value-wrong')

def _preset_mon_grafana_alert_rule_no_datasource(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/rules.yaml', 'grafana-alert-rule-no-datasource')

def _preset_mon_grafana_alert_rule_for_too_short(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/rules.yaml', 'grafana-alert-rule-for-too-short')

def _preset_mon_grafana_alert_rule_for_too_long(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/rules.yaml', 'grafana-alert-rule-for-too-long')

def _preset_mon_grafana_alert_no_data_state_wrong(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/rules.yaml', 'grafana-alert-no-data-state-wrong')

def _preset_mon_grafana_alert_condition_wrong_threshold(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/rules.yaml', 'grafana-alert-condition-wrong-threshold')

def _preset_mon_grafana_alert_eval_interval_wrong(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/rules.yaml', 'grafana-alert-eval-interval-wrong')

def _preset_mon_grafana_contact_point_missing(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/contactpoints.yaml', 'grafana-contact-point-missing')

def _preset_mon_grafana_contact_point_wrong_webhook(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/contactpoints.yaml', 'grafana-contact-point-wrong-webhook')

def _preset_mon_grafana_contact_point_pagerduty_key(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/contactpoints.yaml', 'grafana-contact-point-pagerduty-key')

def _preset_mon_grafana_contact_point_email_smtp(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/contactpoints.yaml', 'grafana-contact-point-email-smtp')

def _preset_mon_grafana_notification_policy_misrouted(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/policies.yaml', 'grafana-notification-policy-misrouted')

def _preset_mon_grafana_notification_policy_group_by(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/policies.yaml', 'grafana-notification-policy-group-by')

def _preset_mon_grafana_notification_mute_timing(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/policies.yaml', 'grafana-notification-mute-timing')

def _preset_mon_grafana_notification_repeat_interval(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/policies.yaml', 'grafana-notification-repeat-interval')

def _preset_mon_grafana_org_default_role_wrong(state):
    _mon_marker(state, '/etc/grafana/grafana.ini', 'grafana-org-default-role-wrong')

def _preset_mon_grafana_anonymous_access_enabled(state):
    _mon_marker(state, '/etc/grafana/grafana.ini', 'grafana-anonymous-access-enabled')

def _preset_mon_grafana_smtp_not_configured(state):
    _mon_marker(state, '/etc/grafana/grafana.ini', 'grafana-smtp-not-configured')

def _preset_mon_grafana_root_url_wrong(state):
    _mon_marker(state, '/etc/grafana/grafana.ini', 'grafana-root-url-wrong')

def _preset_mon_grafana_database_sqlite_locked(state):
    _mon_marker(state, '/etc/grafana/grafana.ini', 'grafana-database-sqlite-locked')

def _preset_mon_grafana_provisioning_path_wrong(state):
    _mon_marker(state, '/etc/grafana/grafana.ini', 'grafana-provisioning-path-wrong')

def _preset_mon_grafana_plugin_unsigned_blocked(state):
    _mon_marker(state, '/etc/grafana/grafana.ini', 'grafana-plugin-unsigned-blocked')

def _preset_mon_grafana_oauth_redirect_mismatch(state):
    _mon_marker(state, '/etc/grafana/grafana.ini', 'grafana-oauth-redirect-mismatch')

def _preset_mon_grafana_dashboard_query_rate_no_range(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/api-slo.json', 'grafana-dashboard-query-rate-no-range')

def _preset_mon_grafana_panel_instant_vs_range(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/api-slo.json', 'grafana-panel-instant-vs-range')

def _preset_mon_grafana_alert_label_missing_severity(state):
    _mon_marker(state, '/etc/grafana/provisioning/alerting/rules.yaml', 'grafana-alert-label-missing-severity')

def _preset_mon_grafana_dashboard_datasource_hardcoded(state):
    _mon_marker(state, '/etc/grafana/provisioning/dashboards/node-overview.json', 'grafana-dashboard-datasource-hardcoded')

def _preset_mon_prometheus_target_down_scrape_refused(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-target-down-scrape-refused')

def _preset_mon_prometheus_scrape_config_wrong_port(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-scrape-config-wrong-port')

def _preset_mon_prometheus_scrape_interval_too_high(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-scrape-interval-too-high')

def _preset_mon_prometheus_scrape_timeout_exceeds_interval(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-scrape-timeout-exceeds-interval')

def _preset_mon_prometheus_metrics_path_wrong(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-metrics-path-wrong')

def _preset_mon_prometheus_scheme_https_no_tls(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-scheme-https-no-tls')

def _preset_mon_prometheus_relabel_drops_everything(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-relabel-drops-everything')

def _preset_mon_prometheus_metric_relabel_drops_metric(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-metric-relabel-drops-metric')

def _preset_mon_prometheus_honor_labels_collision(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-honor-labels-collision')

def _preset_mon_prometheus_sd_file_missing(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-sd-file-missing')

def _preset_mon_prometheus_static_config_no_targets(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-static-config-no-targets')

def _preset_mon_prometheus_external_labels_missing(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-external-labels-missing')

def _preset_mon_prometheus_node_exporter_down(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-node-exporter-down')

def _preset_mon_prometheus_blackbox_probe_failing(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-blackbox-probe-failing')

def _preset_mon_prometheus_blackbox_module_wrong(state):
    _mon_marker(state, '/etc/prometheus/blackbox.yml', 'prometheus-blackbox-module-wrong')

def _preset_mon_prometheus_blackbox_tls_expiry(state):
    _mon_marker(state, '/etc/prometheus/blackbox.yml', 'prometheus-blackbox-tls-expiry')

def _preset_mon_prometheus_recording_rule_parse_error(state):
    _mon_marker(state, '/etc/prometheus/rules/recording.yml', 'prometheus-recording-rule-parse-error')

def _preset_mon_prometheus_recording_rule_name_invalid(state):
    _mon_marker(state, '/etc/prometheus/rules/recording.yml', 'prometheus-recording-rule-name-invalid')

def _preset_mon_prometheus_recording_rule_interval(state):
    _mon_marker(state, '/etc/prometheus/rules/recording.yml', 'prometheus-recording-rule-interval')

def _preset_mon_prometheus_alerting_rule_syntax(state):
    _mon_marker(state, '/etc/prometheus/rules/alerts.yml', 'prometheus-alerting-rule-syntax')

def _preset_mon_prometheus_alert_for_flapping(state):
    _mon_marker(state, '/etc/prometheus/rules/alerts.yml', 'prometheus-alert-for-flapping')

def _preset_mon_prometheus_alert_expr_always_true(state):
    _mon_marker(state, '/etc/prometheus/rules/alerts.yml', 'prometheus-alert-expr-always-true')

def _preset_mon_prometheus_alert_missing_labels(state):
    _mon_marker(state, '/etc/prometheus/rules/alerts.yml', 'prometheus-alert-missing-labels')

def _preset_mon_prometheus_alert_annotation_template(state):
    _mon_marker(state, '/etc/prometheus/rules/alerts.yml', 'prometheus-alert-annotation-template')

def _preset_mon_prometheus_alertmanager_url_wrong(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-alertmanager-url-wrong')

def _preset_mon_prometheus_alertmanager_route_misrouted(state):
    _mon_marker(state, '/etc/prometheus/alertmanager.yml', 'prometheus-alertmanager-route-misrouted')

def _preset_mon_prometheus_alertmanager_receiver_missing(state):
    _mon_marker(state, '/etc/prometheus/alertmanager.yml', 'prometheus-alertmanager-receiver-missing')

def _preset_mon_prometheus_alertmanager_group_wait(state):
    _mon_marker(state, '/etc/prometheus/alertmanager.yml', 'prometheus-alertmanager-group-wait')

def _preset_mon_prometheus_alertmanager_inhibit_wrong(state):
    _mon_marker(state, '/etc/prometheus/alertmanager.yml', 'prometheus-alertmanager-inhibit-wrong')

def _preset_mon_prometheus_alertmanager_silence_stuck(state):
    _mon_marker(state, '/etc/prometheus/alertmanager.yml', 'prometheus-alertmanager-silence-stuck')

def _preset_mon_prometheus_alertmanager_repeat_interval(state):
    _mon_marker(state, '/etc/prometheus/alertmanager.yml', 'prometheus-alertmanager-repeat-interval')

def _preset_mon_prometheus_remote_write_unreachable(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-remote-write-unreachable')

def _preset_mon_prometheus_remote_write_auth(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-remote-write-auth')

def _preset_mon_prometheus_remote_write_queue_full(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-remote-write-queue-full')

def _preset_mon_prometheus_remote_read_wrong(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-remote-read-wrong')

def _preset_mon_prometheus_federation_match_empty(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-federation-match-empty')

def _preset_mon_prometheus_federation_honor_labels(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-federation-honor-labels')

def _preset_mon_prometheus_high_cardinality_label(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-high-cardinality-label')

def _preset_mon_prometheus_cardinality_bomb_histogram(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-cardinality-bomb-histogram')

def _preset_mon_prometheus_tsdb_retention_too_low(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-tsdb-retention-too-low')

def _preset_mon_prometheus_tsdb_retention_disk_full(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-tsdb-retention-disk-full')

def _preset_mon_prometheus_evaluation_interval_mismatch(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-evaluation-interval-mismatch')

def _preset_mon_prometheus_no_data_stale_marker(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-no-data-stale-marker')

def _preset_mon_prometheus_query_rate_counter_reset(state):
    _mon_marker(state, '/etc/prometheus/rules/recording.yml', 'prometheus-query-rate-counter-reset')

def _preset_mon_prometheus_query_by_without_le(state):
    _mon_marker(state, '/etc/prometheus/rules/recording.yml', 'prometheus-query-by-without-le')

def _preset_mon_prometheus_scrape_limit_exceeded(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-scrape-limit-exceeded')

def _preset_mon_prometheus_label_limit_exceeded(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-label-limit-exceeded')

def _preset_mon_prometheus_basic_auth_wrong(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-basic-auth-wrong')

def _preset_mon_prometheus_pushgateway_stale(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-pushgateway-stale')

def _preset_mon_prometheus_service_discovery_relabel_instance(state):
    _mon_marker(state, '/etc/prometheus/prometheus.yml', 'prometheus-service-discovery-relabel-instance')

MONITORING_PRESETS = {
    'grafana-datasource-misconfigured-no-data': _preset_mon_grafana_datasource_misconfigured_no_data,
    'grafana-datasource-wrong-auth': _preset_mon_grafana_datasource_wrong_auth,
    'grafana-datasource-tls-skip-verify': _preset_mon_grafana_datasource_tls_skip_verify,
    'grafana-datasource-default-missing': _preset_mon_grafana_datasource_default_missing,
    'grafana-datasource-duplicate-uid': _preset_mon_grafana_datasource_duplicate_uid,
    'grafana-loki-datasource-down': _preset_mon_grafana_loki_datasource_down,
    'grafana-datasource-scrape-interval-mismatch': _preset_mon_grafana_datasource_scrape_interval_mismatch,
    'grafana-panel-wrong-promql': _preset_mon_grafana_panel_wrong_promql,
    'grafana-panel-wrong-unit': _preset_mon_grafana_panel_wrong_unit,
    'grafana-panel-no-data-state': _preset_mon_grafana_panel_no_data_state,
    'grafana-panel-legend-broken': _preset_mon_grafana_panel_legend_broken,
    'grafana-panel-threshold-wrong': _preset_mon_grafana_panel_threshold_wrong,
    'grafana-panel-time-range-override': _preset_mon_grafana_panel_time_range_override,
    'grafana-panel-transform-broken': _preset_mon_grafana_panel_transform_broken,
    'grafana-panel-stat-reducer-wrong': _preset_mon_grafana_panel_stat_reducer_wrong,
    'grafana-dashboard-json-invalid': _preset_mon_grafana_dashboard_json_invalid,
    'grafana-dashboard-uid-collision': _preset_mon_grafana_dashboard_uid_collision,
    'grafana-dashboard-folder-missing': _preset_mon_grafana_dashboard_folder_missing,
    'grafana-dashboard-version-drift': _preset_mon_grafana_dashboard_version_drift,
    'grafana-variable-query-wrong': _preset_mon_grafana_variable_query_wrong,
    'grafana-variable-regex-filter': _preset_mon_grafana_variable_regex_filter,
    'grafana-variable-chained-broken': _preset_mon_grafana_variable_chained_broken,
    'grafana-variable-multi-value-quote': _preset_mon_grafana_variable_multi_value_quote,
    'grafana-variable-all-value-wrong': _preset_mon_grafana_variable_all_value_wrong,
    'grafana-alert-rule-no-datasource': _preset_mon_grafana_alert_rule_no_datasource,
    'grafana-alert-rule-for-too-short': _preset_mon_grafana_alert_rule_for_too_short,
    'grafana-alert-rule-for-too-long': _preset_mon_grafana_alert_rule_for_too_long,
    'grafana-alert-no-data-state-wrong': _preset_mon_grafana_alert_no_data_state_wrong,
    'grafana-alert-condition-wrong-threshold': _preset_mon_grafana_alert_condition_wrong_threshold,
    'grafana-alert-eval-interval-wrong': _preset_mon_grafana_alert_eval_interval_wrong,
    'grafana-contact-point-missing': _preset_mon_grafana_contact_point_missing,
    'grafana-contact-point-wrong-webhook': _preset_mon_grafana_contact_point_wrong_webhook,
    'grafana-contact-point-pagerduty-key': _preset_mon_grafana_contact_point_pagerduty_key,
    'grafana-contact-point-email-smtp': _preset_mon_grafana_contact_point_email_smtp,
    'grafana-notification-policy-misrouted': _preset_mon_grafana_notification_policy_misrouted,
    'grafana-notification-policy-group-by': _preset_mon_grafana_notification_policy_group_by,
    'grafana-notification-mute-timing': _preset_mon_grafana_notification_mute_timing,
    'grafana-notification-repeat-interval': _preset_mon_grafana_notification_repeat_interval,
    'grafana-org-default-role-wrong': _preset_mon_grafana_org_default_role_wrong,
    'grafana-anonymous-access-enabled': _preset_mon_grafana_anonymous_access_enabled,
    'grafana-smtp-not-configured': _preset_mon_grafana_smtp_not_configured,
    'grafana-root-url-wrong': _preset_mon_grafana_root_url_wrong,
    'grafana-database-sqlite-locked': _preset_mon_grafana_database_sqlite_locked,
    'grafana-provisioning-path-wrong': _preset_mon_grafana_provisioning_path_wrong,
    'grafana-plugin-unsigned-blocked': _preset_mon_grafana_plugin_unsigned_blocked,
    'grafana-oauth-redirect-mismatch': _preset_mon_grafana_oauth_redirect_mismatch,
    'grafana-dashboard-query-rate-no-range': _preset_mon_grafana_dashboard_query_rate_no_range,
    'grafana-panel-instant-vs-range': _preset_mon_grafana_panel_instant_vs_range,
    'grafana-alert-label-missing-severity': _preset_mon_grafana_alert_label_missing_severity,
    'grafana-dashboard-datasource-hardcoded': _preset_mon_grafana_dashboard_datasource_hardcoded,
    'prometheus-target-down-scrape-refused': _preset_mon_prometheus_target_down_scrape_refused,
    'prometheus-scrape-config-wrong-port': _preset_mon_prometheus_scrape_config_wrong_port,
    'prometheus-scrape-interval-too-high': _preset_mon_prometheus_scrape_interval_too_high,
    'prometheus-scrape-timeout-exceeds-interval': _preset_mon_prometheus_scrape_timeout_exceeds_interval,
    'prometheus-metrics-path-wrong': _preset_mon_prometheus_metrics_path_wrong,
    'prometheus-scheme-https-no-tls': _preset_mon_prometheus_scheme_https_no_tls,
    'prometheus-relabel-drops-everything': _preset_mon_prometheus_relabel_drops_everything,
    'prometheus-metric-relabel-drops-metric': _preset_mon_prometheus_metric_relabel_drops_metric,
    'prometheus-honor-labels-collision': _preset_mon_prometheus_honor_labels_collision,
    'prometheus-sd-file-missing': _preset_mon_prometheus_sd_file_missing,
    'prometheus-static-config-no-targets': _preset_mon_prometheus_static_config_no_targets,
    'prometheus-external-labels-missing': _preset_mon_prometheus_external_labels_missing,
    'prometheus-node-exporter-down': _preset_mon_prometheus_node_exporter_down,
    'prometheus-blackbox-probe-failing': _preset_mon_prometheus_blackbox_probe_failing,
    'prometheus-blackbox-module-wrong': _preset_mon_prometheus_blackbox_module_wrong,
    'prometheus-blackbox-tls-expiry': _preset_mon_prometheus_blackbox_tls_expiry,
    'prometheus-recording-rule-parse-error': _preset_mon_prometheus_recording_rule_parse_error,
    'prometheus-recording-rule-name-invalid': _preset_mon_prometheus_recording_rule_name_invalid,
    'prometheus-recording-rule-interval': _preset_mon_prometheus_recording_rule_interval,
    'prometheus-alerting-rule-syntax': _preset_mon_prometheus_alerting_rule_syntax,
    'prometheus-alert-for-flapping': _preset_mon_prometheus_alert_for_flapping,
    'prometheus-alert-expr-always-true': _preset_mon_prometheus_alert_expr_always_true,
    'prometheus-alert-missing-labels': _preset_mon_prometheus_alert_missing_labels,
    'prometheus-alert-annotation-template': _preset_mon_prometheus_alert_annotation_template,
    'prometheus-alertmanager-url-wrong': _preset_mon_prometheus_alertmanager_url_wrong,
    'prometheus-alertmanager-route-misrouted': _preset_mon_prometheus_alertmanager_route_misrouted,
    'prometheus-alertmanager-receiver-missing': _preset_mon_prometheus_alertmanager_receiver_missing,
    'prometheus-alertmanager-group-wait': _preset_mon_prometheus_alertmanager_group_wait,
    'prometheus-alertmanager-inhibit-wrong': _preset_mon_prometheus_alertmanager_inhibit_wrong,
    'prometheus-alertmanager-silence-stuck': _preset_mon_prometheus_alertmanager_silence_stuck,
    'prometheus-alertmanager-repeat-interval': _preset_mon_prometheus_alertmanager_repeat_interval,
    'prometheus-remote-write-unreachable': _preset_mon_prometheus_remote_write_unreachable,
    'prometheus-remote-write-auth': _preset_mon_prometheus_remote_write_auth,
    'prometheus-remote-write-queue-full': _preset_mon_prometheus_remote_write_queue_full,
    'prometheus-remote-read-wrong': _preset_mon_prometheus_remote_read_wrong,
    'prometheus-federation-match-empty': _preset_mon_prometheus_federation_match_empty,
    'prometheus-federation-honor-labels': _preset_mon_prometheus_federation_honor_labels,
    'prometheus-high-cardinality-label': _preset_mon_prometheus_high_cardinality_label,
    'prometheus-cardinality-bomb-histogram': _preset_mon_prometheus_cardinality_bomb_histogram,
    'prometheus-tsdb-retention-too-low': _preset_mon_prometheus_tsdb_retention_too_low,
    'prometheus-tsdb-retention-disk-full': _preset_mon_prometheus_tsdb_retention_disk_full,
    'prometheus-evaluation-interval-mismatch': _preset_mon_prometheus_evaluation_interval_mismatch,
    'prometheus-no-data-stale-marker': _preset_mon_prometheus_no_data_stale_marker,
    'prometheus-query-rate-counter-reset': _preset_mon_prometheus_query_rate_counter_reset,
    'prometheus-query-by-without-le': _preset_mon_prometheus_query_by_without_le,
    'prometheus-scrape-limit-exceeded': _preset_mon_prometheus_scrape_limit_exceeded,
    'prometheus-label-limit-exceeded': _preset_mon_prometheus_label_limit_exceeded,
    'prometheus-basic-auth-wrong': _preset_mon_prometheus_basic_auth_wrong,
    'prometheus-pushgateway-stale': _preset_mon_prometheus_pushgateway_stale,
    'prometheus-service-discovery-relabel-instance': _preset_mon_prometheus_service_discovery_relabel_instance,
}
