"""GENERATED by scripts/upgrade_simulation_marker_labs.py — do not edit by hand.

Real-simulation break presets for the generic ``simulation`` technology labs
(formerly graded by the /tmp/scenario-fixed FIXED-OK marker). Each boots a
genuinely failed systemd unit so the lab is fail-closed until the learner
starts the service. Merged into scenario_presets._PRESETS after the academy
presets.
"""
from __future__ import annotations

from .rhel_os import SimService


def _break_service(state, unit: str, desc: str) -> None:
    state.services[unit] = SimService(
        unit, active="failed", enabled="enabled", description=desc,
        loaded="loaded", sub_state="failed",
        unit_file=f"[Unit]\nDescription={desc}\n",
    )


SIMULATION_MARKER_PRESETS = {
    'sim-cron-missed': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'sim-disk-full': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'sim-firewall-block': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'sim-selinux-deny': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'sim-service-failed': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-16': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-17': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-18': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-19': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-20': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-21': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-22': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-23': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-24': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-25': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-26': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-27': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-28': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-29': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-30': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-31': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-32': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-33': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-34': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-35': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-36': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-37': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-38': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-39': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-40': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-41': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-42': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-43': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-44': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-45': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-46': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-47': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-48': lambda state, u='nginx', d='The nginx HTTP and reverse proxy server': _break_service(state, u, d),
    'simulation-lab-49': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
    'simulation-lab-50': lambda state, u='crond', d='Command Scheduler (cron)': _break_service(state, u, d),
}

