"""GENERATED by scripts/upgrade_simulation_marker_labs.py — do not edit by hand.

E2E fix map for the generic ``simulation`` real-state labs (systemctl start).
"""
from __future__ import annotations

SIMULATION_SERVICE_FIX: dict[str, str] = {
    'sim-cron-missed': 'nginx',
    'sim-disk-full': 'crond',
    'sim-firewall-block': 'nginx',
    'sim-selinux-deny': 'crond',
    'sim-service-failed': 'crond',
    'simulation-lab-16': 'crond',
    'simulation-lab-17': 'nginx',
    'simulation-lab-18': 'crond',
    'simulation-lab-19': 'nginx',
    'simulation-lab-20': 'nginx',
    'simulation-lab-21': 'crond',
    'simulation-lab-22': 'nginx',
    'simulation-lab-23': 'crond',
    'simulation-lab-24': 'nginx',
    'simulation-lab-25': 'crond',
    'simulation-lab-26': 'nginx',
    'simulation-lab-27': 'crond',
    'simulation-lab-28': 'nginx',
    'simulation-lab-29': 'crond',
    'simulation-lab-30': 'crond',
    'simulation-lab-31': 'nginx',
    'simulation-lab-32': 'crond',
    'simulation-lab-33': 'nginx',
    'simulation-lab-34': 'crond',
    'simulation-lab-35': 'nginx',
    'simulation-lab-36': 'crond',
    'simulation-lab-37': 'nginx',
    'simulation-lab-38': 'crond',
    'simulation-lab-39': 'nginx',
    'simulation-lab-40': 'nginx',
    'simulation-lab-41': 'crond',
    'simulation-lab-42': 'nginx',
    'simulation-lab-43': 'crond',
    'simulation-lab-44': 'nginx',
    'simulation-lab-45': 'crond',
    'simulation-lab-46': 'nginx',
    'simulation-lab-47': 'crond',
    'simulation-lab-48': 'nginx',
    'simulation-lab-49': 'crond',
    'simulation-lab-50': 'crond',
}

