# Generated by Django 5.2.12 on 2026-03-30 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('changelog', models.TextField(blank=True)),
                ('definition_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='question_bank.scenario')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('scenario', 'version')},
            },
        ),
    ]
