# Generated by Django 5.2.15 on 2026-06-21 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0011_alter_labsession_expires_at'),
        ('question_bank', '0017_scenario_itsm_config_scenario_itsm_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItsmTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, help_text='ServiceNow-style record number, e.g. INC0010023 / RITM0010024', max_length=20, unique=True)),
                ('ticket_type', models.CharField(choices=[('incident', 'Incident'), ('request', 'Service Request'), ('change', 'Change'), ('problem', 'Problem')], default='incident', max_length=20)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('1', '1 - Critical'), ('2', '2 - High'), ('3', '3 - Moderate'), ('4', '4 - Low'), ('5', '5 - Planning')], default='3', max_length=2)),
                ('assignment_group', models.CharField(choices=[('service_desk', 'Service Desk'), ('storage', 'Storage Team'), ('backup', 'Backup Team'), ('network', 'Network Team'), ('app', 'App / Middleware Team'), ('database', 'Database Team'), ('security', 'Security Team')], default='service_desk', help_text='The team / assignment group that owns this ticket.', max_length=30)),
                ('action_kind', models.CharField(blank=True, default='', max_length=40)),
                ('action_params', models.JSONField(blank=True, default=dict)),
                ('action_result', models.JSONField(blank=True, default=dict)),
                ('close_code', models.CharField(blank=True, choices=[('solved_permanently', 'Solved (Permanently)'), ('solved_workaround', 'Solved (Workaround)'), ('solved_remote', 'Solved Remotely'), ('not_solved', 'Not Solved (Not Reproducible)'), ('closed_complete', 'Closed/Complete')], default='', max_length=40)),
                ('close_notes', models.TextField(blank=True, default='')),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Set on a sub-ticket; the parent ticket it was raised from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='itsm.itsmticket')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itsm_tickets', to='question_bank.scenario')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itsm_tickets', to='labs.labsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itsm_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ItsmWorkNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('work_note', 'Work Note'), ('comment', 'Additional Comment'), ('state_change', 'State Change'), ('system', 'System')], default='work_note', max_length=20)),
                ('author', models.CharField(default='System', max_length=120)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='itsm.itsmticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='itsmticket',
            index=models.Index(fields=['user', 'scenario'], name='itsm_user_scenario_idx'),
        ),
        migrations.AddIndex(
            model_name='itsmticket',
            index=models.Index(fields=['parent'], name='itsm_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='itsmticket',
            index=models.Index(fields=['session', 'state'], name='itsm_session_state_idx'),
        ),
        migrations.AddIndex(
            model_name='itsmworknote',
            index=models.Index(fields=['ticket', 'created_at'], name='itsm_note_ticket_idx'),
        ),
    ]
