# Generated by Django 5.2.15 on 2026-06-22 15:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0017_scenario_itsm_config_scenario_itsm_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('exam_duration_minutes', models.PositiveIntegerField(default=180)),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Percent (0-100) required to pass the timed mock exam')),
                ('validity_months', models.PositiveIntegerField(default=36, help_text='Months the issued certificate stays valid')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_tracks', to='question_bank.technology')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CertObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Relative weight used for the overall track/exam score')),
                ('order', models.PositiveIntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='certifications.certificationtrack')),
            ],
            options={
                'ordering': ['track', 'order'],
                'unique_together': {('track', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('passed', 'Passed'), ('failed', 'Failed'), ('expired', 'Expired')], default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0, help_text='Final percent score (0-100)')),
                ('results', models.JSONField(blank=True, default=dict)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='certifications.certificationtrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CertEarnedCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(max_length=120, unique=True)),
                ('holder_name', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField(default=0)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_certificates', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certifications.certificationtrack')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='certifications.examattempt')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('in_exam_pool', models.BooleanField(default=True, help_text='Eligible for the auto-generated timed mock exam')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_scenarios', to='certifications.certobjective')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_scenarios', to='question_bank.scenario')),
            ],
            options={
                'ordering': ['objective', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', 'track', 'status'], name='cert_attempt_user_track_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackscenario',
            unique_together={('objective', 'scenario')},
        ),
    ]
