# Generated by Django 5.2.15 on 2026-06-22 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certearnedcertificate',
            unique_together={('user', 'track')},
        ),
    ]
