# Generated by Django 6.0.6 on 2026-06-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_alter_certearnedcertificate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationtrack',
            name='coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificationtrack',
            name='is_free',
            field=models.BooleanField(default=True, help_text='Available without a paid subscription'),
        ),
        migrations.AddField(
            model_name='certificationtrack',
            name='maintenance_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificationtrack',
            name='maintenance_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificationtrack',
            name='maintenance_scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationtrack',
            name='maintenance_scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationtrack',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text="Price (INR) for paid access to this track's exam"),
        ),
    ]
