# Generated by Django 6.0.6 on 2026-07-14 12:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0004_certificationtrack_addon_price_and_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenBadgeCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_hash', models.CharField(blank=True, default='', max_length=128)),
                ('achievement_name', models.CharField(max_length=255)),
                ('achievement_description', models.TextField(blank=True, default='')),
                ('credential', models.JSONField(blank=True, default=dict)),
                ('public_key_b64', models.CharField(blank=True, default='', max_length=128)),
                ('proof_value', models.TextField(blank=True, default='')),
                ('issued_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_badge', to='certifications.certearnedcertificate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
