# Generated by Django 6.0.6 on 2026-08-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0005_openbadgecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='certearnedcertificate',
            name='revoked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='certearnedcertificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certearnedcertificate',
            name='revoked_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
