# Generated by Django 5.2.12 on 2026-03-30 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('achievement', 'Achievement Unlocked'), ('lab_expired', 'Lab Expired'), ('streak', 'Streak Alert'), ('system', 'System Message'), ('welcome', 'Welcome')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'read'], name='notificatio_user_id_878a13_idx')],
            },
        ),
    ]
