# Generated by Django 6.0.6 on 2026-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_alter_emaillog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='email_marketing',
            field=models.BooleanField(default=False, help_text='Subscribe reminders, product tips, and benefit emails (opt-in)'),
        ),
    ]
