# Generated by Django 5.2.12 on 2026-03-31 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0002_scenario_cloud_ami_scenario_cloud_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('scenario', 'Scenario Rating'), ('platform', 'Platform Rating')], max_length=20)),
                ('score', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='question_bank.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating_type', '-created_at'], name='ratings_rat_rating__0680c7_idx'), models.Index(fields=['scenario', '-created_at'], name='ratings_rat_scenari_4926f9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('rating_type', 'scenario')), fields=('user', 'scenario'), name='unique_scenario_rating'), models.UniqueConstraint(condition=models.Q(('rating_type', 'platform')), fields=('user', 'rating_type'), name='unique_platform_rating')],
            },
        ),
    ]
