# Generated by Django 6.0.6 on 2026-06-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_templates_invitations_async_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='last_practical_submission',
            field=models.JSONField(blank=True, default=dict, help_text='{text, topic, method, question_id, validated_at} of the last passed practical answer'),
        ),
    ]
