# Generated by Django — index for interview message lookups by round + created_at

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0011_interviewround_paused_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="interviewmessage",
            index=models.Index(fields=["round", "created_at"], name="interviews_msg_round_created_idx"),
        ),
    ]
