# Generated by Django 6.0.6 on 2026-07-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0012_interviewmessage_round_created_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interviewmessage',
            new_name='iv_msg_round_created_idx',
            old_name='interviews_msg_round_created_idx',
        ),
    ]
