# Generated by Django 6.0.6 on 2026-08-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0013_rename_interviews_msg_round_created_idx_iv_msg_round_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='consent_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='consent_policy_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
