# Generated by Django 5.x for session 71 — InterviewRound.language

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interviews", "0014_interviewround_consent_granted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewround",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("hi", "Hindi"), ("te", "Telugu")],
                default="en",
                max_length=8,
            ),
        ),
    ]
