# Generated by Django 6.0.6 on 2026-07-14 12:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0011_alter_labsession_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarRoomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVESTIGATING', 'Investigating'), ('MITIGATING', 'Mitigating'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_action_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('time_to_first_action_seconds', models.FloatField(blank=True, null=True)),
                ('mttr_seconds', models.FloatField(blank=True, null=True)),
                ('team_score', models.IntegerField(blank=True, null=True)),
                ('lab_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='war_rooms', to='labs.labsession')),
            ],
        ),
        migrations.CreateModel(
            name='WarRoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('IC', 'Incident Commander'), ('OPS', 'Ops'), ('COMMS', 'Comms'), ('SCRIBE', 'Scribe')], default='OPS', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_room_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='terminal.warroomsession')),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
    ]
