# Generated by Django 5.2.12 on 2026-03-30 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(choices=[('first_solve', 'First Solve'), ('speed_demon', 'Speed Demon'), ('no_hints', 'No Hints Used'), ('perfect_score', 'Perfect Score'), ('streak_3', '3-Day Streak'), ('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('easy_master', 'Easy Master'), ('medium_master', 'Medium Master'), ('hard_master', 'Hard Master'), ('ten_solves', '10 Scenarios Solved'), ('fifty_solves', '50 Scenarios Solved'), ('hundred_solves', '100 Scenarios Solved')], max_length=30)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserScenarioProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('best_time', models.PositiveIntegerField(blank=True, help_text='Best completion time in seconds', null=True)),
                ('hints_used_best', models.PositiveIntegerField(default=0, help_text='Hints used in best attempt')),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='question_bank.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scenario')},
            },
        ),
    ]
