export const SERVICE_CONFIGS = {
  lambda: {
    title: 'Lambda',
    category: 'Compute',
    desc: 'Run code without provisioning or managing servers',
    primary: 'functions',
    resources: {
      functions: {
        label: 'Functions',
        createLabel: 'Create function',
        idLabel: 'Function name',
        arnService: 'lambda',
        arnResource: (r) => `function:${r.name}`,
        fields: [
          { key: 'name', label: 'Function name' },
          { key: 'runtime', label: 'Runtime' },
          { key: 'memory', label: 'Memory', suffix: ' MB' },
          { key: 'timeout', label: 'Timeout', suffix: ' sec' },
          { key: 'status', label: 'State', badge: true },
        ],
        defaults: { runtime: 'Python 3.12', memory: 128, timeout: 30, status: 'Active', handler: 'lambda_function.lambda_handler' },
      },
      layers: { label: 'Layers', createLabel: 'Create layer', idLabel: 'Layer name', arnService: 'lambda', arnResource: (r) => `layer:${r.name}`, fields: [{ key: 'name', label: 'Layer name' }, { key: 'runtime', label: 'Compatible runtime' }, { key: 'version', label: 'Latest version' }], defaults: { runtime: 'Python 3.12', version: 1, status: 'Active' } },
    },
  },
  rds: {
    title: 'RDS',
    category: 'Database',
    desc: 'Managed relational database service',
    primary: 'databases',
    resources: {
      databases: { label: 'Databases', createLabel: 'Create database', idLabel: 'DB identifier', arnService: 'rds', arnResource: (r) => `db:${r.name}`, fields: [{ key: 'name', label: 'DB identifier' }, { key: 'engine', label: 'Engine' }, { key: 'class', label: 'Class' }, { key: 'storage', label: 'Storage', suffix: ' GiB' }, { key: 'status', label: 'Status', badge: true }], defaults: { engine: 'PostgreSQL 15.4', class: 'db.t3.micro', storage: 20, status: 'available', endpoint: 'simulated.cluster.us-east-1.rds.amazonaws.com:5432' } },
      snapshots: { label: 'Snapshots', createLabel: 'Create snapshot', idLabel: 'Snapshot name', arnService: 'rds', arnResource: (r) => `snapshot:${r.name}`, fields: [{ key: 'name', label: 'Snapshot' }, { key: 'engine', label: 'Engine' }, { key: 'status', label: 'Status', badge: true }, { key: 'created', label: 'Created' }], defaults: { engine: 'PostgreSQL', status: 'available' } },
    },
  },
  dynamodb: {
    title: 'DynamoDB',
    category: 'Database',
    desc: 'Fast and flexible NoSQL database service',
    primary: 'tables',
    resources: {
      tables: { label: 'Tables', createLabel: 'Create table', idLabel: 'Table name', arnService: 'dynamodb', arnResource: (r) => `table/${r.name}`, fields: [{ key: 'name', label: 'Table name' }, { key: 'partitionKey', label: 'Partition key' }, { key: 'billingMode', label: 'Billing mode' }, { key: 'status', label: 'Status', badge: true }, { key: 'items', label: 'Items' }], defaults: { partitionKey: 'pk (String)', sortKey: 'sk (String)', billingMode: 'On-demand', status: 'Active', items: 42 } },
    },
  },
  cloudformation: {
    title: 'CloudFormation',
    category: 'Management & Governance',
    desc: 'Model and provision AWS resources with templates',
    primary: 'stacks',
    resources: {
      stacks: { label: 'Stacks', createLabel: 'Create stack', idLabel: 'Stack name', arnService: 'cloudformation', arnResource: (r) => `stack/${r.name}/${r.id}`, fields: [{ key: 'name', label: 'Stack name' }, { key: 'status', label: 'Status', badge: true }, { key: 'resources', label: 'Resources' }, { key: 'created', label: 'Created' }], defaults: { status: 'CREATE_COMPLETE', resources: 4 } },
      'change-sets': { label: 'Change sets', createLabel: 'Create change set', idLabel: 'Change set name', arnService: 'cloudformation', arnResource: (r) => `changeSet/${r.name}/${r.id}`, fields: [{ key: 'name', label: 'Change set' }, { key: 'status', label: 'Status', badge: true }, { key: 'changes', label: 'Changes' }], defaults: { status: 'CREATE_COMPLETE', changes: 2 } },
    },
  },
  route53: {
    title: 'Route 53',
    category: 'Networking & Content Delivery',
    desc: 'Highly available and scalable DNS',
    primary: 'hosted-zones',
    resources: {
      'hosted-zones': { label: 'Hosted zones', createLabel: 'Create hosted zone', idLabel: 'Domain name', arnService: 'route53', arnResource: (r) => `hostedzone/${r.id}`, fields: [{ key: 'name', label: 'Domain name' }, { key: 'type', label: 'Type' }, { key: 'records', label: 'Record count' }, { key: 'status', label: 'Status', badge: true }], defaults: { type: 'Public', records: 5, status: 'available' } },
      'health-checks': { label: 'Health checks', createLabel: 'Create health check', idLabel: 'Health check name', arnService: 'route53', arnResource: (r) => `healthcheck/${r.id}`, fields: [{ key: 'name', label: 'Name' }, { key: 'protocol', label: 'Protocol' }, { key: 'status', label: 'Status', badge: true }], defaults: { protocol: 'HTTPS', status: 'Healthy' } },
    },
  },
  sns: {
    title: 'SNS',
    category: 'Application Integration',
    desc: 'Pub/sub messaging and mobile notifications',
    primary: 'topics',
    resources: {
      topics: { label: 'Topics', createLabel: 'Create topic', idLabel: 'Topic name', arnService: 'sns', arnResource: (r) => r.name, fields: [{ key: 'name', label: 'Topic name' }, { key: 'type', label: 'Type' }, { key: 'subscriptions', label: 'Subscriptions' }, { key: 'status', label: 'Status', badge: true }], defaults: { type: 'Standard', subscriptions: 1, status: 'Active' } },
      subscriptions: { label: 'Subscriptions', createLabel: 'Create subscription', idLabel: 'Endpoint', arnService: 'sns', arnResource: (r) => r.id, fields: [{ key: 'name', label: 'Endpoint' }, { key: 'protocol', label: 'Protocol' }, { key: 'status', label: 'Status', badge: true }], defaults: { protocol: 'Email', status: 'Confirmed' } },
    },
  },
  sqs: {
    title: 'SQS',
    category: 'Application Integration',
    desc: 'Managed message queues',
    primary: 'queues',
    resources: {
      queues: { label: 'Queues', createLabel: 'Create queue', idLabel: 'Queue name', arnService: 'sqs', arnResource: (r) => r.name, fields: [{ key: 'name', label: 'Queue name' }, { key: 'type', label: 'Type' }, { key: 'messages', label: 'Available messages' }, { key: 'status', label: 'Status', badge: true }], defaults: { type: 'Standard', messages: 0, status: 'Active' } },
    },
  },
  secretsmanager: {
    title: 'Secrets Manager',
    category: 'Security, Identity & Compliance',
    desc: 'Protect secrets needed to access applications and services',
    primary: 'secrets',
    resources: {
      secrets: { label: 'Secrets', createLabel: 'Store a new secret', idLabel: 'Secret name', arnService: 'secretsmanager', arnResource: (r) => `secret:${r.name}-${r.id.slice(-6)}`, fields: [{ key: 'name', label: 'Secret name' }, { key: 'rotation', label: 'Rotation' }, { key: 'lastChanged', label: 'Last changed' }, { key: 'status', label: 'Status', badge: true }], defaults: { rotation: 'Disabled', lastChanged: 'Today', status: 'Active' } },
    },
  },
  acm: {
    title: 'Certificate Manager',
    category: 'Security, Identity & Compliance',
    desc: 'Provision, manage, and deploy SSL/TLS certificates',
    primary: 'certificates',
    resources: {
      certificates: { label: 'Certificates', createLabel: 'Request certificate', idLabel: 'Domain name', arnService: 'acm', arnResource: (r) => `certificate/${r.id}`, fields: [{ key: 'name', label: 'Domain name' }, { key: 'type', label: 'Type' }, { key: 'status', label: 'Status', badge: true }, { key: 'expires', label: 'Expires' }], defaults: { type: 'Amazon issued', status: 'Issued', expires: '2027-03-01' } },
    },
  },
  cloudfront: {
    title: 'CloudFront',
    category: 'Networking & Content Delivery',
    desc: 'Global content delivery network',
    primary: 'distributions',
    resources: {
      distributions: { label: 'Distributions', createLabel: 'Create distribution', idLabel: 'Distribution name', arnService: 'cloudfront', arnResource: (r) => `distribution/${r.id}`, fields: [{ key: 'name', label: 'Distribution' }, { key: 'domainName', label: 'Domain name' }, { key: 'status', label: 'Status', badge: true }, { key: 'priceClass', label: 'Price class' }], defaults: { domainName: 'd111111abcdef8.cloudfront.net', status: 'Deployed', priceClass: 'Use all edge locations' } },
    },
  },
  eks: {
    title: 'EKS',
    category: 'Containers',
    desc: 'Managed Kubernetes service',
    primary: 'clusters',
    resources: {
      clusters: { label: 'Clusters', createLabel: 'Create cluster', idLabel: 'Cluster name', arnService: 'eks', arnResource: (r) => `cluster/${r.name}`, fields: [{ key: 'name', label: 'Name' }, { key: 'version', label: 'Kubernetes version' }, { key: 'nodes', label: 'Nodes' }, { key: 'status', label: 'Status', badge: true }], defaults: { version: '1.30', nodes: 3, status: 'Active' } },
      'node-groups': { label: 'Node groups', createLabel: 'Create node group', idLabel: 'Node group name', arnService: 'eks', arnResource: (r) => `nodegroup/demo/${r.name}/${r.id}`, fields: [{ key: 'name', label: 'Name' }, { key: 'instanceType', label: 'Instance type' }, { key: 'desired', label: 'Desired size' }, { key: 'status', label: 'Status', badge: true }], defaults: { instanceType: 't3.medium', desired: 3, status: 'Active' } },
    },
  },
  ecs: {
    title: 'ECS',
    category: 'Containers',
    desc: 'Run and manage containers',
    primary: 'clusters',
    resources: {
      clusters: { label: 'Clusters', createLabel: 'Create cluster', idLabel: 'Cluster name', arnService: 'ecs', arnResource: (r) => `cluster/${r.name}`, fields: [{ key: 'name', label: 'Cluster' }, { key: 'services', label: 'Services' }, { key: 'tasks', label: 'Running tasks' }, { key: 'status', label: 'Status', badge: true }], defaults: { services: 1, tasks: 2, status: 'Active' } },
      services: { label: 'Services', createLabel: 'Create service', idLabel: 'Service name', arnService: 'ecs', arnResource: (r) => `service/default/${r.name}`, fields: [{ key: 'name', label: 'Service' }, { key: 'desired', label: 'Desired' }, { key: 'running', label: 'Running' }, { key: 'status', label: 'Status', badge: true }], defaults: { desired: 2, running: 2, status: 'Active' } },
      tasks: { label: 'Tasks', createLabel: 'Run task', idLabel: 'Task family', arnService: 'ecs', arnResource: (r) => `task/default/${r.id}`, fields: [{ key: 'name', label: 'Task' }, { key: 'launchType', label: 'Launch type' }, { key: 'status', label: 'Status', badge: true }], defaults: { launchType: 'FARGATE', status: 'RUNNING' } },
    },
  },
  ecr: {
    title: 'ECR',
    category: 'Containers',
    desc: 'Container image registry',
    primary: 'repositories',
    resources: {
      repositories: { label: 'Repositories', createLabel: 'Create repository', idLabel: 'Repository name', arnService: 'ecr', arnResource: (r) => `repository/${r.name}`, fields: [{ key: 'name', label: 'Repository name' }, { key: 'images', label: 'Images' }, { key: 'scanOnPush', label: 'Scan on push' }, { key: 'status', label: 'Status', badge: true }], defaults: { images: 3, scanOnPush: 'Enabled', status: 'Active' } },
    },
  },
  apigateway: {
    title: 'API Gateway',
    category: 'Networking & Content Delivery',
    desc: 'Create, publish, maintain, monitor, and secure APIs',
    primary: 'apis',
    resources: { apis: { label: 'APIs', createLabel: 'Create API', idLabel: 'API name', arnService: 'apigateway', arnResource: (r) => `/apis/${r.id}`, fields: [{ key: 'name', label: 'API name' }, { key: 'type', label: 'Type' }, { key: 'stage', label: 'Stage' }, { key: 'status', label: 'Status', badge: true }], defaults: { type: 'HTTP', stage: 'prod', status: 'Active' } } },
  },
  eventbridge: {
    title: 'EventBridge',
    category: 'Application Integration',
    desc: 'Serverless event bus',
    primary: 'rules',
    resources: { rules: { label: 'Rules', createLabel: 'Create rule', idLabel: 'Rule name', arnService: 'events', arnResource: (r) => `rule/${r.name}`, fields: [{ key: 'name', label: 'Rule name' }, { key: 'eventBus', label: 'Event bus' }, { key: 'targets', label: 'Targets' }, { key: 'status', label: 'Status', badge: true }], defaults: { eventBus: 'default', targets: 1, status: 'Enabled' } } },
  },
  states: {
    title: 'Step Functions',
    category: 'Application Integration',
    desc: 'Coordinate distributed applications',
    primary: 'state-machines',
    resources: { 'state-machines': { label: 'State machines', createLabel: 'Create state machine', idLabel: 'State machine name', arnService: 'states', arnResource: (r) => `stateMachine:${r.name}`, fields: [{ key: 'name', label: 'Name' }, { key: 'type', label: 'Type' }, { key: 'executions', label: 'Executions' }, { key: 'status', label: 'Status', badge: true }], defaults: { type: 'STANDARD', executions: 12, status: 'Active' } } },
  },
  kms: {
    title: 'KMS',
    category: 'Security, Identity & Compliance',
    desc: 'Create and control cryptographic keys',
    primary: 'keys',
    resources: { keys: { label: 'Customer managed keys', createLabel: 'Create key', idLabel: 'Alias', arnService: 'kms', arnResource: (r) => `key/${r.id}`, fields: [{ key: 'name', label: 'Alias' }, { key: 'usage', label: 'Key usage' }, { key: 'rotation', label: 'Rotation' }, { key: 'status', label: 'Status', badge: true }], defaults: { usage: 'Encrypt and decrypt', rotation: 'Enabled', status: 'Enabled' } } },
  },
  cloudtrail: {
    title: 'CloudTrail',
    category: 'Management & Governance',
    desc: 'Track user activity and API usage',
    primary: 'trails',
    resources: { trails: { label: 'Trails', createLabel: 'Create trail', idLabel: 'Trail name', arnService: 'cloudtrail', arnResource: (r) => `trail/${r.name}`, fields: [{ key: 'name', label: 'Trail name' }, { key: 'multiRegion', label: 'Multi-region' }, { key: 'logging', label: 'Logging' }, { key: 'status', label: 'Status', badge: true }], defaults: { multiRegion: 'Yes', logging: 'On', status: 'Active' } } },
  },
  config: {
    title: 'AWS Config',
    category: 'Management & Governance',
    desc: 'Assess, audit, and evaluate resource configurations',
    primary: 'rules',
    resources: { rules: { label: 'Rules', createLabel: 'Add rule', idLabel: 'Rule name', arnService: 'config', arnResource: (r) => `config-rule/${r.id}`, fields: [{ key: 'name', label: 'Rule name' }, { key: 'compliance', label: 'Compliance' }, { key: 'evaluations', label: 'Evaluations' }, { key: 'status', label: 'Status', badge: true }], defaults: { compliance: 'COMPLIANT', evaluations: 24, status: 'Active' } } },
  },
  systemsmanager: {
    title: 'Systems Manager',
    category: 'Management & Governance',
    desc: 'View and control infrastructure at scale',
    primary: 'parameters',
    resources: { parameters: { label: 'Parameter Store', createLabel: 'Create parameter', idLabel: 'Parameter name', arnService: 'ssm', arnResource: (r) => `parameter/${r.name}`, fields: [{ key: 'name', label: 'Name' }, { key: 'type', label: 'Type' }, { key: 'tier', label: 'Tier' }, { key: 'status', label: 'Status', badge: true }], defaults: { type: 'String', tier: 'Standard', status: 'Active' } } },
  },
  billing: {
    title: 'Billing and Cost Management',
    category: 'Cloud Financial Management',
    desc: 'Track usage, cost, budgets, and forecasts',
    primary: 'budgets',
    resources: { budgets: { label: 'Budgets', createLabel: 'Create budget', idLabel: 'Budget name', arnService: 'budgets', arnResource: (r) => `budget/${r.name}`, fields: [{ key: 'name', label: 'Budget name' }, { key: 'amount', label: 'Amount', prefix: '$' }, { key: 'actual', label: 'Actual', prefix: '$' }, { key: 'status', label: 'Status', badge: true }], defaults: { amount: 100, actual: 47.32, status: 'OK' } } },
  },
  waf: {
    title: 'WAF & Shield',
    category: 'Security, Identity & Compliance',
    desc: 'Protect web applications from common exploits',
    primary: 'web-acls',
    resources: { 'web-acls': { label: 'Web ACLs', createLabel: 'Create web ACL', idLabel: 'Web ACL name', arnService: 'wafv2', arnResource: (r) => `regional/webacl/${r.name}/${r.id}`, fields: [{ key: 'name', label: 'Name' }, { key: 'scope', label: 'Scope' }, { key: 'rules', label: 'Rules' }, { key: 'status', label: 'Status', badge: true }], defaults: { scope: 'Regional', rules: 3, status: 'Active' } } },
  },
  cognito: {
    title: 'Cognito',
    category: 'Security, Identity & Compliance',
    desc: 'User identity and access for apps',
    primary: 'user-pools',
    resources: { 'user-pools': { label: 'User pools', createLabel: 'Create user pool', idLabel: 'User pool name', arnService: 'cognito-idp', arnResource: (r) => `userpool/${r.id}`, fields: [{ key: 'name', label: 'Pool name' }, { key: 'users', label: 'Users' }, { key: 'mfa', label: 'MFA' }, { key: 'status', label: 'Status', badge: true }], defaults: { users: 24, mfa: 'Optional', status: 'Enabled' } } },
  },
  elasticache: {
    title: 'ElastiCache',
    category: 'Database',
    desc: 'In-memory caching service',
    primary: 'clusters',
    resources: { clusters: { label: 'Clusters', createLabel: 'Create cluster', idLabel: 'Cluster name', arnService: 'elasticache', arnResource: (r) => `cluster:${r.name}`, fields: [{ key: 'name', label: 'Cluster name' }, { key: 'engine', label: 'Engine' }, { key: 'nodes', label: 'Nodes' }, { key: 'status', label: 'Status', badge: true }], defaults: { engine: 'Redis OSS', nodes: 2, status: 'available' } } },
  },
  redshift: {
    title: 'Redshift',
    category: 'Analytics',
    desc: 'Cloud data warehouse',
    primary: 'clusters',
    resources: { clusters: { label: 'Clusters', createLabel: 'Create cluster', idLabel: 'Cluster name', arnService: 'redshift', arnResource: (r) => `cluster:${r.name}`, fields: [{ key: 'name', label: 'Cluster name' }, { key: 'nodeType', label: 'Node type' }, { key: 'nodes', label: 'Nodes' }, { key: 'status', label: 'Status', badge: true }], defaults: { nodeType: 'ra3.xlplus', nodes: 2, status: 'available' } } },
  },
  opensearch: {
    title: 'OpenSearch Service',
    category: 'Analytics',
    desc: 'Search, visualize, and analyze text and logs',
    primary: 'domains',
    resources: { domains: { label: 'Domains', createLabel: 'Create domain', idLabel: 'Domain name', arnService: 'es', arnResource: (r) => `domain/${r.name}`, fields: [{ key: 'name', label: 'Domain name' }, { key: 'version', label: 'Version' }, { key: 'nodes', label: 'Nodes' }, { key: 'status', label: 'Status', badge: true }], defaults: { version: 'OpenSearch 2.13', nodes: 3, status: 'Active' } } },
  },
  kinesis: {
    title: 'Kinesis',
    category: 'Analytics',
    desc: 'Collect, process, and analyze streaming data',
    primary: 'streams',
    resources: { streams: { label: 'Data streams', createLabel: 'Create stream', idLabel: 'Stream name', arnService: 'kinesis', arnResource: (r) => `stream/${r.name}`, fields: [{ key: 'name', label: 'Stream name' }, { key: 'mode', label: 'Capacity mode' }, { key: 'shards', label: 'Shards' }, { key: 'status', label: 'Status', badge: true }], defaults: { mode: 'On-demand', shards: 4, status: 'Active' } } },
  },
  glue: {
    title: 'Glue',
    category: 'Analytics',
    desc: 'Serverless data integration',
    primary: 'jobs',
    resources: { jobs: { label: 'ETL jobs', createLabel: 'Create job', idLabel: 'Job name', arnService: 'glue', arnResource: (r) => `job/${r.name}`, fields: [{ key: 'name', label: 'Job name' }, { key: 'type', label: 'Type' }, { key: 'runs', label: 'Runs' }, { key: 'status', label: 'Status', badge: true }], defaults: { type: 'Spark', runs: 8, status: 'Active' } }, databases: { label: 'Databases', createLabel: 'Create database', idLabel: 'Database name', arnService: 'glue', arnResource: (r) => `database/${r.name}`, fields: [{ key: 'name', label: 'Database' }, { key: 'tables', label: 'Tables' }, { key: 'status', label: 'Status', badge: true }], defaults: { tables: 6, status: 'Active' } } },
  },
  athena: {
    title: 'Athena',
    category: 'Analytics',
    desc: 'Query data in S3 using SQL',
    primary: 'workgroups',
    resources: { workgroups: { label: 'Workgroups', createLabel: 'Create workgroup', idLabel: 'Workgroup name', arnService: 'athena', arnResource: (r) => `workgroup/${r.name}`, fields: [{ key: 'name', label: 'Workgroup' }, { key: 'queries', label: 'Queries' }, { key: 'bytesScanned', label: 'Bytes scanned' }, { key: 'status', label: 'Status', badge: true }], defaults: { queries: 18, bytesScanned: '1.2 GB', status: 'Enabled' } } },
  },
  codecommit: {
    title: 'CodeCommit',
    category: 'Developer Tools',
    desc: 'Private Git repositories',
    primary: 'repositories',
    resources: { repositories: { label: 'Repositories', createLabel: 'Create repository', idLabel: 'Repository name', arnService: 'codecommit', arnResource: (r) => r.name, fields: [{ key: 'name', label: 'Repository' }, { key: 'defaultBranch', label: 'Default branch' }, { key: 'commits', label: 'Commits' }, { key: 'status', label: 'Status', badge: true }], defaults: { defaultBranch: 'main', commits: 42, status: 'Active' } } },
  },
  codebuild: {
    title: 'CodeBuild',
    category: 'Developer Tools',
    desc: 'Build and test code',
    primary: 'projects',
    resources: { projects: { label: 'Projects', createLabel: 'Create project', idLabel: 'Project name', arnService: 'codebuild', arnResource: (r) => `project/${r.name}`, fields: [{ key: 'name', label: 'Project' }, { key: 'environment', label: 'Environment' }, { key: 'lastBuild', label: 'Last build' }, { key: 'status', label: 'Status', badge: true }], defaults: { environment: 'Linux container', lastBuild: 'SUCCEEDED', status: 'Active' } } },
  },
  codepipeline: {
    title: 'CodePipeline',
    category: 'Developer Tools',
    desc: 'Continuous delivery pipelines',
    primary: 'pipelines',
    resources: { pipelines: { label: 'Pipelines', createLabel: 'Create pipeline', idLabel: 'Pipeline name', arnService: 'codepipeline', arnResource: (r) => r.name, fields: [{ key: 'name', label: 'Pipeline' }, { key: 'stages', label: 'Stages' }, { key: 'lastExecution', label: 'Last execution' }, { key: 'status', label: 'Status', badge: true }], defaults: { stages: 3, lastExecution: 'Succeeded', status: 'Active' } } },
  },
  organizations: {
    title: 'Organizations',
    category: 'Management & Governance',
    desc: 'Centrally manage AWS accounts',
    primary: 'accounts',
    resources: { accounts: { label: 'Accounts', createLabel: 'Create account', idLabel: 'Account name', arnService: 'organizations', arnResource: (r) => `account/o-example/${r.id}`, fields: [{ key: 'name', label: 'Account name' }, { key: 'email', label: 'Email' }, { key: 'ou', label: 'OU' }, { key: 'status', label: 'Status', badge: true }], defaults: { email: 'team@example.com', ou: 'Engineering', status: 'ACTIVE' } } },
  },
  servicequotas: {
    title: 'Service Quotas',
    category: 'Management & Governance',
    desc: 'View and manage service limits',
    primary: 'requests',
    resources: { requests: { label: 'Quota requests', createLabel: 'Request quota increase', idLabel: 'Quota request name', arnService: 'servicequotas', arnResource: (r) => `request/${r.id}`, fields: [{ key: 'name', label: 'Quota' }, { key: 'service', label: 'Service' }, { key: 'requested', label: 'Requested value' }, { key: 'status', label: 'Status', badge: true }], defaults: { service: 'EC2', requested: 64, status: 'CASE_OPENED' } } },
  },
  health: {
    title: 'Health Dashboard',
    category: 'Management & Governance',
    desc: 'Personalized AWS service health alerts',
    primary: 'events',
    resources: { events: { label: 'Events', createLabel: 'Create simulated event', idLabel: 'Event title', arnService: 'health', arnResource: (r) => `event/${r.id}`, fields: [{ key: 'name', label: 'Event' }, { key: 'service', label: 'Service' }, { key: 'impact', label: 'Impact' }, { key: 'status', label: 'Status', badge: true }], defaults: { service: 'EC2', impact: 'Informational', status: 'open' } } },
  },
  trustedadvisor: {
    title: 'Trusted Advisor',
    category: 'Management & Governance',
    desc: 'Best-practice checks and recommendations',
    primary: 'checks',
    resources: { checks: { label: 'Checks', createLabel: 'Add simulated check', idLabel: 'Check name', arnService: 'trustedadvisor', arnResource: (r) => `check/${r.id}`, fields: [{ key: 'name', label: 'Check' }, { key: 'category', label: 'Category' }, { key: 'affected', label: 'Affected resources' }, { key: 'status', label: 'Status', badge: true }], defaults: { category: 'Security', affected: 0, status: 'OK' } } },
  },
  wellarchitected: {
    title: 'Well-Architected Tool',
    category: 'Management & Governance',
    desc: 'Review workloads against AWS best practices',
    primary: 'workloads',
    resources: { workloads: { label: 'Workloads', createLabel: 'Define workload', idLabel: 'Workload name', arnService: 'wellarchitected', arnResource: (r) => `workload/${r.id}`, fields: [{ key: 'name', label: 'Workload' }, { key: 'lenses', label: 'Lenses' }, { key: 'risks', label: 'High risks' }, { key: 'status', label: 'Status', badge: true }], defaults: { lenses: 'AWS Well-Architected Framework', risks: 2, status: 'Active' } } },
  },
}

export const GENERIC_SERVICE_KEYS = Object.keys(SERVICE_CONFIGS)

export function getResourceConfig(serviceKey, resourceKey) {
  return SERVICE_CONFIGS[serviceKey]?.resources?.[resourceKey]
}
