# Generated by Django 6.0.6 on 2026-07-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_paymenttransaction_cgst_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('provider', models.CharField(default='razorpay', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Processed webhook event',
                'verbose_name_plural': 'Processed webhook events',
                'ordering': ['-created_at'],
            },
        ),
    ]
