# Generated by Django 6.0.6 on 2026-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_processedwebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='FL', max_length=12)),
                ('financial_year', models.CharField(help_text='e.g. 26-27', max_length=7)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'invoice series',
                'unique_together': {('prefix', 'financial_year')},
            },
        ),
    ]
