# Generated by Django 6.0.6 on 2026-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_invoiceseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologysubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the customer cancelled. Access continues until expires_at (audit Z1-11); this only stops renewal.', null=True),
        ),
    ]
