# Generated by Django 5.2.12 on 2026-03-30 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(blank=True, help_text='Null means global leaderboard', null=True, on_delete=django.db.models.deletion.CASCADE, to='question_bank.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('user', 'scenario')},
            },
        ),
    ]
