# User roles
ROLE_USER = "user"
ROLE_ADMIN = "admin"

# Lab statuses
LAB_PENDING = "PENDING"
LAB_RUNNING = "RUNNING"
LAB_STOPPED = "STOPPED"
LAB_FAILED = "FAILED"

LAB_STATUSES = [
    LAB_PENDING,
    LAB_RUNNING,
    LAB_STOPPED,
    LAB_FAILED,
]

# Difficulty levels
DIFFICULTY_EASY = "easy"
DIFFICULTY_MEDIUM = "medium"
DIFFICULTY_HARD = "hard"

DIFFICULTY_LEVELS = [
    DIFFICULTY_EASY,
    DIFFICULTY_MEDIUM,
    DIFFICULTY_HARD,
]

