# Generated by Django 5.2.12 on 2026-03-30 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Hint order (1, 2, 3...)')),
                ('content', models.TextField()),
                ('penalty', models.PositiveIntegerField(default=0, help_text='Penalty points for using this hint')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='question_bank.scenario')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('scenario', 'order')},
            },
        ),
    ]
