# Generated by Django 4.2.29 on 2026-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contactmessage_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='currency_preference',
            field=models.CharField(choices=[('INR', 'Indian Rupees (₹)'), ('USD', 'US Dollars ($)')], default='INR', help_text='Preferred currency for pricing display', max_length=3),
        ),
    ]
