# Generated by Django 6.0.6 on 2026-08-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_hash_email_verification_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_state',
            field=models.CharField(blank=True, default='', help_text="Indian state/UT used as the GST place of supply. Blank means no address on record, which under the CGST place-of-supply rules for B2C services falls back to the seller's state (audit Z1-13).", max_length=100),
        ),
    ]
