# Generated by Django 6.0.6 on 2026-08-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_billing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='privacy_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='terms_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
