# Generated by Django 6.0.6 on 2026-08-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_mfadevice_mfarecoverycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
