# Generated by Django 5.x on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_profile_mfa_prompt_dismissed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="interview_processing_consent",
            field=models.BooleanField(
                default=True,
                help_text="Consent to process interview transcripts/scores for practice rounds",
            ),
        ),
    ]
