# Generated by Django 5.2.12 on 2026-03-30 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('TERMINATED', 'Terminated'), ('EXPIRED', 'Expired')], default='PROVISIONING', max_length=20)),
                ('provider', models.CharField(default='docker', help_text='docker | aws', max_length=50)),
                ('container_id', models.CharField(blank=True, max_length=255, null=True)),
                ('container_name', models.CharField(blank=True, max_length=255, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_host', models.CharField(blank=True, max_length=255)),
                ('ssh_user', models.CharField(blank=True, default='root', max_length=50)),
                ('ssh_key_path', models.CharField(blank=True, max_length=255)),
                ('duration_limit', models.PositiveIntegerField(default=3600, help_text='Max duration in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('validation_passed', models.BooleanField(default=False)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='question_bank.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='labs_labses_user_id_386172_idx'), models.Index(fields=['status', 'started_at'], name='labs_labses_status_8decd6_idx')],
            },
        ),
    ]
