# Generated by Django 6.0.6 on 2026-07-14 12:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0011_alter_labsession_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.CharField(blank=True, default='', max_length=100)),
                ('seed', models.CharField(blank=True, default='', max_length=100)),
                ('root_cause', models.TextField(blank=True, default='')),
                ('detection_signal', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(blank=True, default='', max_length=20)),
                ('escalations', models.JSONField(blank=True, default=list, help_text='Ordered escalation records [{step, kind, note}] applied by the Director')),
                ('director_plan', models.JSONField(blank=True, default=dict, help_text='Full Director.summary() snapshot (template, what_worked, action_items)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('mitigated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('lab_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_runs', to='labs.labsession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Postmortem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unguessable token that gates public read access (no auth).', unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Structured postmortem (timeline, root cause, MTTR, action items).')),
                ('markdown', models.TextField(blank=True, default='', help_text='Deterministic Markdown rendering of the postmortem.')),
                ('is_public', models.BooleanField(default=True, help_text='If False the public token endpoint returns 404 (owner can unshare).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postmortem', to='labs.incidentrun')),
                ('lab_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postmortems', to='labs.labsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incidentrun',
            index=models.Index(fields=['lab_session', 'started_at'], name='labs_incrun_session_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentrun',
            index=models.Index(fields=['template_key'], name='labs_incrun_template_idx'),
        ),
    ]
