"""Extended topic snippets — generated/curated for all TECH_TOPICS keys."""
from __future__ import annotations

EXTENDED_TOPIC_SNIPPETS: dict[str, dict[str, str]] = {
    'accessibility': {
        'label': 'web accessibility',
        'concept': 'ARIA roles, keyboard navigation, contrast, and screen-reader semantics',
        'inspect': 'axe/Lighthouse audits, tab order, and semantic landmarks',
        'symptom': 'keyboard users cannot complete flows or screen readers announce the wrong state',
        'verify': 'critical paths pass WCAG-oriented checks without breaking visuals',
    },
    'active-directory': {
        'label': 'Active Directory',
        'concept': 'core concepts and daily workflows for active directory',
        'inspect': 'status commands, logs, and configuration related to active directory',
        'symptom': 'Active Directory misconfiguration causes user-visible failures or operational risk',
        'verify': 'Active Directory meets expected health checks after your changes',
    },
    'agents': {
        'label': 'AI agents',
        'concept': 'tool use, planning loops, memory, and guardrails for autonomous workflows',
        'inspect': 'agent traces, tool call logs, and evaluation harness output',
        'symptom': 'agents loop, call wrong tools, or leak context across sessions',
        'verify': 'agent completes the task with bounded steps and auditable tool calls',
    },
    'alerting': {
        'label': 'alerting rules',
        'concept': 'thresholds, burn rates, inhibition, and on-call routing',
        'inspect': 'alert rule definitions, firing history, and notification logs',
        'symptom': 'alerts never fire or page constantly without actionable context',
        'verify': 'alerts fire for real regressions and stay quiet during expected noise',
    },
    'alertmanager': {
        'label': 'Alertmanager',
        'concept': 'grouping, inhibition, silences, and receiver routes',
        'inspect': 'Alertmanager UI/API, `amtool`, and route trees',
        'symptom': 'duplicate pages flood on-call or real incidents are swallowed',
        'verify': 'routes deliver one clear notification per incident with correct severity',
    },
    'alerts': {
        'label': 'monitoring alerts',
        'concept': 'SLO-based alerts, symptom vs cause, and runbook links',
        'inspect': 'alertmanager/PagerDuty history and rule evaluation logs',
        'symptom': 'on-call is numb to alerts or misses customer-impacting failures',
        'verify': 'each alert maps to a runbook step and reflects user-visible impact',
    },
    'app-engine': {
        'label': 'PeopleSoft App Engine',
        'concept': 'AE programs, sections, state records, and batch timing',
        'inspect': 'Process Scheduler details, AE traces, and SQL for state tables',
        'symptom': 'AE jobs end abnormally or post incorrect accounting',
        'verify': 'programs complete with expected SQL rows and restart cleanly',
    },
    'args': {
        'label': 'shell script arguments',
        'concept': '$1/$@, getopts, defaults, and input validation',
        'inspect': 'script header, `set -u`, and sample invocations',
        'symptom': 'scripts mis-parse flags and destroy data on empty input',
        'verify': 'invalid args fail fast with usage text; happy path works',
    },
    'arrays': {
        'label': 'JavaScript arrays',
        'concept': 'mutation vs copy, map/filter/reduce, and sparse arrays',
        'inspect': 'console experiments, unit tests, and typeof checks',
        'symptom': 'unexpected in-place mutation breaks shared references',
        'verify': 'array helpers return correct results without side effects',
    },
    'artifacts': {
        'label': 'build artifacts',
        'concept': 'immutable packages, versioning, provenance, and retention',
        'inspect': 'artifact repository UI, checksums, and CI publish logs',
        'symptom': 'deploys pull the wrong build or artifacts expire mid-release',
        'verify': 'the intended version is promoted with verifiable checksums',
    },
    'async': {
        'label': 'Python async',
        'concept': 'event loops, await, tasks, and backpressure',
        'inspect': '`asyncio` debug, task graphs, and slow callbacks',
        'symptom': 'coroutines block the loop or deadlock on gathers',
        'verify': 'concurrent I/O completes with predictable cancellation behavior',
    },
    'async-await': {
        'label': 'async/await in JavaScript',
        'concept': 'Promises, microtasks, error propagation, and parallel awaits',
        'inspect': 'browser devtools async stacks and test harnesses',
        'symptom': 'unhandled rejections or race conditions corrupt UI state',
        'verify': 'async flows resolve in order with errors surfaced to callers',
    },
    'audit': {
        'label': 'security auditing',
        'concept': 'audit trails, tamper evidence, and retention',
        'inspect': 'audit logs, SIEM queries, and immutable storage settings',
        'symptom': 'sensitive actions leave no trace or logs are editable',
        'verify': 'every privileged action is attributable with correct timestamps',
    },
    'auditd': {
        'label': 'Linux auditd',
        'concept': 'audit rules, key fields, and AVC correlation',
        'inspect': '`ausearch`, `aureport`, and `/etc/audit/rules.d`',
        'symptom': 'compliance asks who changed a file and audit has no record',
        'verify': 'rules capture the event with uid, syscall, and path',
    },
    'auth': {
        'label': 'authentication',
        'concept': 'sessions, OAuth/OIDC, MFA, and token lifetimes',
        'inspect': 'auth middleware logs, cookie flags, and IdP metadata',
        'symptom': 'users bypass login or sessions never expire',
        'verify': 'only authenticated principals reach protected routes',
    },
    'authoring': {
        'label': 'lab authoring',
        'concept': 'scenario structure, validation hooks, and learner UX',
        'inspect': 'scenario YAML, check scripts, and simulation presets',
        'symptom': 'learners pass without doing work or checks are brittle',
        'verify': 'authoring template validates real skills with clear feedback',
    },
    'autoscaling': {
        'label': 'Kubernetes autoscaling',
        'concept': 'HPA/VPA metrics, cooldowns, and capacity limits',
        'inspect': '`kubectl get hpa`, metrics-server, and deployment replicas',
        'symptom': 'traffic spikes overwhelm pods or autoscaler thrashes',
        'verify': 'replica count tracks load within min/max with stable latency',
    },
    'awx': {
        'label': 'Ansible AWX',
        'concept': 'projects, inventories, job templates, and RBAC',
        'inspect': 'AWX UI job output, instance groups, and credentials',
        'symptom': 'scheduled jobs fail silently or target wrong inventory',
        'verify': 'job templates run idempotently with scoped credentials',
    },
    'backup': {
        'label': 'Backup',
        'concept': 'core concepts and daily workflows for backup',
        'inspect': 'status commands, logs, and configuration related to backup',
        'symptom': 'Backup misconfiguration causes user-visible failures or operational risk',
        'verify': 'Backup meets expected health checks after your changes',
    },
    'bios': {
        'label': 'server BIOS',
        'concept': 'boot order, virtualization, power profiles, and security features',
        'inspect': 'out-of-band console, BIOS screens, and firmware inventory',
        'symptom': 'servers boot from wrong media or VT-d/SR-IOV disabled',
        'verify': 'firmware settings match hardware profile and boot reliably',
    },
    'bonding': {
        'label': 'NIC bonding',
        'concept': 'LACP modes, failover, and hash policies',
        'inspect': '`ip link`, `/proc/net/bonding/*`, and switch port config',
        'symptom': 'link failover drops active connections or asymmetry breaks TCP',
        'verify': 'bond fails over cleanly and throughput matches design',
    },
    'boot-recovery': {
        'label': 'Linux boot recovery',
        'concept': 'initramfs, GRUB, fstab, and emergency mode',
        'inspect': '`journalctl -b`, `lsblk`, and dracut logs',
        'symptom': 'system drops to emergency shell after kernel upgrade',
        'verify': 'host boots to multi-user target with correct mounts',
    },
    'bundling': {
        'label': 'JS bundling',
        'concept': 'tree shaking, code splitting, and source maps',
        'inspect': 'bundle analyzer, webpack/vite stats, and network panel',
        'symptom': 'production bundle is huge or dev/prod behavior diverges',
        'verify': 'bundles load quickly with correct hashed assets',
    },
    'capture': {
        'label': 'packet capture',
        'concept': 'snaplen, buffers, filters, and file rotation',
        'inspect': 'tcpdump/Wireshark capture settings and disk usage',
        'symptom': 'captures truncate packets or drop during bursts',
        'verify': 'pcap contains complete conversations for the incident window',
    },
    'cd-release': {
        'label': 'continuous delivery',
        'concept': 'promotion gates, canaries, and release artifacts',
        'inspect': 'pipeline stages, deployment logs, and feature flags',
        'symptom': 'bad builds reach production without automated rollback',
        'verify': 'releases promote through gates with observable health checks',
    },
    'change-management': {
        'label': 'change management',
        'concept': 'CAB records, risk classification, and backout plans',
        'inspect': 'change tickets, maintenance windows, and comms templates',
        'symptom': 'emergency fixes skip documentation and repeat outages',
        'verify': 'each change has owner, rollback, and verification steps',
    },
    'charset': {
        'label': 'MySQL charset/collation',
        'concept': 'utf8mb4, connection vs table charset, and conversions',
        'inspect': "`SHOW VARIABLES LIKE 'char%'` and column definitions",
        'symptom': 'emoji or i18n data corrupts on insert',
        'verify': 'client and tables agree on utf8mb4 end-to-end',
    },
    'chrony': {
        'label': 'time sync with chrony',
        'concept': 'NTP sources, leap seconds, and stratum',
        'inspect': '`chronyc sources`, `tracking`, and `/etc/chrony.conf`',
        'symptom': 'logs show skewed timestamps and TLS/auth fails',
        'verify': 'clock offset stays within org NTP policy',
    },
    'ci-pipeline': {
        'label': 'CI pipelines',
        'concept': 'stages, caching, secrets, and flaky test control',
        'inspect': 'pipeline YAML, job logs, and artifact outputs',
        'symptom': 'main is red for environmental reasons, not code',
        'verify': 'pipelines finish fast with deterministic test results',
    },
    'cleaning': {
        'label': 'data cleaning',
        'concept': 'nulls, dtypes, outliers, and reproducible transforms',
        'inspect': 'profiling reports, pandas info(), and sample rows',
        'symptom': 'models train on dirty labels and metrics lie',
        'verify': 'cleaned dataset documents transforms and passes validation rules',
    },
    'cli': {
        'label': 'Python CLIs',
        'concept': 'argparse/typer, exit codes, and stdin/stdout contracts',
        'inspect': '`--help`, exit codes, and golden CLI tests',
        'symptom': 'operators cannot script the tool due to ambiguous flags',
        'verify': 'CLI returns documented codes and supports automation',
    },
    'component-security': {
        'label': 'PeopleSoft component security',
        'concept': 'menu/component permissions and row-level security',
        'inspect': 'Security by Permission List and component properties',
        'symptom': 'users open components they should not see',
        'verify': 'effective permissions match role design for test users',
    },
    'components': {
        'label': 'Components',
        'concept': 'core concepts and daily workflows for components',
        'inspect': 'status commands, logs, and configuration related to components',
        'symptom': 'Components misconfiguration causes user-visible failures or operational risk',
        'verify': 'Components meets expected health checks after your changes',
    },
    'compose': {
        'label': 'Compose',
        'concept': 'core concepts and daily workflows for compose',
        'inspect': 'status commands, logs, and configuration related to compose',
        'symptom': 'Compose misconfiguration causes user-visible failures or operational risk',
        'verify': 'Compose meets expected health checks after your changes',
    },
    'conditionals': {
        'label': 'Ansible conditionals',
        'concept': 'when, failed_when, changed_when, and Jinja tests',
        'inspect': 'ansible-playbook -vvv task skips and facts',
        'symptom': 'tasks run on wrong hosts or ignore soft failures',
        'verify': 'conditionals make plays idempotent and host-accurate',
    },
    'configmaps': {
        'label': 'Configmaps',
        'concept': 'core concepts and daily workflows for configmaps',
        'inspect': 'status commands, logs, and configuration related to configmaps',
        'symptom': 'Configmaps misconfiguration causes user-visible failures or operational risk',
        'verify': 'Configmaps meets expected health checks after your changes',
    },
    'console': {
        'label': 'serial/IPMI console',
        'concept': 'SOL, baud, login prompts, and firmware access',
        'inspect': 'ipmitool sol, physical/KVM console, and boot messages',
        'symptom': 'operators cannot reach host during network outage',
        'verify': 'console provides reliable out-of-band recovery path',
    },
    'constraints': {
        'label': 'SQLite constraints',
        'concept': 'PRIMARY KEY, UNIQUE, FOREIGN KEY, and CHECK',
        'inspect': '`.schema`, `PRAGMA foreign_keys`, and insert tests',
        'symptom': 'orphan rows or duplicates slip into production DB',
        'verify': 'constraints enforce referential integrity on write',
    },
    'contact-points': {
        'label': 'Grafana contact points',
        'concept': 'receivers, templates, and on-call integrations',
        'inspect': 'Grafana alerting UI and test notification button',
        'symptom': 'alerts fire in UI but never reach Slack/PagerDuty',
        'verify': 'test alert delivers to the right channel with context',
    },
    'container-toolkit': {
        'label': 'NVIDIA container toolkit',
        'concept': 'runtime hooks, device requests, and CDI',
        'inspect': '`nvidia-ctk`, docker/k8s GPU requests, and logs',
        'symptom': 'containers start but CUDA cannot see GPUs',
        'verify': 'GPU workloads run with correct driver/runtime pairing',
    },
    'context': {
        'label': 'React Context',
        'concept': 'providers, consumers, and avoiding unnecessary rerenders',
        'inspect': 'React DevTools context panel and render profiler',
        'symptom': 'global state updates repaint the entire tree',
        'verify': 'context delivers state to subtrees without prop drilling pain',
    },
    'cron': {
        'label': 'cron scheduling',
        'concept': 'crontab fields, timezones, and environment',
        'inspect': '`crontab -l`, `/var/log/cron`, and mail spool',
        'symptom': 'jobs never run or run with wrong PATH/user',
        'verify': 'scheduled job executes at expected times with logs',
    },
    'cron-timers': {
        'label': 'systemd timers',
        'concept': 'OnCalendar, monotonic timers, and Persistent',
        'inspect': '`systemctl list-timers`, unit files, and journals',
        'symptom': 'maintenance windows are missed after downtime',
        'verify': 'timers catch up correctly and log each run',
    },
    'cross-tech': {
        'label': 'cross-technology integration',
        'concept': 'handoffs between platforms, contracts, and failure domains',
        'inspect': 'logs/traces on both sides of the integration boundary',
        'symptom': 'each team blames the other and nothing end-to-end works',
        'verify': 'integrated workflow succeeds with correlated IDs across systems',
    },
    'csp': {
        'label': 'Content Security Policy',
        'concept': 'directives, nonces, and report-only mode',
        'inspect': 'browser console CSP errors and response headers',
        'symptom': 'inline scripts break after tightening headers',
        'verify': 'CSP blocks XSS vectors without breaking legit assets',
    },
    'cuda': {
        'label': 'CUDA workloads',
        'concept': 'kernels, streams, device memory, and occupancy',
        'inspect': '`nvcc`, `nvprof/nsys`, and application logs',
        'symptom': 'GPU jobs fail with illegal memory access or low SM util',
        'verify': 'kernels launch on the selected device with stable results',
    },
    'dashboards': {
        'label': 'Dashboards',
        'concept': 'core concepts and daily workflows for dashboards',
        'inspect': 'status commands, logs, and configuration related to dashboards',
        'symptom': 'Dashboards misconfiguration causes user-visible failures or operational risk',
        'verify': 'Dashboards meets expected health checks after your changes',
    },
    'data-processing': {
        'label': 'Python data processing',
        'concept': 'chunking, iterators, memory bounds, and parquet/csv IO',
        'inspect': 'memory_profiler, row counts, and schema checks',
        'symptom': 'pipelines OOM on large files or skew partitions',
        'verify': 'processing finishes within memory budget with correct counts',
    },
    'data-sources': {
        'label': 'Terraform data sources',
        'concept': 'read-only queries, dependencies, and refresh behavior',
        'inspect': '`terraform plan` data reads and provider docs',
        'symptom': 'plans fail because data sources return empty sets',
        'verify': 'data sources populate resources with live values',
    },
    'database': {
        'label': 'database platforms',
        'concept': 'engines, connections, backups, and operational baselines',
        'inspect': 'server status views, connection pools, and error logs',
        'symptom': 'apps see intermittent DB errors under load',
        'verify': 'database serves consistent queries within SLO latency',
    },
    'dataset': {
        'label': 'Dataset',
        'concept': 'core concepts and daily workflows for dataset',
        'inspect': 'status commands, logs, and configuration related to dataset',
        'symptom': 'Dataset misconfiguration causes user-visible failures or operational risk',
        'verify': 'Dataset meets expected health checks after your changes',
    },
    'datasources': {
        'label': 'Grafana datasources',
        'concept': 'proxy vs direct, auth, and TLS to backends',
        'inspect': 'Grafana datasource test and query inspector',
        'symptom': 'dashboards break after credential rotation',
        'verify': 'datasources authenticate and return series in Explore',
    },
    'datastore': {
        'label': 'VMware datastores',
        'concept': 'VMFS/NFS, capacity, and VM placement',
        'inspect': 'vSphere datastore summary, alarms, and vmknic paths',
        'symptom': 'VM provisioning fails with insufficient space or latency',
        'verify': 'datastores have headroom and correct multipathing',
    },
    'datetime': {
        'label': 'datetime handling',
        'concept': 'time zones, parsing, and daylight-saving edges',
        'inspect': 'unit tests around DST boundaries and ISO formats',
        'symptom': 'reports shift dates or sort chronologically wrong',
        'verify': 'timestamps normalize to UTC with explicit tz metadata',
    },
    'dcgm': {
        'label': 'NVIDIA DCGM',
        'concept': 'GPU telemetry, health watches, and field groups',
        'inspect': '`dcgmi discovery`, policy violations, and exporter metrics',
        'symptom': 'GPU faults go unnoticed until workloads fail',
        'verify': 'DCGM exports health metrics and triggers on XID errors',
    },
    'debugging': {
        'label': 'prompt debugging',
        'concept': 'trace prompts, compare variants, and regression sets',
        'inspect': 'prompt logs, eval dashboards, and diff tools',
        'symptom': 'small prompt edits cause large quality regressions',
        'verify': 'debug workflow isolates which prompt segment changed behavior',
    },
    'deployment': {
        'label': 'application deployment',
        'concept': 'rollouts, health checks, and config separation',
        'inspect': 'deploy logs, `/health`, and load balancer targets',
        'symptom': 'new version serves 500s while old still healthy',
        'verify': 'deployment completes with passing smoke tests',
    },
    'deployments': {
        'label': 'Deployments',
        'concept': 'core concepts and daily workflows for deployments',
        'inspect': 'status commands, logs, and configuration related to deployments',
        'symptom': 'Deployments misconfiguration causes user-visible failures or operational risk',
        'verify': 'Deployments meets expected health checks after your changes',
    },
    'dhcp': {
        'label': 'DHCP',
        'concept': 'scopes, reservations, leases, and options',
        'inspect': 'dhcp server logs, `dhclient`, and lease databases',
        'symptom': 'clients get wrong gateway/DNS or exhaust leases',
        'verify': 'leases renew correctly with intended options',
    },
    'dnf-modules': {
        'label': 'RHEL DNF modules',
        'concept': 'module streams, profiles, and switching',
        'inspect': '`dnf module list`, `module info`, and repo config',
        'symptom': 'wrong Python/DB stream breaks dependencies',
        'verify': 'enabled module stream matches app requirements',
    },
    'dns': {
        'label': 'Dns',
        'concept': 'core concepts and daily workflows for dns',
        'inspect': 'status commands, logs, and configuration related to dns',
        'symptom': 'Dns misconfiguration causes user-visible failures or operational risk',
        'verify': 'Dns meets expected health checks after your changes',
    },
    'dns-dhcp': {
        'label': 'Windows DNS and DHCP',
        'concept': 'zones, A/PTR records, scopes, reservations, and lease options',
        'inspect': 'DNS Manager, `Get-DhcpServerv4Scope`, and ipconfig /all on clients',
        'symptom': 'clients get no IP, wrong gateway/DNS, or stale records break name resolution',
        'verify': 'clients receive correct leases and DNS resolves forward and reverse',
    },
    'dockerfile': {
        'label': 'Dockerfile',
        'concept': 'core concepts and daily workflows for dockerfile',
        'inspect': 'status commands, logs, and configuration related to dockerfile',
        'symptom': 'Dockerfile misconfiguration causes user-visible failures or operational risk',
        'verify': 'Dockerfile meets expected health checks after your changes',
    },
    'dom': {
        'label': 'the DOM',
        'concept': 'nodes, events, delegation, and reflow costs',
        'inspect': 'Elements panel, event listeners, and Performance tab',
        'symptom': 'UI handlers double-fire or miss dynamic elements',
        'verify': 'DOM updates reflect user actions without memory leaks',
    },
    'drift': {
        'label': 'infrastructure drift',
        'concept': 'config vs actual, scheduled detection, and remediation',
        'inspect': '`terraform plan`, driftctl, or config audit reports',
        'symptom': 'console hotfixes never make it back to IaC',
        'verify': 'drift is detected and reconciled through code',
    },
    'drivers': {
        'label': 'Drivers',
        'concept': 'core concepts and daily workflows for drivers',
        'inspect': 'status commands, logs, and configuration related to drivers',
        'symptom': 'Drivers misconfiguration causes user-visible failures or operational risk',
        'verify': 'Drivers meets expected health checks after your changes',
    },
    'dv-switch': {
        'label': 'distributed virtual switch',
        'concept': 'port groups, uplinks, and private VLANs',
        'inspect': 'vSphere networking view and vmkernel adapters',
        'symptom': 'VM traffic lands on wrong VLAN or suffers packet loss',
        'verify': 'dvSwitch port groups match VLAN and teaming design',
    },
    'effects': {
        'label': 'React effects',
        'concept': 'dependency arrays, cleanup, and stale closures',
        'inspect': 'eslint exhaustive-deps and React DevTools',
        'symptom': 'effects loop infinitely or miss updates',
        'verify': 'effects run once per meaningful dependency change',
    },
    'env-config': {
        'label': 'environment configuration',
        'concept': '12-factor env vars, secrets, and per-env files',
        'inspect': '`.env*`, process env, and config schema validation',
        'symptom': 'prod points at staging URLs after deploy',
        'verify': 'each environment loads validated config at startup',
    },
    'error-boundaries': {
        'label': 'React error boundaries',
        'concept': 'fallback UI, logging, and isolating subtree crashes',
        'inspect': 'console errors and boundary componentDidCatch logs',
        'symptom': 'one widget crash whitescreens the entire app',
        'verify': 'boundary shows recoverable fallback and reports error',
    },
    'evaluation': {
        'label': 'prompt evaluation',
        'concept': 'golden sets, rubrics, and regression thresholds',
        'inspect': 'eval harness output, score distributions, and diffs',
        'symptom': 'prompt changes ship without measurable QA',
        'verify': 'eval suite gates releases with documented metrics',
    },
    'event-viewer': {
        'label': 'Windows Event Viewer',
        'concept': 'channels, filters, XPath queries, and forwarding',
        'inspect': 'Event Viewer custom views and `Get-WinEvent`',
        'symptom': 'critical errors are buried in noise',
        'verify': 'filtered views surface auth, disk, and service failures',
    },
    'examples': {
        'label': 'few-shot examples',
        'concept': 'example ordering, diversity, and label leakage',
        'inspect': 'prompt transcripts and held-out eval cases',
        'symptom': 'model copies examples instead of generalizing',
        'verify': 'examples improve accuracy without overfitting phrasing',
    },
    'exceptions': {
        'label': 'Python exceptions',
        'concept': 'try/except granularity, chaining, and custom types',
        'inspect': 'tracebacks, `logging.exception`, and pytest failures',
        'symptom': 'bare excepts hide root cause or swallow KeyboardInterrupt',
        'verify': 'exceptions carry context and bubble when unhandled',
    },
    'export': {
        'label': 'trace/capture export',
        'concept': 'pcapng, CSV, and sanitized shares',
        'inspect': 'Wireshark export dialogs and file sizes',
        'symptom': 'exports too large to share or strip required headers',
        'verify': 'export contains just the incident slice with metadata',
    },
    'exporters': {
        'label': 'Prometheus exporters',
        'concept': 'metric names, labels, and scrape auth',
        'inspect': 'exporter `/metrics` and `curl` from Prometheus pod',
        'symptom': 'cardinality explosion or missing key series',
        'verify': 'exporter exposes documented metrics with sane labels',
    },
    'exports': {
        'label': 'data exports',
        'concept': 'CSV/Parquet exports, PII redaction, and schedules',
        'inspect': 'export job logs, row counts, and checksums',
        'symptom': 'downstream teams receive partial or stale extracts',
        'verify': 'exports match query definition and land on schedule',
    },
    'express': {
        'label': 'Express',
        'concept': 'core concepts and daily workflows for express',
        'inspect': 'status commands, logs, and configuration related to express',
        'symptom': 'Express misconfiguration causes user-visible failures or operational risk',
        'verify': 'Express meets expected health checks after your changes',
    },
    'extensions': {
        'label': 'PostgreSQL extensions',
        'concept': 'CREATE EXTENSION, version pinning, and shared_preload_libraries',
        'inspect': '`\\dx`, `pg_available_extensions`, and postgresql.conf',
        'symptom': 'queries fail because an extension is missing, outdated, or not preloaded',
        'verify': 'required extensions are installed at the expected version and loaded',
    },
    'facts': {
        'label': 'Ansible facts',
        'concept': 'setup module, custom facts, and caching',
        'inspect': '`ansible -m setup`, fact paths, and `hostvars`',
        'symptom': 'plays branch on stale or missing facts',
        'verify': 'facts refresh when needed and drive correct conditionals',
    },
    'features': {
        'label': 'ML feature engineering',
        'concept': 'encoding, scaling, leakage, and feature stores',
        'inspect': 'feature stats, correlation matrix, and pipelines',
        'symptom': 'production features differ from training schema',
        'verify': 'feature pipeline version matches served model contract',
    },
    'fetch': {
        'label': 'fetch API',
        'concept': 'HTTP methods, credentials, CORS, and error handling',
        'inspect': 'Network tab, response.status, and CORS console errors',
        'symptom': 'silent failures on 4xx/5xx or CORS blocks preflight',
        'verify': 'fetch handles non-OK responses and parses JSON safely',
    },
    'file-shares': {
        'label': 'Windows file shares',
        'concept': 'SMB permissions, DFS, and offline caching',
        'inspect': '`Get-SmbShare`, ACLs, and connectivity tests',
        'symptom': 'users cannot map drives or see permission denied on files',
        'verify': 'share ACLs and NTFS permissions align for intended access',
    },
    'files': {
        'label': 'Python file IO',
        'concept': 'paths, context managers, encoding, and atomic writes',
        'inspect': '`pathlib`, temp files, and permission bits',
        'symptom': 'Windows vs Linux path bugs corrupt outputs',
        'verify': 'file reads/writes are encoding-safe and atomic where needed',
    },
    'filters': {
        'label': 'Filters',
        'concept': 'core concepts and daily workflows for filters',
        'inspect': 'status commands, logs, and configuration related to filters',
        'symptom': 'Filters misconfiguration causes user-visible failures or operational risk',
        'verify': 'Filters meets expected health checks after your changes',
    },
    'firewall': {
        'label': 'Firewall',
        'concept': 'core concepts and daily workflows for firewall',
        'inspect': 'status commands, logs, and configuration related to firewall',
        'symptom': 'Firewall misconfiguration causes user-visible failures or operational risk',
        'verify': 'Firewall meets expected health checks after your changes',
    },
    'firewalld': {
        'label': 'firewalld on RHEL',
        'concept': 'zones, rich rules, and permanent vs runtime',
        'inspect': '`firewall-cmd --list-all`, `--reload`, and logs',
        'symptom': 'RHEL services unreachable after enabling firewalld',
        'verify': 'permanent rules allow required services only',
    },
    'firmware': {
        'label': 'server firmware',
        'concept': 'BIOS/BMC versions, CVEs, and upgrade paths',
        'inspect': 'vendor inventory tools and firmware catalogs',
        'symptom': 'known CVEs remain on critical hosts',
        'verify': 'firmware meets baseline and upgrades are logged',
    },
    'forms': {
        'label': 'HTML/React forms',
        'concept': 'controlled inputs, validation, and submit states',
        'inspect': 'form state, a11y labels, and network on submit',
        'symptom': 'double submits or validation only on server',
        'verify': 'forms validate client-side and show accessible errors',
    },
    'functions': {
        'label': 'shell functions',
        'concept': 'local scope, return codes, and reusability',
        'inspect': '`declare -f`, `set -e` behavior, and shellcheck',
        'symptom': 'functions leak globals or mask failures',
        'verify': 'functions encapsulate logic with documented exit codes',
    },
    'git-flow': {
        'label': 'Git branching',
        'concept': 'trunk vs GitFlow, PR checks, and release tags',
        'inspect': '`git log`, branch protections, and CI status',
        'symptom': 'hotfixes merge to wrong branch or lose commits',
        'verify': 'branch strategy matches team release cadence',
    },
    'gpo': {
        'label': 'Group Policy',
        'concept': 'GPO scope, inheritance, and rsop',
        'inspect': 'GPMC, `gpresult`, and SYSVOL replication',
        'symptom': 'settings never apply or apply to wrong OU',
        'verify': 'rsop shows intended policy on test machines',
    },
    'gradle': {
        'label': 'Gradle builds',
        'concept': 'tasks, dependencies, wrappers, and build scans',
        'inspect': '`./gradlew tasks`, dependency insight, and reports',
        'symptom': 'builds are non-reproducible across laptops',
        'verify': '`gradlew build` succeeds with locked dependency versions',
    },
    'grants': {
        'label': 'database grants',
        'concept': 'least privilege, role inheritance, and object-level perms',
        'inspect': '`SHOW GRANTS`, `pg_roles`, and privilege catalogs',
        'symptom': 'apps connect as superuser or lack needed SELECT',
        'verify': 'roles grant minimal rights required for the workload',
    },
    'groupby': {
        'label': 'groupby aggregations',
        'concept': 'keys, agg funcs, null groups, and performance',
        'inspect': 'pandas `groupby` sizes, `reset_index`, and explain',
        'symptom': 'aggregations drop groups or double-count rows',
        'verify': 'groupby results match manual spot checks',
    },
    'gui': {
        'label': 'simulation GUI',
        'concept': 'stateful UI panels, validation, and learner guidance',
        'inspect': 'GUI component tree and event logs in sim',
        'symptom': 'learners cannot tell which UI action is required',
        'verify': 'GUI reflects lab state and responds to correct actions',
    },
    'ha-drs': {
        'label': 'vSphere HA/DRS',
        'concept': 'admission control, affinity, and resource pools',
        'inspect': 'cluster summary, DRS recommendations, and alarms',
        'symptom': 'host failure does not restart VMs or DRS thrashes',
        'verify': 'cluster maintains SLA with balanced utilization',
    },
    'handlers': {
        'label': 'Ansible handlers',
        'concept': 'notify, listen, and flush_handlers',
        'inspect': 'play recap handler section and `--diff`',
        'symptom': 'service restarts never trigger after config change',
        'verify': 'handlers run once at end of play when notified',
    },
    'healthchecks': {
        'label': 'container healthchecks',
        'concept': 'HEALTHCHECK CMD, start periods, and restart policy',
        'inspect': '`docker inspect` Health section and compose healthcheck',
        'symptom': 'unhealthy containers keep receiving traffic',
        'verify': 'healthcheck reflects app readiness, not just port open',
    },
    'hints': {
        'label': 'lab hints',
        'concept': 'progressive disclosure, costs, and anti-spoilers',
        'inspect': 'hint usage analytics and learner feedback',
        'symptom': 'hints give away answers or are too vague to help',
        'verify': 'hints escalate from orientation to verification constructively',
    },
    'http': {
        'label': 'HTTP protocol analysis',
        'concept': 'methods, status codes, headers, and keep-alive',
        'inspect': 'curl -v, proxy logs, and Wireshark HTTP decode',
        'symptom': 'intermittent 502/504 with unclear upstream cause',
        'verify': 'HTTP conversation shows where latency or errors originate',
    },
    'http-api': {
        'label': 'Python HTTP APIs',
        'concept': 'requests/httpx, timeouts, retries, and schemas',
        'inspect': 'HTTP traces, status codes, and pydantic validation',
        'symptom': 'clients hang without timeouts or retry idempotency wrong',
        'verify': 'API client handles errors and validates payloads',
    },
    'iam': {
        'label': 'identity and access',
        'concept': 'users, roles, policies, and federation',
        'inspect': 'IAM console/CLI, policy simulator, and CloudTrail',
        'symptom': 'overprivileged keys or missing break-glass access',
        'verify': 'policies enforce least privilege with auditable changes',
    },
    'iis': {
        'label': 'IIS web server',
        'concept': 'sites, app pools, bindings, and modules',
        'inspect': 'IIS Manager, `appcmd`, and Windows event logs',
        'symptom': 'sites return 503 or wrong cert on HTTPS binding',
        'verify': 'app pool identity and bindings serve the correct app',
    },
    'images-layers': {
        'label': 'Images Layers',
        'concept': 'core concepts and daily workflows for images layers',
        'inspect': 'status commands, logs, and configuration related to images layers',
        'symptom': 'Images Layers misconfiguration causes user-visible failures or operational risk',
        'verify': 'Images Layers meets expected health checks after your changes',
    },
    'import': {
        'label': 'Terraform import',
        'concept': 'addressing, state adoption, and drift reconciliation',
        'inspect': '`terraform import`, generated config, and plan',
        'symptom': 'resources recreated because never imported to state',
        'verify': 'imported resources match live IDs with clean plan',
    },
    'incident-response': {
        'label': 'incident response',
        'concept': 'severity, comms, timelines, and postmortems',
        'inspect': 'incident channel, status page, and action log',
        'symptom': 'teams fix symptoms without customer updates',
        'verify': 'incident has owner, ETA, mitigation, and follow-up items',
    },
    'indexes': {
        'label': 'Indexes',
        'concept': 'core concepts and daily workflows for indexes',
        'inspect': 'status commands, logs, and configuration related to indexes',
        'symptom': 'Indexes misconfiguration causes user-visible failures or operational risk',
        'verify': 'Indexes meets expected health checks after your changes',
    },
    'inference': {
        'label': 'model inference',
        'concept': 'batching, latency, GPU/CPU paths, and versioning',
        'inspect': 'serving logs, p99 latency, and model registry tags',
        'symptom': 'serving skew vs training features causes bad predictions',
        'verify': 'inference meets latency SLO with correct model version',
    },
    'ingress': {
        'label': 'Ingress',
        'concept': 'core concepts and daily workflows for ingress',
        'inspect': 'status commands, logs, and configuration related to ingress',
        'symptom': 'Ingress misconfiguration causes user-visible failures or operational risk',
        'verify': 'Ingress meets expected health checks after your changes',
    },
    'innodb': {
        'label': 'InnoDB engine',
        'concept': 'buffer pool, redo log, transactions, and locks',
        'inspect': '`SHOW ENGINE INNODB STATUS`, `information_schema`',
        'symptom': 'write stalls during checkpoint or deadlocks spike',
        'verify': 'InnoDB metrics healthy and transactions commit reliably',
    },
    'instructions': {
        'label': 'system instructions',
        'concept': 'role prompts, constraints, and tone control',
        'inspect': 'prompt versions, eval scores, and refusal logs',
        'symptom': 'model ignores safety or style constraints',
        'verify': 'instructions produce consistent behavior on eval set',
    },
    'integration-broker': {
        'label': 'PeopleSoft Integration Broker',
        'concept': 'services, routing, handlers, and errors',
        'inspect': 'IB monitoring, service logs, and message definitions',
        'symptom': 'integrations fail with opaque IB errors',
        'verify': 'messages route, transform, and post with traceable IDs',
    },
    'integrity': {
        'label': 'SQLite integrity',
        'concept': 'PRAGMA integrity_check and foreign keys',
        'inspect': '`PRAGMA integrity_check`, `quick_check`',
        'symptom': 'app sees corruption after unclean shutdown',
        'verify': 'integrity checks pass and FK mode enforced',
    },
    'inventory': {
        'label': 'Inventory',
        'concept': 'core concepts and daily workflows for inventory',
        'inspect': 'status commands, logs, and configuration related to inventory',
        'symptom': 'Inventory misconfiguration causes user-visible failures or operational risk',
        'verify': 'Inventory meets expected health checks after your changes',
    },
    'ipmi': {
        'label': 'IPMI / BMC management',
        'concept': 'out-of-band power, sensors, SOL console, and user accounts',
        'inspect': '`ipmitool sensor`, `ipmitool sol activate`, and BMC web UI',
        'symptom': 'host is unreachable over network and cannot be power-cycled or inspected',
        'verify': 'BMC reports healthy sensors and provides reliable remote power/console',
    },
    'jdbc': {
        'label': 'Java JDBC',
        'concept': 'connections, pools, transactions, and SQL injection safety',
        'inspect': 'Hikari metrics, SQLException traces, and query logs',
        'symptom': 'connection leaks exhaust pool or wrong isolation level',
        'verify': 'JDBC pool stable under load with parameterized SQL',
    },
    'joins': {
        'label': 'SQL joins',
        'concept': 'inner/left joins, keys, and cardinality explosions',
        'inspect': 'EXPLAIN plans, row counts, and null handling',
        'symptom': 'fan-out duplicates revenue or drops rows silently',
        'verify': 'join results match keyed expectations on samples',
    },
    'journald-logs': {
        'label': 'Journald Logs',
        'concept': 'core concepts and daily workflows for journald logs',
        'inspect': 'status commands, logs, and configuration related to journald logs',
        'symptom': 'Journald Logs misconfiguration causes user-visible failures or operational risk',
        'verify': 'Journald Logs meets expected health checks after your changes',
    },
    'junit': {
        'label': 'JUnit testing',
        'concept': 'fixtures, assertions, parameterized tests, and CI',
        'inspect': 'surefire reports, `@Test` lifecycle, and failures',
        'symptom': 'flaky tests erode trust in CI',
        'verify': 'suite runs deterministically with meaningful assertions',
    },
    'jvm-memory': {
        'label': 'JVM memory',
        'concept': 'heap, GC logs, metaspace, and OOM dumps',
        'inspect': 'jcmd, GC logs, and heap histogram',
        'symptom': 'services OOM or pause too long under load',
        'verify': 'heap sizing and GC keep pauses within SLO',
    },
    'kdump': {
        'label': 'kernel crash dumps',
        'concept': 'crashkernel reservation, vmcore, and analysis',
        'inspect': '`kdumpctl status`, `/var/crash`, and `crash`',
        'symptom': 'host panics leave no vmcore for engineering',
        'verify': 'kdump captures cores and survives reboot workflow',
    },
    'labels': {
        'label': 'Prometheus labels',
        'concept': 'cardinality, naming, and relabeling',
        'inspect': '`promtool check metrics`, TSDB stats, and scrape configs',
        'symptom': 'high-cardinality label crashes Prometheus',
        'verify': 'labels follow naming rules and stay bounded',
    },
    'latency': {
        'label': 'network latency',
        'concept': 'RTT, jitter, buffering, and slow paths',
        'inspect': 'ping, mtr, IO graphs, and service traces',
        'symptom': 'users see sluggish apps but CPU is idle',
        'verify': 'latency budget traced to segment responsible',
    },
    'least-privilege': {
        'label': 'least privilege',
        'concept': 'role minimization, JIT access, and periodic review',
        'inspect': 'access reviews, policy simulators, and sudo logs',
        'symptom': 'shared admin accounts hide accountability',
        'verify': 'each principal has minimum rights still allowing work',
    },
    'load-balancing': {
        'label': 'load balancing',
        'concept': 'L4/L7 algorithms, health checks, and stickiness',
        'inspect': 'LB config, backend pool status, and access logs',
        'symptom': 'traffic sticks to unhealthy backends',
        'verify': 'LB distributes only to healthy targets with even load',
    },
    'locks': {
        'label': 'database locks',
        'concept': 'row/table locks, deadlocks, and isolation levels',
        'inspect': 'pg_locks, innodb lock waits, and slow query log',
        'symptom': 'transactions block each other and timeouts cascade',
        'verify': 'lock waits resolve and deadlocks are rare/retried',
    },
    'logging': {
        'label': 'application logging',
        'concept': 'structured logs, levels, correlation IDs, and rotation',
        'inspect': 'log aggregation queries and sample trace IDs',
        'symptom': 'incidents impossible to debug due to missing fields',
        'verify': 'logs answer who/what/when with traceable request IDs',
    },
    'logs': {
        'label': 'container logs',
        'concept': 'drivers, rotation, and centralized shipping',
        'inspect': '`docker logs`, logging driver config, and agents',
        'symptom': 'logs disappear after restart or fill disk',
        'verify': 'logs stream to central store with retention policy',
    },
    'loki': {
        'label': 'Grafana Loki',
        'concept': 'labels, logql, ingestion limits, and retention',
        'inspect': 'Loki query frontend, ingester metrics, and chunk stores',
        'symptom': 'queries timeout or ingest drops due to label cardinality',
        'verify': 'LogQL finds target lines with bounded label set',
    },
    'loops': {
        'label': 'shell loops',
        'concept': 'for/while, word splitting, and exit codes',
        'inspect': '`set -e` with loops, `break/continue`, and shellcheck',
        'symptom': 'loops process wrong word list or exit early silently',
        'verify': 'loops iterate expected items and propagate failures',
    },
    'maven': {
        'label': 'Maven',
        'concept': 'core concepts and daily workflows for maven',
        'inspect': 'status commands, logs, and configuration related to maven',
        'symptom': 'Maven misconfiguration causes user-visible failures or operational risk',
        'verify': 'Maven meets expected health checks after your changes',
    },
    'media': {
        'label': 'HTML media',
        'concept': 'video/audio tags, formats, and responsive images',
        'inspect': 'Network panel, codec support, and Lighthouse',
        'symptom': 'media fails on mobile or LCP regresses',
        'verify': 'media loads with correct formats and fallbacks',
    },
    'metadata': {
        'label': 'HTML metadata',
        'concept': 'title, meta tags, OpenGraph, and canonical URLs',
        'inspect': 'view-source, social debuggers, and SEO crawlers',
        'symptom': 'shares show wrong preview or duplicate SEO URLs',
        'verify': 'metadata accurate per page with canonical set',
    },
    'metrics': {
        'label': 'ML metrics',
        'concept': 'precision/recall, calibration, and business KPIs',
        'inspect': 'confusion matrix, PR curves, and offline eval',
        'symptom': 'accuracy hides class imbalance problems',
        'verify': 'metrics align with product goal and baseline',
    },
    'middleware': {
        'label': 'Express middleware',
        'concept': 'order, auth, parsing, and error middleware',
        'inspect': 'request logging with middleware stack trace',
        'symptom': 'auth runs after routes or body parser missing',
        'verify': 'middleware order delivers auth, parse, routes, errors',
    },
    'mig': {
        'label': 'NVIDIA MIG',
        'concept': 'GPU partitioning, profiles, and scheduling',
        'inspect': '`nvidia-smi mig -lgi`, kube device plugin logs',
        'symptom': 'workloads cannot see allocated MIG slice',
        'verify': 'MIG instances match requested profile and persist',
    },
    'model-save': {
        'label': 'model serialization',
        'concept': 'pickle/safetensors, versioning, and signatures',
        'inspect': 'artifact registry, hash, and load tests',
        'symptom': 'wrong model version serves in production',
        'verify': 'saved artifact loads with matching feature schema',
    },
    'modules': {
        'label': 'Modules',
        'concept': 'core concepts and daily workflows for modules',
        'inspect': 'status commands, logs, and configuration related to modules',
        'symptom': 'Modules misconfiguration causes user-visible failures or operational risk',
        'verify': 'Modules meets expected health checks after your changes',
    },
    'monitoring': {
        'label': 'database monitoring',
        'concept': 'latency, connections, replication lag, and alarms',
        'inspect': 'performance schema, pg_stat_activity, dashboards',
        'symptom': 'DB issues discovered by users before monitoring',
        'verify': 'dashboards show leading indicators with actionable thresholds',
    },
    'mtu': {
        'label': 'MTU and fragmentation',
        'concept': 'path MTU, MSS clamping, and jumbo frames',
        'inspect': 'ping -M do -s, interface MTU, and tracepath',
        'symptom': 'large packets black-hole causing TLS hangs',
        'verify': 'end-to-end MTU consistent without silent fragmentation',
    },
    'nat': {
        'label': 'NAT',
        'concept': 'SNAT/DNAT, conntrack, and hairpinning',
        'inspect': '`iptables -t nat -S`, connection tracking, and tcpdump',
        'symptom': 'return traffic misses NAT mapping or port exhaustion',
        'verify': 'NAT rules translate traffic correctly under load',
    },
    'networking-firewalld': {
        'label': 'Linux networking + firewalld',
        'concept': 'interfaces, routes, zones, and service ports',
        'inspect': '`nmcli`, `ip route`, and `firewall-cmd`',
        'symptom': 'service reachable locally but not remotely',
        'verify': 'network and firewall config agree on allowed paths',
    },
    'networkpolicy': {
        'label': 'Kubernetes NetworkPolicy',
        'concept': 'pod selectors, namespaces, and default deny',
        'inspect': '`kubectl describe netpol`, connectivity probes',
        'symptom': 'unexpected east-west traffic or blocked DNS',
        'verify': 'only intended pod-to-pod paths are permitted',
    },
    'networks': {
        'label': 'Networks',
        'concept': 'core concepts and daily workflows for networks',
        'inspect': 'status commands, logs, and configuration related to networks',
        'symptom': 'Networks misconfiguration causes user-visible failures or operational risk',
        'verify': 'Networks meets expected health checks after your changes',
    },
    'nic-teaming': {
        'label': 'NIC teaming',
        'concept': 'LACP/static teams, failover, and VLAN tagging',
        'inspect': 'teamd/Windows teaming UI and switch config',
        'symptom': 'failover drops TCP sessions or VLAN wrong',
        'verify': 'teamed NICs fail over with expected connectivity',
    },
    'notebooks': {
        'label': 'data notebooks',
        'concept': 'reproducibility, secrets, and export to jobs',
        'inspect': 'notebook git diff, papermill parameters, and outputs',
        'symptom': 'works in notebook but fails as scheduled job',
        'verify': 'notebook runs top-to-bottom with pinned dependencies',
    },
    'nse': {
        'label': 'Nmap NSE scripts',
        'concept': 'script categories, args, and safe execution',
        'inspect': '`nmap --script-help`, output, and vuln scans',
        'symptom': 'aggressive scripts disrupt production targets',
        'verify': 'NSE output answers security question without harm',
    },
    'nvidia-smi': {
        'label': 'nvidia-smi monitoring',
        'concept': 'utilization, memory, processes, and clocks',
        'inspect': '`nvidia-smi`, dmon, and persistence mode',
        'symptom': 'GPU shows 0% util while jobs queue',
        'verify': 'smi reflects active processes and thermals',
    },
    'objects': {
        'label': 'JavaScript objects',
        'concept': 'keys, prototypes, destructuring, and immutability',
        'inspect': 'console inspection and Object.freeze tests',
        'symptom': 'mutations cause subtle bugs across modules',
        'verify': 'object shapes match contract without accidental mutation',
    },
    'observability': {
        'label': 'DevOps observability',
        'concept': 'logs, metrics, traces, and SLO dashboards',
        'inspect': 'correlated trace IDs across pipeline stages',
        'symptom': 'releases succeed but regressions invisible until users complain',
        'verify': 'deploy observability shows golden signals within minutes',
    },
    'operator-lock': {
        'label': 'PeopleSoft operator lock',
        'concept': 'locked objects, release, and audit',
        'inspect': 'Operator Security and release actions in PIA',
        'symptom': 'batch jobs fail because records locked by stale user',
        'verify': 'locks identified and cleared per policy with audit',
    },
    'os-detect': {
        'label': 'OS fingerprinting',
        'concept': 'nmap -O, confidence, and ethics',
        'inspect': 'nmap OS scan output and permission scope',
        'symptom': 'wrong OS guess leads to incorrect remediation',
        'verify': 'OS detection documented with scan scope approval',
    },
    'output': {
        'label': 'scan output formats',
        'concept': 'grepable XML, JSON, and diffing scans',
        'inspect': 'nmap -oA files and parsing scripts',
        'symptom': 'automation cannot parse scan results reliably',
        'verify': 'output format stable for downstream tooling',
    },
    'package-patching': {
        'label': 'Linux patching',
        'concept': 'repos, kernels, reboot strategy, and compliance',
        'inspect': '`dnf/apt history`, needs-restarting, and CVE trackers',
        'symptom': 'unpatched CVEs or rebootless kernel mismatch',
        'verify': 'patch level meets policy and required reboots scheduled',
    },
    'packaging': {
        'label': 'Python packaging',
        'concept': 'pyproject.toml, wheels, and entry points',
        'inspect': '`pip install -e .`, twine check, and import smoke',
        'symptom': 'package installs but console_scripts missing',
        'verify': 'wheel installs cleanly on target Python version',
    },
    'packet-capture': {
        'label': 'packet capture strategy',
        'concept': 'SPAN/TAP placement, filters, and retention',
        'inspect': 'capture points, disk sizing, and legal approval',
        'symptom': 'captures miss the actual failing path',
        'verify': 'capture plan covers bidirectional flow for incident',
    },
    'panels': {
        'label': 'Grafana panels',
        'concept': 'queries, units, thresholds, and legends',
        'inspect': 'panel editor, query inspector, and repeat rows',
        'symptom': 'panel shows misleading units or dual Y axes',
        'verify': 'panels answer one operational question clearly',
    },
    'partitioning': {
        'label': 'table partitioning',
        'concept': 'range/list/hash, pruning, and maintenance',
        'inspect': 'EXPLAIN partition pruning and partition DDL',
        'symptom': 'queries scan all partitions and slow down',
        'verify': 'queries prune to correct partition with even growth',
    },
    'patching': {
        'label': 'Windows patching',
        'concept': 'WSUS/Intune, rings, and reboot compliance',
        'inspect': 'Windows Update logs and compliance reports',
        'symptom': 'critical KB missing on subset of fleet',
        'verify': 'patch compliance meets SLA with staged rollout',
    },
    'performance': {
        'label': 'web performance',
        'concept': 'LCP, bundle size, caching, and profiling',
        'inspect': 'Lighthouse, Performance tab, and RUM metrics',
        'symptom': 'pages feel slow despite low server CPU',
        'verify': 'core vitals meet budget on target devices',
    },
    'performance-schema': {
        'label': 'MySQL performance_schema',
        'concept': 'waits, statements, and consumers',
        'inspect': 'sys schema views and setup_consumers',
        'symptom': 'cannot pinpoint which query consumes IO',
        'verify': 'performance_schema highlights top wait/query offenders',
    },
    'permission-lists': {
        'label': 'PeopleSoft permission lists',
        'concept': 'menus, components, and sign-on times',
        'inspect': 'Security Administrator and PL compare tool',
        'symptom': 'role shows menu but component access denied',
        'verify': 'permission lists align with designed security matrix',
    },
    'permissions-acl': {
        'label': 'Permissions Acl',
        'concept': 'core concepts and daily workflows for permissions acl',
        'inspect': 'status commands, logs, and configuration related to permissions acl',
        'symptom': 'Permissions Acl misconfiguration causes user-visible failures or operational risk',
        'verify': 'Permissions Acl meets expected health checks after your changes',
    },
    'pg-hba': {
        'label': 'PostgreSQL pg_hba.conf',
        'concept': 'auth methods, CIDR rules, and reload',
        'inspect': '`pg_hba.conf`, `ss` on 5432, and auth logs',
        'symptom': 'apps get password auth failed from valid subnets',
        'verify': 'hba entries allow intended roles from correct networks',
    },
    'pia-navigation': {
        'label': 'Pia Navigation',
        'concept': 'core concepts and daily workflows for pia navigation',
        'inspect': 'status commands, logs, and configuration related to pia navigation',
        'symptom': 'Pia Navigation misconfiguration causes user-visible failures or operational risk',
        'verify': 'Pia Navigation meets expected health checks after your changes',
    },
    'pipelines': {
        'label': 'data/ML pipelines',
        'concept': 'DAG steps, idempotency, and artifact lineage',
        'inspect': 'orchestrator UI, step logs, and data contracts',
        'symptom': 'pipeline succeeds but downstream data wrong',
        'verify': 'pipeline reproduces outputs from pinned inputs',
    },
    'pipes': {
        'label': 'shell pipes',
        'concept': 'stdout/stderr, pipefail, and exit codes',
        'inspect': '`set -o pipefail`, `tee`, and bash -x',
        'symptom': 'pipelines mask failing commands in the middle',
        'verify': 'pipe exit status reflects first failure correctly',
    },
    'playbooks': {
        'label': 'Playbooks',
        'concept': 'core concepts and daily workflows for playbooks',
        'inspect': 'status commands, logs, and configuration related to playbooks',
        'symptom': 'Playbooks misconfiguration causes user-visible failures or operational risk',
        'verify': 'Playbooks meets expected health checks after your changes',
    },
    'pods': {
        'label': 'Pods',
        'concept': 'core concepts and daily workflows for pods',
        'inspect': 'status commands, logs, and configuration related to pods',
        'symptom': 'Pods misconfiguration causes user-visible failures or operational risk',
        'verify': 'Pods meets expected health checks after your changes',
    },
    'policy': {
        'label': 'Terraform policy',
        'concept': 'OPA/Sentinel, plan checks, and guardrails',
        'inspect': 'policy-as-code test suite and denied plans',
        'symptom': 'non-compliant resources reach production',
        'verify': 'policy blocks risky plans with clear denial reasons',
    },
    'pooling': {
        'label': 'connection pooling',
        'concept': 'pool size, timeouts, and prepared statements',
        'inspect': 'pool metrics, wait times, and server conn count',
        'symptom': 'apps exhaust DB connections or see stale sessions',
        'verify': 'pool sizing keeps latency low without saturating DB',
    },
    'power': {
        'label': 'server power',
        'concept': 'PSU redundancy, caps, and IPMI power policy',
        'inspect': 'IPMI power readings and rack PDU logs',
        'symptom': 'unexpected shutdowns during peak or uneven draw',
        'verify': 'power redundancy healthy and within rack budget',
    },
    'powershell': {
        'label': 'PowerShell administration',
        'concept': 'cmdlets, remoting, execution policy, and modules',
        'inspect': '`Get-WinEvent`, `Invoke-Command`, and transcripts',
        'symptom': 'scripts work interactively but fail as scheduled tasks',
        'verify': 'PowerShell automation runs with correct principal and logging',
    },
    'pragma': {
        'label': 'SQLite PRAGMA',
        'concept': 'journal_mode, synchronous, cache_size, and FKs',
        'inspect': '`PRAGMA journal_mode`, `integrity_check`',
        'symptom': 'SQLite corrupts or locks under concurrent writers',
        'verify': 'PRAGMA settings match workload durability needs',
    },
    'process-monitor': {
        'label': 'PeopleSoft Process Monitor',
        'concept': 'runnables, traces, and distribution',
        'inspect': 'Process Monitor, server logs, and SQL trace',
        'symptom': 'stuck processes block downstream payroll',
        'verify': 'processes complete with expected runtime and status',
    },
    'prompting': {
        'label': 'prompt patterns',
        'concept': 'instructions, delimiters, and tool schemas',
        'inspect': 'prompt A/B logs and failure transcripts',
        'symptom': 'model drifts off format or hallucinates tools',
        'verify': 'prompts produce parseable outputs on eval cases',
    },
    'promql': {
        'label': 'Promql',
        'concept': 'core concepts and daily workflows for promql',
        'inspect': 'status commands, logs, and configuration related to promql',
        'symptom': 'Promql misconfiguration causes user-visible failures or operational risk',
        'verify': 'Promql meets expected health checks after your changes',
    },
    'providers': {
        'label': 'Providers',
        'concept': 'core concepts and daily workflows for providers',
        'inspect': 'status commands, logs, and configuration related to providers',
        'symptom': 'Providers misconfiguration causes user-visible failures or operational risk',
        'verify': 'Providers meets expected health checks after your changes',
    },
    'provisioning': {
        'label': 'Grafana provisioning',
        'concept': 'dashboards/datasources as code and reload',
        'inspect': 'provisioning YAML, sidecar logs, and git sync',
        'symptom': 'manual UI changes lost on pod restart',
        'verify': 'Git-managed dashboards provision cleanly on boot',
    },
    'pxe': {
        'label': 'PXE boot',
        'concept': 'DHCP options, TFTP, and kickstart/cloud-init',
        'inspect': 'DHCP leases, tftpd logs, and installer console',
        'symptom': 'hosts loop PXE or boot wrong image',
        'verify': 'PXE delivers correct image and unattended install completes',
    },
    'quality': {
        'label': 'data quality',
        'concept': 'constraints, anomalies, and monitoring',
        'inspect': 'Great Expectations/dbt tests and alerts',
        'symptom': 'dashboards built on untrusted data',
        'verify': 'quality checks block bad data before consumption',
    },
    'query-plan': {
        'label': 'SQL query plans',
        'concept': 'EXPLAIN/ANALYZE, join order, scans vs index access, and statistics',
        'inspect': '`EXPLAIN ANALYZE`, pg_stat_statements, and table statistics',
        'symptom': 'a query that was fast now does sequential scans and times out',
        'verify': 'the plan uses the intended index/join and latency returns to baseline',
    },
    'raid': {
        'label': 'hardware RAID',
        'concept': 'levels, cache, rebuild, and hot spares',
        'inspect': 'controller CLI, SMART, and array status',
        'symptom': 'degraded array unnoticed until second disk fails',
        'verify': 'array optimal with hot spare and monitored rebuild',
    },
    'rbac': {
        'label': 'Rbac',
        'concept': 'core concepts and daily workflows for rbac',
        'inspect': 'status commands, logs, and configuration related to rbac',
        'symptom': 'Rbac misconfiguration causes user-visible failures or operational risk',
        'verify': 'Rbac meets expected health checks after your changes',
    },
    'recording-rules': {
        'label': 'Prometheus recording rules',
        'concept': 'pre-aggregation, naming, and evaluation intervals',
        'inspect': 'rule files, `promtool check rules`, and query compare',
        'symptom': 'dashboards query expensive expressions repeatedly',
        'verify': 'recording rules cut query cost with correct labels',
    },
    'registry': {
        'label': 'container registry',
        'concept': 'tags, immutability, scanning, and auth',
        'inspect': '`docker login`, manifest inspect, and scan reports',
        'symptom': 'prod pulls `latest` and gets unexpected digest',
        'verify': 'images pulled by immutable digest with scan pass',
    },
    'remote-backend': {
        'label': 'Terraform remote state',
        'concept': 'S3/GCS backends, locking, and encryption',
        'inspect': 'backend config, lock table, and state versioning',
        'symptom': 'concurrent applies corrupt state or lock stuck',
        'verify': 'remote state locking prevents concurrent write races',
    },
    'remote-write': {
        'label': 'Prometheus remote write',
        'concept': 'replication, shards, and lag',
        'inspect': 'remote_write queue metrics and receiver health',
        'symptom': 'long-term metrics missing chunks during outage',
        'verify': 'remote_write catches up without cardinality blowup',
    },
    'replication': {
        'label': 'Replication',
        'concept': 'core concepts and daily workflows for replication',
        'inspect': 'status commands, logs, and configuration related to replication',
        'symptom': 'Replication misconfiguration causes user-visible failures or operational risk',
        'verify': 'Replication meets expected health checks after your changes',
    },
    'reports': {
        'label': 'PeopleSoft reports',
        'concept': 'PSQuery, nVision, and distribution',
        'inspect': 'report manager, process output, and schedules',
        'symptom': 'financial reports wrong due to stale prompts',
        'verify': 'reports reconcile to source with scheduled delivery',
    },
    'resource-limits': {
        'label': 'container resource limits',
        'concept': 'CPU/memory requests/limits and OOM behavior',
        'inspect': '`docker stats`, cgroup files, and OOMKilled events',
        'symptom': 'containers starve neighbors or die under normal load',
        'verify': 'limits match workload with headroom for bursts',
    },
    'resource-pools': {
        'label': 'vSphere resource pools',
        'concept': 'shares, reservations, limits, and nesting',
        'inspect': 'cluster resource distribution and pool alarms',
        'symptom': 'noisy neighbor VMs steal capacity from prod pool',
        'verify': 'pools enforce fair scheduling per SLA',
    },
    'responsive': {
        'label': 'responsive design',
        'concept': 'breakpoints, fluid layouts, and touch targets',
        'inspect': 'device mode, CSS grid/flex, and viewport meta',
        'symptom': 'layout breaks on mobile or horizontal scroll appears',
        'verify': 'UI usable across breakpoints without overlap',
    },
    'rest-api': {
        'label': 'Java REST APIs',
        'concept': 'controllers, validation, status codes, and DTOs',
        'inspect': 'OpenAPI, HTTP traces, and integration tests',
        'symptom': 'API returns 500 for validation errors or leaks stack traces',
        'verify': 'REST endpoints follow contract with proper error bodies',
    },
    'restore': {
        'label': 'database restore',
        'concept': 'RPO/RTO, PITR, and verification queries',
        'inspect': 'restore logs, backup catalogs, and checksum queries',
        'symptom': 'restore succeeds but app data inconsistent',
        'verify': 'restored DB passes row counts and app smoke tests',
    },
    'retransmits': {
        'label': 'TCP retransmits',
        'concept': 'loss, congestion, and window sizing',
        'inspect': 'Wireshark TCP graphs, `ss -ti`, and capture',
        'symptom': 'latency spikes with high retransmit rate',
        'verify': 'retransmits explained by identified network segment',
    },
    'roles': {
        'label': 'Roles',
        'concept': 'core concepts and daily workflows for roles',
        'inspect': 'status commands, logs, and configuration related to roles',
        'symptom': 'Roles misconfiguration causes user-visible failures or operational risk',
        'verify': 'Roles meets expected health checks after your changes',
    },
    'rollback': {
        'label': 'deployment rollback',
        'concept': 'artifact pinning, DB migrations, and feature flags',
        'inspect': 'deploy history, helm rollback, and health gates',
        'symptom': 'rollback blocked by irreversible migration',
        'verify': 'rollback returns service to last known good quickly',
    },
    'rolling-deploy': {
        'label': 'rolling Ansible deploys',
        'concept': 'serial, max_fail_percentage, and health checks',
        'inspect': 'play recap, rolling batch logs, and service probes',
        'symptom': 'half-upgraded fleet causes incompatible protocol errors',
        'verify': 'rolling update keeps quorum with automated pause on failure',
    },
    'rootless': {
        'label': 'rootless Docker',
        'concept': 'user namespaces, subuid, and cgroup delegation',
        'inspect': '`docker info`, `/etc/subuid`, and systemd user session',
        'symptom': 'containers cannot bind privileged ports or mount volumes',
        'verify': 'rootless workflow runs with documented constraints',
    },
    'router': {
        'label': 'React Router',
        'concept': 'routes, loaders, nested routes, and 404 handling',
        'inspect': 'router devtools, URL bar, and navigation events',
        'symptom': 'deep links 404 or back button breaks state',
        'verify': 'routes match URLs and preserve expected navigation state',
    },
    'routing': {
        'label': 'Routing',
        'concept': 'core concepts and daily workflows for routing',
        'inspect': 'status commands, logs, and configuration related to routing',
        'symptom': 'Routing misconfiguration causes user-visible failures or operational risk',
        'verify': 'Routing meets expected health checks after your changes',
    },
    'runbooks': {
        'label': 'operational runbooks',
        'concept': 'triggers, steps, escalation, and verification',
        'inspect': 'runbook doc, incident tickets, and command snippets',
        'symptom': 'on-call improvises under pressure and lengthens outage',
        'verify': 'runbook steps reproducible by secondary engineer',
    },
    'safe-delete': {
        'label': 'safe deletion in scripts',
        'concept': 'guards, trash staging, and confirmation flags',
        'inspect': 'dry-run mode, `rm -i`, and audit logs',
        'symptom': 'script deletes production path due to typo',
        'verify': 'destructive ops require explicit flags and backups',
    },
    'safe-scans': {
        'label': 'safe scanning practices',
        'concept': 'scope approval, rate limits, and timing templates',
        'inspect': 'scan authorization ticket and `-T2` policies',
        'symptom': 'scan triggers IDS outage or locks accounts',
        'verify': 'scan completes within approved scope without disruption',
    },
    'safety': {
        'label': 'AI safety guardrails',
        'concept': 'refusals, PII filters, and jailbreak tests',
        'inspect': 'red-team logs, moderation API hits, and eval',
        'symptom': 'model leaks secrets or gives harmful instructions',
        'verify': 'guardrails block policy violations on test suite',
    },
    'scheduler': {
        'label': 'PeopleSoft Scheduler',
        'concept': 'recurrence, priorities, and server lists',
        'inspect': 'Schedule Manager, server status, and job logs',
        'symptom': 'critical jobs queue behind low priority work',
        'verify': 'scheduler dispatches jobs to healthy server with SLA met',
    },
    'scheduling': {
        'label': 'GPU/job scheduling',
        'concept': 'queues, priorities, preemption, and quotas',
        'inspect': 'scheduler logs, queue depth, and utilization',
        'symptom': 'jobs starve or GPUs sit idle due to mismatch',
        'verify': 'scheduler places jobs on eligible nodes fairly',
    },
    'schema': {
        'label': 'SQLite schema',
        'concept': 'DDL, migrations, and normalization',
        'inspect': '`.schema`, migration files, and pragma table_info',
        'symptom': 'schema drift breaks app queries after upgrade',
        'verify': 'schema version matches application expectations',
    },
    'schemas': {
        'label': 'PostgreSQL schemas',
        'concept': 'namespace separation, search_path, and ownership',
        'inspect': 'psql \\dn, \\dt schema.*, and role grants',
        'symptom': 'objects created in wrong schema invisible to app',
        'verify': 'search_path and grants expose correct objects',
    },
    'scoring': {
        'label': 'lab scoring',
        'concept': 'rubrics, partial credit, and anti-cheat',
        'inspect': 'score breakdown, validation logs, and retries',
        'symptom': 'learners game checks without learning objectives',
        'verify': 'scores reflect demonstrated skills with fair partial credit',
    },
    'scrape-config': {
        'label': 'Prometheus scrape config',
        'concept': 'jobs, relabeling, TLS, and honor_labels',
        'inspect': 'prometheus.yml, `promtool check config`, and targets UI',
        'symptom': 'targets down or labels missing after relabel',
        'verify': 'all intended targets UP with consistent labels',
    },
    'secrets': {
        'label': 'Secrets',
        'concept': 'core concepts and daily workflows for secrets',
        'inspect': 'status commands, logs, and configuration related to secrets',
        'symptom': 'Secrets misconfiguration causes user-visible failures or operational risk',
        'verify': 'Secrets meets expected health checks after your changes',
    },
    'security': {
        'label': 'platform security hardening',
        'concept': 'least privilege, patching, secrets handling, and exposure reduction',
        'inspect': 'config audits, open-port scans, IAM/role review, and audit logs',
        'symptom': 'default credentials, open ports, or excessive permissions leave the system exploitable',
        'verify': 'unsafe defaults are removed and access is least-privilege and auditable',
    },
    'selinux': {
        'label': 'Selinux',
        'concept': 'core concepts and daily workflows for selinux',
        'inspect': 'status commands, logs, and configuration related to selinux',
        'symptom': 'Selinux misconfiguration causes user-visible failures or operational risk',
        'verify': 'Selinux meets expected health checks after your changes',
    },
    'selinux-policy': {
        'label': 'SELinux policy',
        'concept': 'booleans, ports, fcontext, and custom modules',
        'inspect': '`audit2allow`, `semanage`, and `restorecon`',
        'symptom': 'app works only with SELinux permissive',
        'verify': 'policy allows required paths/ports while staying enforcing',
    },
    'semantic-html': {
        'label': 'semantic HTML',
        'concept': 'landmarks, headings hierarchy, and native elements',
        'inspect': 'validator, outline view, and screen reader spot check',
        'symptom': 'div soup hurts SEO and accessibility',
        'verify': 'pages use semantic tags reflecting document structure',
    },
    'seo': {
        'label': 'SEO basics',
        'concept': 'crawlability, sitemaps, canonicals, and Core Web Vitals',
        'inspect': 'Search Console, robots.txt, and Lighthouse SEO',
        'symptom': 'pages not indexed or duplicate content dilutes rank',
        'verify': 'SEO checklist passes for template pages',
    },
    'service-detection': {
        'label': 'Nmap service detection',
        'concept': '-sV versions, probes, and false positives',
        'inspect': '`nmap -sV --version-intensity`, output review',
        'symptom': 'wrong service name leads to incorrect patch plan',
        'verify': 'detected services match banner evidence',
    },
    'service-discovery': {
        'label': 'Prometheus service discovery',
        'concept': 'k8s SD, file SD, and label mapping',
        'inspect': 'targets page before/after relabel configs',
        'symptom': 'new pods never appear as scrape targets',
        'verify': 'SD keeps target list current as infra changes',
    },
    'services': {
        'label': 'Services',
        'concept': 'core concepts and daily workflows for services',
        'inspect': 'status commands, logs, and configuration related to services',
        'symptom': 'Services misconfiguration causes user-visible failures or operational risk',
        'verify': 'Services meets expected health checks after your changes',
    },
    'sharing': {
        'label': 'dashboard sharing',
        'concept': 'RBAC, snapshots, and external links',
        'inspect': 'Grafana folder permissions and public dashboard settings',
        'symptom': 'sensitive metrics exposed via public link',
        'verify': 'sharing respects org ACLs and expires appropriately',
    },
    'slow-query': {
        'label': 'Slow Query',
        'concept': 'core concepts and daily workflows for slow query',
        'inspect': 'status commands, logs, and configuration related to slow query',
        'symptom': 'Slow Query misconfiguration causes user-visible failures or operational risk',
        'verify': 'Slow Query meets expected health checks after your changes',
    },
    'smart': {
        'label': 'disk SMART health',
        'concept': 'reallocated sectors, predictive fail, and baselines',
        'inspect': '`smartctl -a`, vendor tools, and RAID events',
        'symptom': 'disk dies without warning despite SMART errors',
        'verify': 'SMART thresholds alert before data unavailability',
    },
    'snapshots': {
        'label': 'VM snapshots',
        'concept': 'quiescing, chains, and consolidation',
        'inspect': 'vSphere snapshot manager and datastore usage',
        'symptom': 'snapshots fill datastore or hurt performance',
        'verify': 'snapshot tree healthy with consolidation schedule',
    },
    'spring-boot': {
        'label': 'Spring Boot',
        'concept': 'auto-config, profiles, actuator, and fat jars',
        'inspect': 'actuator `/health`, application.yml, and startup logs',
        'symptom': 'beans fail to wire or wrong profile activates',
        'verify': 'app starts with healthy actuator and correct profile',
    },
    'ssh-hardening': {
        'label': 'SSH hardening',
        'concept': 'keys, ciphers, AllowUsers, and fail2ban',
        'inspect': '`sshd -T`, auth logs, and `ssh -vvv`',
        'symptom': 'password auth brute-force succeeds or weak ciphers enabled',
        'verify': 'SSH allows only approved auth with modern algorithms',
    },
    'sssd': {
        'label': 'SSSD identity',
        'concept': 'AD/LDAP providers, caches, and offline logon',
        'inspect': '`sssctl user-check`, `/var/log/sssd`, and `getent`',
        'symptom': 'Linux hosts cannot resolve AD users after join',
        'verify': 'SSSD serves identities and sudo rules consistently',
    },
    'state': {
        'label': 'State',
        'concept': 'core concepts and daily workflows for state',
        'inspect': 'status commands, logs, and configuration related to state',
        'symptom': 'State misconfiguration causes user-visible failures or operational risk',
        'verify': 'State meets expected health checks after your changes',
    },
    'statistics': {
        'label': 'statistics fundamentals',
        'concept': 'distributions, hypothesis tests, and sampling bias',
        'inspect': 'summary stats, CI plots, and sample size checks',
        'symptom': 'conclusions drawn from biased samples',
        'verify': 'analysis documents assumptions and confidence bounds',
    },
    'storage': {
        'label': 'database storage',
        'concept': 'tablespaces, files, growth, and autovacuum/optimize',
        'inspect': 'disk usage views, IOPS metrics, and file layout',
        'symptom': 'disk full pauses writes or corrupts cluster',
        'verify': 'storage growth tracked with headroom and maintenance plan',
    },
    'storage-lvm': {
        'label': 'Storage Lvm',
        'concept': 'core concepts and daily workflows for storage lvm',
        'inspect': 'status commands, logs, and configuration related to storage lvm',
        'symptom': 'Storage Lvm misconfiguration causes user-visible failures or operational risk',
        'verify': 'Storage Lvm meets expected health checks after your changes',
    },
    'streams': {
        'label': 'Node.js streams',
        'concept': 'backpressure, piping, and error propagation',
        'inspect': 'stream events, `pipeline()`, and memory usage',
        'symptom': 'streams buffer unbounded and OOM the process',
        'verify': 'stream pipeline handles backpressure without data loss',
    },
    'structured-output': {
        'label': 'structured LLM output',
        'concept': 'JSON schema, function calling, and repair loops',
        'inspect': 'schema validators, retry logs, and parse errors',
        'symptom': 'downstream parser breaks on malformed JSON',
        'verify': 'model output validates against schema reliably',
    },
    'subscription-repos': {
        'label': 'RHEL subscriptions',
        'concept': 'entitlements, repos, and candle status',
        'inspect': '`subscription-manager`, `dnf repolist`, and compliance',
        'symptom': 'hosts cannot install packages due to expired sub',
        'verify': 'system registered with correct repos enabled',
    },
    'systemd-services': {
        'label': 'Systemd Services',
        'concept': 'core concepts and daily workflows for systemd services',
        'inspect': 'status commands, logs, and configuration related to systemd services',
        'symptom': 'Systemd Services misconfiguration causes user-visible failures or operational risk',
        'verify': 'Systemd Services meets expected health checks after your changes',
    },
    'systemd-targets': {
        'label': 'systemd targets',
        'concept': 'default target, dependencies, and rescue mode',
        'inspect': '`systemctl get-default`, `list-dependencies`',
        'symptom': 'boot stops at wrong target after maintenance',
        'verify': 'system reaches multi-user/graphical target reliably',
    },
    'tables': {
        'label': 'HTML tables',
        'concept': 'thead/tbody, scope, and responsive patterns',
        'inspect': 'accessibility tree and horizontal scroll behavior',
        'symptom': 'screen readers cannot navigate wide tables',
        'verify': 'tables expose headers and work on small screens',
    },
    'tcp': {
        'label': 'TCP analysis',
        'concept': 'handshakes, windows, retransmits, and resets',
        'inspect': 'Wireshark TCP stream graphs and seq/ack',
        'symptom': 'connections reset mid-transfer without explanation',
        'verify': 'TCP behavior matches hypothesis for the incident',
    },
    'tcp-scan': {
        'label': 'Tcp Scan',
        'concept': 'core concepts and daily workflows for tcp scan',
        'inspect': 'status commands, logs, and configuration related to tcp scan',
        'symptom': 'Tcp Scan misconfiguration causes user-visible failures or operational risk',
        'verify': 'Tcp Scan meets expected health checks after your changes',
    },
    'templates': {
        'label': 'Ansible templates',
        'concept': 'Jinja, variables, and whitespace control',
        'inspect': '`ansible-playbook --diff` and rendered files',
        'symptom': 'templates render wrong values on edge hosts',
        'verify': 'templates idempotent and produce correct config files',
    },
    'terminal': {
        'label': 'terminal simulation',
        'concept': 'shell state, command history, and validation',
        'inspect': 'simulated FS, last commands, and check scripts',
        'symptom': 'learners unsure which terminal to use',
        'verify': 'terminal reflects lab state and accepts expected commands',
    },
    'testing': {
        'label': 'automated testing',
        'concept': 'unit/integration boundaries, fixtures, and CI gates',
        'inspect': 'test reports, coverage, and flaky test trackers',
        'symptom': 'regressions ship because tests too shallow',
        'verify': 'tests catch realistic failures and run in CI',
    },
    'thermal': {
        'label': 'thermal management',
        'concept': 'sensors, throttling, and airflow',
        'inspect': 'IPMI sensors, GPU temps, and fan curves',
        'symptom': 'thermal throttling caps performance silently',
        'verify': 'thermals within spec under sustained load',
    },
    'timing': {
        'label': 'Nmap timing',
        'concept': 'T0-T5, parallelism, and RTT tuning',
        'inspect': 'nmap `--stats-every` and scan duration logs',
        'symptom': 'scans too slow or trigger rate limits',
        'verify': 'timing template matches network sensitivity',
    },
    'tls': {
        'label': 'Tls',
        'concept': 'core concepts and daily workflows for tls',
        'inspect': 'status commands, logs, and configuration related to tls',
        'symptom': 'Tls misconfiguration causes user-visible failures or operational risk',
        'verify': 'Tls meets expected health checks after your changes',
    },
    'tools': {
        'label': 'LLM tool calling',
        'concept': 'schemas, auth, timeouts, and result parsing',
        'inspect': 'tool call traces, latency, and error payloads',
        'symptom': 'tools invoked with wrong args or infinite loops',
        'verify': 'tool calls succeed with validated arguments',
    },
    'traceroute': {
        'label': 'traceroute',
        'concept': 'hop discovery, ICMP vs UDP, and asymmetric routes',
        'inspect': '`traceroute`, `mtr`, and path changes',
        'symptom': 'cannot tell which hop adds latency/packet loss',
        'verify': 'path map identifies suspect hop with evidence',
    },
    'training': {
        'label': 'model training',
        'concept': 'train/val split, checkpoints, and early stopping',
        'inspect': 'loss curves, GPU util, and experiment tracking',
        'symptom': 'overfitting looks great on train but fails live',
        'verify': 'training reproducible with tracked hyperparameters',
    },
    'transactions': {
        'label': 'database transactions',
        'concept': 'ACID, isolation levels, and deadlocks',
        'inspect': 'BEGIN/COMMIT traces, locks, and rollback tests',
        'symptom': 'partial commits corrupt business invariants',
        'verify': 'transactions commit or roll back atomically',
    },
    'traps': {
        'label': 'shell signal traps',
        'concept': 'EXIT, ERR, INT handlers, and cleanup',
        'inspect': '`trap -p`, manual signals, and temp file cleanup',
        'symptom': 'scripts leave temp files or ignore Ctrl-C',
        'verify': 'traps run cleanup on exit and failure paths',
    },
    'triggers': {
        'label': 'SQLite triggers',
        'concept': 'BEFORE/AFTER, WHEN clauses, and recursion',
        'inspect': '`sqlite_master`, insert tests, and EXPLAIN',
        'symptom': 'trigger causes infinite loop or silent data change',
        'verify': 'triggers enforce invariants without surprise recursion',
    },
    'troubleshooting': {
        'label': 'simulation troubleshooting',
        'concept': 'hypothesis-driven debugging in lab environments',
        'inspect': 'logs, state diffs, and validation output',
        'symptom': 'random changes pass check without understanding',
        'verify': 'troubleshooting doc shows evidence chain to root cause',
    },
    'tsdb': {
        'label': 'Prometheus TSDB',
        'concept': 'blocks, compaction, retention, and WAL',
        'inspect': 'prometheus tsdb stats, disk usage, and queries',
        'symptom': 'queries slow as retention grows unbounded',
        'verify': 'TSDB retention and compaction healthy on disk budget',
    },
    'tuned-profile': {
        'label': 'tuned profiles',
        'concept': 'throughput vs latency profiles and overrides',
        'inspect': '`tuned-adm active`, profile files, and sysctl diffs',
        'symptom': 'wrong profile hurts database latency',
        'verify': 'tuned profile matches workload with measurable benefit',
    },
    'udp-scan': {
        'label': 'UDP scanning',
        'concept': 'open|filtered states, probes, and slow paths',
        'inspect': '`nmap -sU`, specific `-p`, and `--reason`',
        'symptom': 'UDP services invisible in TCP-only scans',
        'verify': 'UDP scan results interpreted with correct caution',
    },
    'users-grants': {
        'label': 'MySQL users and grants',
        'concept': 'authentication plugins, roles, and host patterns',
        'inspect': '`SHOW GRANTS`, `mysql.user`, and connection tests',
        'symptom': 'app user lacks privilege on new schema',
        'verify': 'grants minimal rights from approved app hosts',
    },
    'users-groups': {
        'label': 'Users Groups',
        'concept': 'core concepts and daily workflows for users groups',
        'inspect': 'status commands, logs, and configuration related to users groups',
        'symptom': 'Users Groups misconfiguration causes user-visible failures or operational risk',
        'verify': 'Users Groups meets expected health checks after your changes',
    },
    'vacuum': {
        'label': 'PostgreSQL VACUUM',
        'concept': 'autovacuum, bloat, freeze, and wraparound',
        'inspect': '`pg_stat_user_tables`, `pgstattuple`, and logs',
        'symptom': 'transactions fail near xmin horizon or bloat grows',
        'verify': 'vacuum keeps tables healthy with acceptable bloat',
    },
    'validation': {
        'label': 'ML validation',
        'concept': 'cross-validation, leakage checks, and holdouts',
        'inspect': 'CV splits, metric variance, and feature audit',
        'symptom': 'validation score optimistic due to leakage',
        'verify': 'validation protocol matches production sampling',
    },
    'variables': {
        'label': 'Variables',
        'concept': 'core concepts and daily workflows for variables',
        'inspect': 'status commands, logs, and configuration related to variables',
        'symptom': 'Variables misconfiguration causes user-visible failures or operational risk',
        'verify': 'Variables meets expected health checks after your changes',
    },
    'vault': {
        'label': 'Ansible Vault',
        'concept': 'encrypting vars/files, vault IDs, and rotation',
        'inspect': '`ansible-vault view`, password files, and CI secrets',
        'symptom': 'secrets plaintext in git or vault password shared widely',
        'verify': 'secrets encrypted at rest with rotated vault credentials',
    },
    'vcenter-rbac': {
        'label': 'vCenter RBAC',
        'concept': 'roles, permissions inheritance, and SSO groups',
        'inspect': 'vSphere permissions tab and `govc` checks',
        'symptom': 'operators lack task rights or have excessive admin',
        'verify': 'RBAC maps teams to least-privilege role set',
    },
    'venv': {
        'label': 'Venv',
        'concept': 'core concepts and daily workflows for venv',
        'inspect': 'status commands, logs, and configuration related to venv',
        'symptom': 'Venv misconfiguration causes user-visible failures or operational risk',
        'verify': 'Venv meets expected health checks after your changes',
    },
    'views': {
        'label': 'SQLite views',
        'concept': 'view definitions, updatability, and security',
        'inspect': '`.schema` views and EXPLAIN on view queries',
        'symptom': 'reports query wrong view definition after migration',
        'verify': 'views simplify queries without hiding needed columns',
    },
    'visualization': {
        'label': 'data visualization',
        'concept': 'chart choice, scales, and honest axes',
        'inspect': 'matplotlib/plotly figures and colorblind checks',
        'symptom': 'charts mislead stakeholders about trends',
        'verify': 'visualizations match data table and label uncertainty',
    },
    'vlan': {
        'label': 'VLANs',
        'concept': '802.1Q tagging, trunks, and SVIs',
        'inspect': 'switch port config, `ip -d link`, and ping across VLAN',
        'symptom': 'hosts on same IP range cannot talk due to VLAN mismatch',
        'verify': 'VLAN tagging consistent end-to-end',
    },
    'vm-lifecycle': {
        'label': 'Vm Lifecycle',
        'concept': 'core concepts and daily workflows for vm lifecycle',
        'inspect': 'status commands, logs, and configuration related to vm lifecycle',
        'symptom': 'Vm Lifecycle misconfiguration causes user-visible failures or operational risk',
        'verify': 'Vm Lifecycle meets expected health checks after your changes',
    },
    'vmotion': {
        'label': 'vMotion',
        'concept': 'shared storage, vMotion net, and CPU compatibility',
        'inspect': 'vCenter tasks, vmkernel vmotion iface, and events',
        'symptom': 'vMotion fails at 90% or EVC blocks migration',
        'verify': 'workloads migrate live without connection drop',
    },
    'volumes': {
        'label': 'Volumes',
        'concept': 'core concepts and daily workflows for volumes',
        'inspect': 'status commands, logs, and configuration related to volumes',
        'symptom': 'Volumes misconfiguration causes user-visible failures or operational risk',
        'verify': 'Volumes meets expected health checks after your changes',
    },
    'vulnerability': {
        'label': 'vulnerability management',
        'concept': 'scanning, CVSS prioritization, and patch SLAs',
        'inspect': 'scanner reports, asset inventory, and ticket queue',
        'symptom': 'critical CVEs open for months on internet-facing assets',
        'verify': 'remediation tracked with risk-based prioritization',
    },
    'wal': {
        'label': 'write-ahead logging',
        'concept': 'WAL archiving, replication slots, and PITR',
        'inspect': 'pg_wal directory, `pg_stat_wal`, or SQLite WAL mode',
        'symptom': 'replication breaks when WAL disks fill',
        'verify': 'WAL retained per policy and replay succeeds',
    },
    'workers': {
        'label': 'Node.js worker threads',
        'concept': 'CPU-bound offload, message passing, and SharedArrayBuffer',
        'inspect': 'worker logs, thread count, and perf profiles',
        'symptom': 'event loop blocked by CPU work on main thread',
        'verify': 'workers handle CPU tasks without starving HTTP loop',
    },
    'workspaces': {
        'label': 'Terraform workspaces',
        'concept': 'env isolation, workspace select, and naming',
        'inspect': '`terraform workspace list`, backend prefixes',
        'symptom': 'staging change applied to prod workspace',
        'verify': 'workspaces isolate state with clear naming convention',
    },
}
