#!/usr/bin/env python3
"""Upgrade the generic ``simulation`` technology labs from the legacy
``/tmp/scenario-fixed`` FIXED-OK marker to real simulation validation (B3 sweep).

These 40 labs (``simulation-lab-16``..``-50`` plus the named ``sim-*`` labs) are
``simulation_type: generic`` and are graded by the unified simulation engine via
``check.sh`` → ``validate_simulation_state``. Unlike the coding labs (graded by
hidden tests) and the nmap/wireshark/peoplesoft labs (graded by dedicated
engines), these are the only non-academy old-marker labs whose grading genuinely
depended on the learner writing ``echo FIXED-OK > /tmp/scenario-fixed``.

After this upgrade each lab:
  • boots with a genuinely **failed** systemd unit (real broken OS state), and
  • validates with ``systemctl is-active <unit>`` against the real engine state.

Outputs:
  backend/apps/labs/provisioner/simulation/simulation_marker_presets.py
  backend/apps/labs/provisioner/simulation/simulation_marker_e2e_fixes.py

Re-run idempotently after adding more ``simulation`` labs.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCEN = ROOT / "scenarios" / "simulation"
PRESET_OUT = ROOT / "backend/apps/labs/provisioner/simulation/simulation_marker_presets.py"
E2E_OUT = ROOT / "backend/apps/labs/provisioner/simulation/simulation_marker_e2e_fixes.py"

sys.path.insert(0, str(ROOT / "scripts"))
from upgrade_academy_labs import (  # noqa: E402
    SERVICE_DESC,
    assign_service_unit,
    check_script_for_mode,
    verify_hint_line,
)

MARKER_RE = re.compile(r"scenario-fixed|FIXED-OK")


def _clean_hint(content: str) -> str:
    """Strip any legacy ``echo FIXED-OK`` marker instruction from a hint body."""
    lines = []
    for line in content.splitlines():
        if "FIXED-OK" in line or "scenario-fixed" in line:
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def patch_yaml(path: Path, unit: str, topic_label: str) -> None:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    verify = verify_hint_line("service", unit)
    data["description"] = (
        f"Service operations lab. The `{unit}` systemd unit is **failed/inactive** on "
        f"this host — a realistic fault for {topic_label}. Diagnose with "
        f"`systemctl status {unit}` and the journal, apply the smallest reliable fix, "
        f"then verify with `systemctl is-active {unit}`. Graded against the real "
        f"service state — no completion markers."
    )
    data["initial_state"] = (
        f"The `{unit}` service is not running (`systemctl is-active {unit}` → "
        f"inactive/failed). Dependent tasks cannot succeed until the unit is healthy."
    )
    data["objectives"] = [
        f"The `{unit}` service is active (running)",
        f"`systemctl is-active {unit}` returns active",
        "The fix survives a status re-check (no marker files)",
    ]

    hints = data.get("hints") or []
    cleaned: list[dict] = []
    for h in sorted(hints, key=lambda x: x.get("order", 0)):
        order = h.get("order", len(cleaned) + 1)
        if order == 1:
            h["content"] = (
                "Where to look: a dependent service has stopped. Start broad with "
                f"`systemctl --failed`, then inspect the specific unit with "
                f"`systemctl status {unit}`. Do not change anything yet — confirm "
                "which unit is down and why."
            )
        elif order == 2:
            h["content"] = (
                "Diagnostic steps:\n"
                f"1. `systemctl status {unit}` — read the Active: line and the last log lines.\n"
                f"2. `journalctl -u {unit} -n 50` — look for the error that stopped it.\n"
                "3. Decide on the smallest change that restores the unit (usually a restart "
                "once the underlying cause is understood)."
            )
        else:
            h["content"] = (
                "Exact fix + verification:\n"
                f"1. `sudo systemctl start {unit}` (use `restart` if it is in a failed state).\n"
                f"2. `sudo systemctl enable {unit}` so it survives a reboot.\n"
                f"3. Click Check Solution once {verify}.\n"
                "WHY: the unit was left inactive/failed; starting it restores the dependent "
                "workflow. Validation reads the real service state, so there is nothing to fake."
            )
        h["content"] = _clean_hint(h["content"])
        cleaned.append(h)
    data["hints"] = cleaned

    path.write_text(
        yaml.dump(data, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8",
    )


def _emit_presets(service_units: dict[str, str]) -> None:
    lines = [
        '"""GENERATED by scripts/upgrade_simulation_marker_labs.py — do not edit by hand.',
        "",
        "Real-simulation break presets for the generic ``simulation`` technology labs",
        "(formerly graded by the /tmp/scenario-fixed FIXED-OK marker). Each boots a",
        "genuinely failed systemd unit so the lab is fail-closed until the learner",
        "starts the service. Merged into scenario_presets._PRESETS after the academy",
        "presets.",
        '"""',
        "from __future__ import annotations",
        "",
        "from .rhel_os import SimService",
        "",
        "",
        "def _break_service(state, unit: str, desc: str) -> None:",
        "    state.services[unit] = SimService(",
        '        unit, active="failed", enabled="enabled", description=desc,',
        '        loaded="loaded", sub_state="failed",',
        '        unit_file=f"[Unit]\\nDescription={desc}\\n",',
        "    )",
        "",
        "",
        "SIMULATION_MARKER_PRESETS = {",
    ]
    for slug in sorted(service_units):
        unit = service_units[slug]
        desc = SERVICE_DESC.get(unit, unit)
        lines.append(
            f"    {slug!r}: lambda state, u={unit!r}, d={desc!r}: _break_service(state, u, d),"
        )
    lines.append("}")
    lines.append("")
    PRESET_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _emit_e2e(service_units: dict[str, str]) -> None:
    lines = [
        '"""GENERATED by scripts/upgrade_simulation_marker_labs.py — do not edit by hand.',
        "",
        "E2E fix map for the generic ``simulation`` real-state labs (systemctl start).",
        '"""',
        "from __future__ import annotations",
        "",
        "SIMULATION_SERVICE_FIX: dict[str, str] = {",
    ]
    for slug in sorted(service_units):
        lines.append(f"    {slug!r}: {service_units[slug]!r},")
    lines.append("}")
    lines.append("")
    E2E_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Upgrade generic simulation marker labs")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    service_units: dict[str, str] = {}
    converted = 0

    for folder in sorted(SCEN.iterdir()):
        if not folder.is_dir():
            continue
        yaml_path = folder / "scenario.yaml"
        check_path = folder / "check.sh"
        if not yaml_path.is_file():
            continue
        slug = folder.name
        check_body = check_path.read_text(encoding="utf-8") if check_path.is_file() else ""
        if not MARKER_RE.search(check_body):
            continue  # already converted / not a marker lab

        unit = assign_service_unit("simulation", slug)
        script = check_script_for_mode("service", unit)
        data = yaml.safe_load(yaml_path.read_text(encoding="utf-8")) or {}
        topic_label = (data.get("title") or slug).split("—")[-1].strip() or "simulation operations"

        if not args.dry_run:
            check_path.write_text(script + "exit 0\n", encoding="utf-8")
            patch_yaml(yaml_path, unit, topic_label)

        service_units[slug] = unit
        converted += 1

    if not args.dry_run:
        _emit_presets(service_units)
        _emit_e2e(service_units)

    print(f"simulation marker labs upgraded: {converted}")
    if not args.dry_run:
        print(f"presets:   {PRESET_OUT}")
        print(f"e2e fixes: {E2E_OUT}")


if __name__ == "__main__":
    main()
