# Generated by Django 5.2.15 on 2026-06-22 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('topic', models.CharField(db_index=True, max_length=60)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=10)),
                ('playground_slug', models.CharField(blank=True, max_length=60)),
                ('scenario_slug', models.CharField(blank=True, max_length=255)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('seo_keywords', models.CharField(blank=True, max_length=320)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['is_published', 'order'], name='tutorials_t_is_publ_3f95c9_idx'), models.Index(fields=['topic', 'is_published'], name='tutorials_t_topic_c21818_idx')],
            },
        ),
        migrations.CreateModel(
            name='TutorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('heading', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
                ('code_language', models.CharField(blank=True, default='bash', max_length=30)),
                ('code_caption', models.CharField(blank=True, max_length=200)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tutorials.tutorial')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('tutorial', 'order')},
            },
        ),
    ]
