# Generated by Django 6.0.6 on 2026-06-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorial_progress_and_quiz'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tutorial',
            new_name='tutorials_t_course__95a5cc_idx',
            old_name='tutorials_course_mod_idx',
        ),
        migrations.RenameIndex(
            model_name='tutorialprogress',
            new_name='tutorials_t_user_id_be96c6_idx',
            old_name='tutorials_t_user_id_6a8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='tutorialprogress',
            new_name='tutorials_t_user_id_bfc307_idx',
            old_name='tutorials_t_user_id_9c2b1e_idx',
        ),
    ]
