"""Extended zero-to-hero tracks — merged into course_catalog.COURSE_DEFINITIONS."""

from __future__ import annotations

# Each entry: course_slug, course_title, topic, playground_slug, modules[10]
EXTENDED_COURSES: list[dict] = [
    {
        "course_slug": "bash-shell-zero-hero",
        "course_title": "Bash Shell Scripting: Zero to Hero",
        "topic": "Bash",
        "playground_slug": "bash",
        "modules": [
            "Shell syntax, quoting, and expansion",
            "Variables, arrays, and parameter expansion",
            "Conditionals, tests, and exit codes",
            "Loops, functions, and sourcing",
            "Text processing with awk/sed/grep",
            "Process control and job control",
            "Signal traps and error handling",
            "Debugging with set -x and shellcheck",
            "Production scripting patterns",
            "Enterprise automation and CI hooks",
        ],
    },
    {
        "course_slug": "devops-engineering-zero-hero",
        "course_title": "DevOps Engineering: Zero to Hero",
        "topic": "DevOps",
        "playground_slug": "devops",
        "modules": [
            "DevOps culture and DORA metrics",
            "Version control workflows",
            "Build pipelines and artifact stores",
            "Infrastructure as code foundations",
            "Configuration management",
            "Containerization and orchestration",
            "Observability-driven operations",
            "Incident response and SRE practices",
            "Platform engineering and IDP",
            "Enterprise release governance",
        ],
    },
    {
        "course_slug": "github-actions-zero-hero",
        "course_title": "GitHub & GitHub Actions: Zero to Hero",
        "topic": "GitHub",
        "playground_slug": "github",
        "modules": [
            "Repositories, branches, and protection rules",
            "Pull requests and code review",
            "GitHub Actions workflow syntax",
            "Runners, secrets, and environments",
            "Reusable workflows and composites",
            "Matrix builds and caching",
            "OIDC to cloud deployments",
            "Security: Dependabot and code scanning",
            "Monorepo and release automation",
            "Enterprise org policies and audit",
        ],
    },
    {
        "course_slug": "gitlab-cicd-zero-hero",
        "course_title": "GitLab & GitLab CI/CD: Zero to Hero",
        "topic": "GitLab",
        "playground_slug": "gitlab",
        "modules": [
            "GitLab project structure",
            ".gitlab-ci.yml pipelines",
            "Runners and executor types",
            "Environments and deployments",
            "Container registry integration",
            "Security scanning and compliance",
            "Merge trains and review apps",
            "Multi-project pipelines",
            "Geo and disaster recovery",
            "Enterprise self-managed ops",
        ],
    },
    {
        "course_slug": "kubernetes-deep-zero-hero",
        "course_title": "Kubernetes: Beginner to Expert",
        "topic": "Kubernetes",
        "playground_slug": "kubernetes",
        "modules": [
            "Cluster architecture and kubectl",
            "Pods, Deployments, and Services",
            "ConfigMaps, Secrets, and storage",
            "Ingress, TLS, and networking",
            "RBAC, PSA, and network policies",
            "Helm, operators, and CRDs",
            "Cluster upgrades and HA",
            "Multi-cluster and GitOps",
            "GPU scheduling and AI workloads",
            "Production troubleshooting and DR",
        ],
    },
    {
        "course_slug": "helm-charts-zero-hero",
        "course_title": "Helm: Zero to Hero",
        "topic": "Helm",
        "playground_slug": "kubernetes",
        "modules": [
            "Charts, releases, and repositories",
            "Templates, values, and helpers",
            "Hooks and lifecycle",
            "Dependencies and subcharts",
            "Testing with helm unittest",
            "OCI registries and signing",
            "GitOps with Helm",
            "Multi-env promotion",
            "Performance at scale",
            "Enterprise chart governance",
        ],
    },
    {
        "course_slug": "prometheus-grafana-zero-hero",
        "course_title": "Prometheus & Grafana: Zero to Hero",
        "topic": "Prometheus",
        "playground_slug": "monitoring",
        "modules": [
            "Metrics model and PromQL basics",
            "Exporters and service discovery",
            "Recording rules and alerting",
            "Grafana dashboards and variables",
            "Alertmanager routing",
            "SLOs and error budgets",
            "Long-term storage and federation",
            "Kubernetes monitoring stack",
            "Incident response from alerts",
            "Enterprise observability design",
        ],
    },
    {
        "course_slug": "elk-stack-zero-hero",
        "course_title": "ELK Stack: Zero to Hero",
        "topic": "ELK",
        "playground_slug": "monitoring",
        "modules": [
            "Elasticsearch cluster topology",
            "Index templates and mappings",
            "Logstash pipelines and grok",
            "Kibana dashboards and Discover",
            "Beats and Elastic Agent",
            "ILM and retention policies",
            "Security and RBAC",
            "Cross-cluster search",
            "Performance tuning",
            "Enterprise log analytics",
        ],
    },
    {
        "course_slug": "vyos-networking-zero-hero",
        "course_title": "VyOS Network Engineering: Zero to Hero",
        "topic": "VyOS",
        "playground_slug": "networking",
        "modules": [
            "Installation and initial config",
            "Interfaces, zones, and firewall",
            "Static and dynamic routing",
            "OSPF and BGP fundamentals",
            "NAT, PAT, and load balancing",
            "IPsec and WireGuard VPN",
            "QoS and traffic shaping",
            "High availability and VRRP",
            "ISP and WAN design",
            "Enterprise troubleshooting",
        ],
    },
    {
        "course_slug": "linux-rhcsa-rhce-zero-hero",
        "course_title": "Linux: RHCSA + RHCE Level",
        "topic": "Linux",
        "playground_slug": "linux",
        "modules": [
            "Filesystem, users, and permissions",
            "systemd, journals, and boot",
            "Storage, LVM, and RAID",
            "Networking and firewalld",
            "SELinux and AppArmor",
            "Containers and Podman basics",
            "Ansible ad-hoc and playbooks",
            "Performance tuning and cgroups",
            "Kernel, kdump, and upgrades",
            "Production incidents and Leapp",
        ],
    },
    {
        "course_slug": "ai-infrastructure-zero-hero",
        "course_title": "AI Infrastructure Engineering",
        "topic": "AI Infrastructure",
        "playground_slug": "aiml",
        "modules": [
            "GPU fundamentals: NVIDIA and AMD",
            "CUDA, ROCm, and driver lifecycle",
            "GPU memory, PCIe, and NUMA",
            "GPU monitoring and thermal ops",
            "vLLM, Triton, and NIM inference",
            "KServe and Kubeflow on Kubernetes",
            "Ray and distributed training",
            "Multi-GPU clusters and scheduling",
            "AI datacenter and capacity planning",
            "GPU incident response and RCA",
        ],
    },
    {
        "course_slug": "bare-metal-datacenter-zero-hero",
        "course_title": "Bare Metal Datacenter Engineering",
        "topic": "Bare Metal",
        "playground_slug": "baremetal",
        "modules": [
            "BIOS, UEFI, and firmware",
            "PXE, iPXE, TFTP, and DHCP",
            "Kickstart, cloud-init, and imaging",
            "IPMI, Redfish, and BMC ops",
            "Dell iDRAC, HP iLO, Lenovo XClarity",
            "Rack design and datacenter networking",
            "MAAS architecture and provisioning",
            "Metal3 and bare-metal Kubernetes",
            "Hardware and storage failures",
            "Real datacenter operations",
        ],
    },
    {
        "course_slug": "maas-provisioning-zero-hero",
        "course_title": "MAAS Bare Metal Provisioning",
        "topic": "MAAS",
        "playground_slug": "baremetal",
        "modules": [
            "MAAS architecture and components",
            "Installation and networking",
            "PXE integration and fabrics",
            "Commissioning and testing",
            "Deployment and curtin",
            "MAAS API and automation",
            "VLANs, subnets, and DNS",
            "GPU and custom images",
            "Troubleshooting PXE failures",
            "Enterprise fleet deployments",
        ],
    },
    {
        "course_slug": "cybersecurity-zero-hero",
        "course_title": "Cybersecurity Engineering: Zero to Hero",
        "topic": "Cybersecurity",
        "playground_slug": "security",
        "modules": [
            "Network security fundamentals",
            "Linux hardening and auditing",
            "Cloud security and shared responsibility",
            "DevSecOps in CI/CD",
            "Kubernetes security (PSA, RBAC)",
            "IAM, MFA, and zero trust",
            "SOC operations and playbooks",
            "SIEM detection engineering",
            "Incident response and forensics",
            "Enterprise compliance programs",
        ],
    },
    {
        "course_slug": "ai-engineering-zero-hero",
        "course_title": "AI Engineering: Zero to Hero",
        "topic": "AI Engineering",
        "playground_slug": "aiml",
        "modules": [
            "ML and deep learning foundations",
            "MLOps pipelines and registries",
            "LLMOps and prompt lifecycle",
            "Generative AI system design",
            "AI agents and tool use",
            "RAG architecture and evals",
            "Vector databases and embeddings",
            "Inference optimization",
            "Responsible AI and guardrails",
            "Enterprise AI platform ops",
        ],
    },
    {
        "course_slug": "frontend-web-zero-hero",
        "course_title": "Frontend Web Development: Zero to Hero",
        "topic": "Frontend",
        "playground_slug": "javascript",
        "modules": [
            "HTML semantics and accessibility",
            "CSS layout, flex, and grid",
            "JavaScript ES6+ fundamentals",
            "TypeScript types and tooling",
            "React components and hooks",
            "State management patterns",
            "Next.js routing and SSR",
            "Testing and performance",
            "Security (XSS, CSP, auth)",
            "Enterprise design systems",
        ],
    },
    {
        "course_slug": "backend-api-zero-hero",
        "course_title": "Backend API Development: Zero to Hero",
        "topic": "Backend",
        "playground_slug": "python",
        "modules": [
            "HTTP, REST, and OpenAPI",
            "Node.js and Express.js",
            "Python FastAPI services",
            "Django ORM and admin",
            "Authentication and JWT",
            "Database integration patterns",
            "Caching and message queues",
            "Observability and tracing",
            "Load testing and scaling",
            "Enterprise API governance",
        ],
    },
    {
        "course_slug": "data-science-zero-hero",
        "course_title": "Data Science: Zero to Hero",
        "topic": "Data Science",
        "playground_slug": "python",
        "modules": [
            "NumPy arrays and vectorization",
            "Pandas dataframes and joins",
            "Matplotlib and visualization",
            "Scikit-learn pipelines",
            "Feature engineering",
            "Model evaluation and bias",
            "Experiment tracking",
            "Productionizing notebooks",
            "Data governance",
            "Enterprise analytics platforms",
        ],
    },
    {
        "course_slug": "podman-containers-zero-hero",
        "course_title": "Podman & Containerd: Zero to Hero",
        "topic": "Podman",
        "playground_slug": "docker",
        "modules": [
            "OCI images and registries",
            "Podman rootless containers",
            "Pods, systemd units, and quadlet",
            "Containerd architecture",
            "CRI and Kubernetes runtime",
            "Networking and volumes",
            "Security profiles and seccomp",
            "Image signing and SBOM",
            "Migration from Docker",
            "Enterprise container hosts",
        ],
    },
    {
        "course_slug": "jenkins-cicd-zero-hero",
        "course_title": "Jenkins CI/CD: Zero to Hero",
        "topic": "Jenkins",
        "playground_slug": "devops",
        "modules": [
            "Controller and agent model",
            "Declarative pipelines",
            "Shared libraries",
            "Credentials and secrets",
            "Multibranch and PR builds",
            "Docker and Kubernetes agents",
            "Quality gates and artifacts",
            "Backup and HA controllers",
            "Plugin security",
            "Enterprise Jenkins ops",
        ],
    },
    {
        "course_slug": "argocd-gitops-zero-hero",
        "course_title": "Argo CD GitOps: Zero to Hero",
        "topic": "ArgoCD",
        "playground_slug": "kubernetes",
        "modules": [
            "GitOps principles",
            "Applications and projects",
            "Sync policies and hooks",
            "Helm and Kustomize apps",
            "Multi-cluster management",
            "SSO and RBAC",
            "Progressive delivery",
            "Disaster recovery",
            "Observability integration",
            "Enterprise GitOps platforms",
        ],
    },
    {
        "course_slug": "pulumi-iac-zero-hero",
        "course_title": "Pulumi Infrastructure as Code",
        "topic": "Pulumi",
        "playground_slug": "terraform",
        "modules": [
            "Pulumi projects and stacks",
            "Python/TS resource definitions",
            "State and backends",
            "Components and modules",
            "Policy and testing",
            "CI/CD integration",
            "Secrets management",
            "Multi-cloud patterns",
            "Drift and refresh",
            "Enterprise IaC platforms",
        ],
    },
    {
        "course_slug": "cisco-networking-zero-hero",
        "course_title": "Cisco Networking: Zero to Hero",
        "topic": "Cisco",
        "playground_slug": "networking",
        "modules": [
            "IOS CLI and device roles",
            "Switching and VLANs",
            "Routing protocols overview",
            "OSPF and EIGRP",
            "BGP for enterprise WAN",
            "ACLs and security zones",
            "NAT and load balancing",
            "QoS and VoIP",
            "Automation with Netmiko",
            "Enterprise campus design",
        ],
    },
    {
        "course_slug": "mongodb-dba-zero-hero",
        "course_title": "MongoDB: Zero to Hero",
        "topic": "MongoDB",
        "playground_slug": "mongodb",
        "modules": [
            "Documents and collections",
            "Indexes and aggregation",
            "Replication sets",
            "Sharding topology",
            "Backup and restore",
            "Security and TLS",
            "Performance tuning",
            "Change streams",
            "Atlas vs self-hosted",
            "Enterprise DBA operations",
        ],
    },
    {
        "course_slug": "openshift-platform-zero-hero",
        "course_title": "OpenShift Platform: Zero to Hero",
        "topic": "OpenShift",
        "playground_slug": "kubernetes",
        "modules": [
            "OpenShift architecture",
            "Projects, routes, and S2I",
            "Operators and OLM",
            "Security context constraints",
            "Networking and SDN",
            "Storage and CSI",
            "Monitoring stack",
            "Upgrades and disconnected",
            "Multi-cluster management",
            "Enterprise OpenShift ops",
        ],
    },
]
