"""Extended zero-to-hero tracks — merged into course_catalog.COURSE_DEFINITIONS."""

from __future__ import annotations

# Each entry: course_slug, course_title, topic, playground_slug, modules[10]
EXTENDED_COURSES: list[dict] = [
    {
        "course_slug": "bash-shell-zero-hero",
        "course_title": "Bash Shell Scripting: Zero to Hero",
        "topic": "Bash",
        "playground_slug": "bash",
        "modules": [
            "Shell syntax, quoting, and expansion",
            "Variables, arrays, and parameter expansion",
            "Conditionals, tests, and exit codes",
            "Loops, functions, and sourcing",
            "Text processing with awk/sed/grep",
            "Process control and job control",
            "Signal traps and error handling",
            "Debugging with set -x and shellcheck",
            "Production scripting patterns",
            "Enterprise automation and CI hooks",
        ],
    },
    {
        "course_slug": "devops-engineering-zero-hero",
        "course_title": "DevOps Engineering: Zero to Hero",
        "topic": "DevOps",
        "playground_slug": "devops",
        "modules": [
            "DevOps culture and DORA metrics",
            "Version control workflows",
            "Build pipelines and artifact stores",
            "Infrastructure as code foundations",
            "Configuration management",
            "Containerization and orchestration",
            "Observability-driven operations",
            "Incident response and SRE practices",
            "Platform engineering and IDP",
            "Enterprise release governance",
        ],
    },
    {
        "course_slug": "github-actions-zero-hero",
        "course_title": "GitHub & GitHub Actions: Zero to Hero",
        "topic": "GitHub",
        "playground_slug": "github",
        "modules": [
            "Repositories, branches, and protection rules",
            "Pull requests and code review",
            "GitHub Actions workflow syntax",
            "Runners, secrets, and environments",
            "Reusable workflows and composites",
            "Matrix builds and caching",
            "OIDC to cloud deployments",
            "Security: Dependabot and code scanning",
            "Monorepo and release automation",
            "Enterprise org policies and audit",
        ],
    },
    {
        "course_slug": "gitlab-cicd-zero-hero",
        "course_title": "GitLab & GitLab CI/CD: Zero to Hero",
        "topic": "GitLab",
        "playground_slug": "gitlab",
        "modules": [
            "GitLab project structure",
            ".gitlab-ci.yml pipelines",
            "Runners and executor types",
            "Environments and deployments",
            "Container registry integration",
            "Security scanning and compliance",
            "Merge trains and review apps",
            "Multi-project pipelines",
            "Geo and disaster recovery",
            "Enterprise self-managed ops",
        ],
    },
    {
        "course_slug": "kubernetes-deep-zero-hero",
        "course_title": "Kubernetes: Beginner to Expert",
        "topic": "Kubernetes",
        "playground_slug": "kubernetes",
        "modules": [
            "Cluster architecture and kubectl",
            "Pods, Deployments, and Services",
            "ConfigMaps, Secrets, and storage",
            "Ingress, TLS, and networking",
            "RBAC, PSA, and network policies",
            "Helm, operators, and CRDs",
            "Cluster upgrades and HA",
            "Multi-cluster and GitOps",
            "GPU scheduling and AI workloads",
            "Production troubleshooting and DR",
        ],
    },
    {
        "course_slug": "helm-charts-zero-hero",
        "course_title": "Helm: Zero to Hero",
        "topic": "Helm",
        "playground_slug": "kubernetes",
        "modules": [
            "Charts, releases, and repositories",
            "Templates, values, and helpers",
            "Hooks and lifecycle",
            "Dependencies and subcharts",
            "Testing with helm unittest",
            "OCI registries and signing",
            "GitOps with Helm",
            "Multi-env promotion",
            "Performance at scale",
            "Enterprise chart governance",
        ],
    },
    {
        "course_slug": "prometheus-grafana-zero-hero",
        "course_title": "Prometheus & Grafana: Zero to Hero",
        "topic": "Prometheus",
        "playground_slug": "monitoring",
        "modules": [
            "Metrics model and PromQL basics",
            "Exporters and service discovery",
            "Recording rules and alerting",
            "Grafana dashboards and variables",
            "Alertmanager routing",
            "SLOs and error budgets",
            "Long-term storage and federation",
            "Kubernetes monitoring stack",
            "Incident response from alerts",
            "Enterprise observability design",
        ],
    },
    {
        "course_slug": "elk-stack-zero-hero",
        "course_title": "ELK Stack: Zero to Hero",
        "topic": "ELK",
        "playground_slug": "monitoring",
        "modules": [
            "Elasticsearch cluster topology",
            "Index templates and mappings",
            "Logstash pipelines and grok",
            "Kibana dashboards and Discover",
            "Beats and Elastic Agent",
            "ILM and retention policies",
            "Security and RBAC",
            "Cross-cluster search",
            "Performance tuning",
            "Enterprise log analytics",
        ],
    },
    {
        "course_slug": "vyos-networking-zero-hero",
        "course_title": "VyOS Network Engineering: Zero to Hero",
        "topic": "VyOS",
        "playground_slug": "networking",
        "modules": [
            "Installation and initial config",
            "Interfaces, zones, and firewall",
            "Static and dynamic routing",
            "OSPF and BGP fundamentals",
            "NAT, PAT, and load balancing",
            "IPsec and WireGuard VPN",
            "QoS and traffic shaping",
            "High availability and VRRP",
            "ISP and WAN design",
            "Enterprise troubleshooting",
        ],
    },
    {
        "course_slug": "linux-rhcsa-rhce-zero-hero",
        "course_title": "Linux: RHCSA + RHCE Level",
        "topic": "Linux",
        "playground_slug": "linux",
        "modules": [
            "Filesystem, users, and permissions",
            "systemd, journals, and boot",
            "Storage, LVM, and RAID",
            "Networking and firewalld",
            "SELinux and AppArmor",
            "Containers and Podman basics",
            "Ansible ad-hoc and playbooks",
            "Performance tuning and cgroups",
            "Kernel, kdump, and upgrades",
            "Production incidents and Leapp",
        ],
    },
    {
        "course_slug": "ai-infrastructure-zero-hero",
        "course_title": "AI Infrastructure Engineering",
        "topic": "AI Infrastructure",
        "playground_slug": "aiml",
        "modules": [
            "GPU fundamentals: NVIDIA and AMD",
            "CUDA, ROCm, and driver lifecycle",
            "GPU memory, PCIe, and NUMA",
            "GPU monitoring and thermal ops",
            "vLLM, Triton, and NIM inference",
            "KServe and Kubeflow on Kubernetes",
            "Ray and distributed training",
            "Multi-GPU clusters and scheduling",
            "AI datacenter and capacity planning",
            "GPU incident response and RCA",
        ],
    },
    {
        "course_slug": "bare-metal-datacenter-zero-hero",
        "course_title": "Bare Metal Datacenter Engineering",
        "topic": "Bare Metal",
        "playground_slug": "baremetal",
        "modules": [
            "BIOS, UEFI, and firmware",
            "PXE, iPXE, TFTP, and DHCP",
            "Kickstart, cloud-init, and imaging",
            "IPMI, Redfish, and BMC ops",
            "Dell iDRAC, HP iLO, Lenovo XClarity",
            "Rack design and datacenter networking",
            "MAAS architecture and provisioning",
            "Metal3 and bare-metal Kubernetes",
            "Hardware and storage failures",
            "Real datacenter operations",
        ],
    },
    {
        "course_slug": "maas-provisioning-zero-hero",
        "course_title": "MAAS Bare Metal Provisioning",
        "topic": "MAAS",
        "playground_slug": "baremetal",
        "modules": [
            "MAAS architecture and components",
            "Installation and networking",
            "PXE integration and fabrics",
            "Commissioning and testing",
            "Deployment and curtin",
            "MAAS API and automation",
            "VLANs, subnets, and DNS",
            "GPU and custom images",
            "Troubleshooting PXE failures",
            "Enterprise fleet deployments",
        ],
    },
    {
        "course_slug": "cybersecurity-zero-hero",
        "course_title": "Cybersecurity Engineering: Zero to Hero",
        "topic": "Cybersecurity",
        "playground_slug": "security",
        "modules": [
            "Network security fundamentals",
            "Linux hardening and auditing",
            "Cloud security and shared responsibility",
            "DevSecOps in CI/CD",
            "Kubernetes security (PSA, RBAC)",
            "IAM, MFA, and zero trust",
            "SOC operations and playbooks",
            "SIEM detection engineering",
            "Incident response and forensics",
            "Enterprise compliance programs",
        ],
    },
    {
        "course_slug": "ai-engineering-zero-hero",
        "course_title": "AI Engineering: Zero to Hero",
        "topic": "AI Engineering",
        "playground_slug": "aiml",
        "modules": [
            "ML and deep learning foundations",
            "MLOps pipelines and registries",
            "LLMOps and prompt lifecycle",
            "Generative AI system design",
            "AI agents and tool use",
            "RAG architecture and evals",
            "Vector databases and embeddings",
            "Inference optimization",
            "Responsible AI and guardrails",
            "Enterprise AI platform ops",
        ],
    },
    {
        "course_slug": "frontend-web-zero-hero",
        "course_title": "Frontend Web Development: Zero to Hero",
        "topic": "Frontend",
        "playground_slug": "javascript",
        "modules": [
            "HTML semantics and accessibility",
            "CSS layout, flex, and grid",
            "JavaScript ES6+ fundamentals",
            "TypeScript types and tooling",
            "React components and hooks",
            "State management patterns",
            "Next.js routing and SSR",
            "Testing and performance",
            "Security (XSS, CSP, auth)",
            "Enterprise design systems",
        ],
    },
    {
        "course_slug": "backend-api-zero-hero",
        "course_title": "Backend API Development: Zero to Hero",
        "topic": "Backend",
        "playground_slug": "python",
        "modules": [
            "HTTP, REST, and OpenAPI",
            "Node.js and Express.js",
            "Python FastAPI services",
            "Django ORM and admin",
            "Authentication and JWT",
            "Database integration patterns",
            "Caching and message queues",
            "Observability and tracing",
            "Load testing and scaling",
            "Enterprise API governance",
        ],
    },
    {
        "course_slug": "data-science-zero-hero",
        "course_title": "Data Science: Zero to Hero",
        "topic": "Data Science",
        "playground_slug": "python",
        "modules": [
            "NumPy arrays and vectorization",
            "Pandas dataframes and joins",
            "Matplotlib and visualization",
            "Scikit-learn pipelines",
            "Feature engineering",
            "Model evaluation and bias",
            "Experiment tracking",
            "Productionizing notebooks",
            "Data governance",
            "Enterprise analytics platforms",
        ],
    },
    {
        "course_slug": "podman-containers-zero-hero",
        "course_title": "Podman & Containerd: Zero to Hero",
        "topic": "Podman",
        "playground_slug": "docker",
        "modules": [
            "OCI images and registries",
            "Podman rootless containers",
            "Pods, systemd units, and quadlet",
            "Containerd architecture",
            "CRI and Kubernetes runtime",
            "Networking and volumes",
            "Security profiles and seccomp",
            "Image signing and SBOM",
            "Migration from Docker",
            "Enterprise container hosts",
        ],
    },
    {
        "course_slug": "jenkins-cicd-zero-hero",
        "course_title": "Jenkins CI/CD: Zero to Hero",
        "topic": "Jenkins",
        "playground_slug": "devops",
        "modules": [
            "Controller and agent model",
            "Declarative pipelines",
            "Shared libraries",
            "Credentials and secrets",
            "Multibranch and PR builds",
            "Docker and Kubernetes agents",
            "Quality gates and artifacts",
            "Backup and HA controllers",
            "Plugin security",
            "Enterprise Jenkins ops",
        ],
    },
    {
        "course_slug": "argocd-gitops-zero-hero",
        "course_title": "Argo CD GitOps: Zero to Hero",
        "topic": "ArgoCD",
        "playground_slug": "kubernetes",
        "modules": [
            "GitOps principles",
            "Applications and projects",
            "Sync policies and hooks",
            "Helm and Kustomize apps",
            "Multi-cluster management",
            "SSO and RBAC",
            "Progressive delivery",
            "Disaster recovery",
            "Observability integration",
            "Enterprise GitOps platforms",
        ],
    },
    {
        "course_slug": "pulumi-iac-zero-hero",
        "course_title": "Pulumi Infrastructure as Code",
        "topic": "Pulumi",
        "playground_slug": "terraform",
        "modules": [
            "Pulumi projects and stacks",
            "Python/TS resource definitions",
            "State and backends",
            "Components and modules",
            "Policy and testing",
            "CI/CD integration",
            "Secrets management",
            "Multi-cloud patterns",
            "Drift and refresh",
            "Enterprise IaC platforms",
        ],
    },
    {
        "course_slug": "cisco-networking-zero-hero",
        "course_title": "Cisco Networking: Zero to Hero",
        "topic": "Cisco",
        "playground_slug": "networking",
        "modules": [
            "IOS CLI and device roles",
            "Switching and VLANs",
            "Routing protocols overview",
            "OSPF and EIGRP",
            "BGP for enterprise WAN",
            "ACLs and security zones",
            "NAT and load balancing",
            "QoS and VoIP",
            "Automation with Netmiko",
            "Enterprise campus design",
        ],
    },
    {
        "course_slug": "mongodb-dba-zero-hero",
        "course_title": "MongoDB: Zero to Hero",
        "topic": "MongoDB",
        "playground_slug": "mongodb",
        "modules": [
            "Documents and collections",
            "Indexes and aggregation",
            "Replication sets",
            "Sharding topology",
            "Backup and restore",
            "Security and TLS",
            "Performance tuning",
            "Change streams",
            "Atlas vs self-hosted",
            "Enterprise DBA operations",
        ],
    },
    {
        "course_slug": "openshift-platform-zero-hero",
        "course_title": "OpenShift Platform: Zero to Hero",
        "topic": "OpenShift",
        "playground_slug": "kubernetes",
        "modules": [
            "OpenShift architecture",
            "Projects, routes, and S2I",
            "Operators and OLM",
            "Security context constraints",
            "Networking and SDN",
            "Storage and CSI",
            "Monitoring stack",
            "Upgrades and disconnected",
            "Multi-cluster management",
            "Enterprise OpenShift ops",
        ],
    },
    {
        "course_slug": "database-engineering-zero-hero",
        "course_title": "Database Engineering: Zero to Hero",
        "topic": "Database",
        "playground_slug": "postgresql",
        "modules": [
            "Relational model and ACID",
            "PostgreSQL administration",
            "MySQL and InnoDB tuning",
            "SQLite embedded workloads",
            "MongoDB document design",
            "Redis caching patterns",
            "Backups, PITR, and restore drills",
            "Replication and high availability",
            "Security, auditing, and compliance",
            "Enterprise DBA operations",
        ],
    },
    {
        "course_slug": "sqlite-embedded-zero-hero",
        "course_title": "SQLite: Zero to Hero",
        "topic": "SQLite",
        "playground_slug": "sqlite",
        "modules": [
            "Embedded database fundamentals",
            "Schema design and constraints",
            "WAL mode and concurrency",
            "Indexes and query plans",
            "Backup and migration",
            "Application integration",
            "Performance tuning",
            "Security and encryption",
            "Testing and CI patterns",
            "Enterprise edge deployments",
        ],
    },
    {
        "course_slug": "grafana-visualization-zero-hero",
        "course_title": "Grafana: Zero to Hero",
        "topic": "Grafana",
        "playground_slug": "monitoring",
        "modules": [
            "Grafana architecture and plugins",
            "Datasources and authentication",
            "Dashboard design and variables",
            "Panels, alerts, and annotations",
            "Explore and ad-hoc queries",
            "Loki log dashboards",
            "Tempo trace correlation",
            "RBAC and organization",
            "Performance and scaling",
            "Enterprise observability design",
        ],
    },
    {
        "course_slug": "loki-logging-zero-hero",
        "course_title": "Loki Log Aggregation: Zero to Hero",
        "topic": "Loki",
        "playground_slug": "monitoring",
        "modules": [
            "Loki architecture and labels",
            "Promtail and log shipping",
            "LogQL queries",
            "Retention and compaction",
            "Multi-tenant isolation",
            "Alerting from logs",
            "Grafana integration",
            "Performance tuning",
            "Security and access control",
            "Enterprise log platforms",
        ],
    },
    {
        "course_slug": "tempo-tracing-zero-hero",
        "course_title": "Tempo Distributed Tracing: Zero to Hero",
        "topic": "Tempo",
        "playground_slug": "monitoring",
        "modules": [
            "Tracing fundamentals",
            "Tempo architecture",
            "OpenTelemetry instrumentation",
            "Trace ingestion and storage",
            "TraceQL queries",
            "Grafana correlation",
            "Sampling strategies",
            "Performance at scale",
            "Security and PII",
            "Enterprise APM design",
        ],
    },
    {
        "course_slug": "jaeger-tracing-zero-hero",
        "course_title": "Jaeger Tracing: Zero to Hero",
        "topic": "Jaeger",
        "playground_slug": "monitoring",
        "modules": [
            "Distributed tracing concepts",
            "Jaeger components",
            "Instrumentation libraries",
            "Context propagation",
            "Storage backends",
            "UI and dependency graphs",
            "Kubernetes deployment",
            "Performance tuning",
            "Security practices",
            "Enterprise tracing ops",
        ],
    },
    {
        "course_slug": "cloudformation-iac-zero-hero",
        "course_title": "AWS CloudFormation: Zero to Hero",
        "topic": "CloudFormation",
        "playground_slug": "aws",
        "modules": [
            "Templates and stacks",
            "Parameters and mappings",
            "Resources and dependencies",
            "Nested stacks and modules",
            "Change sets and drift",
            "StackSets multi-account",
            "IAM and security",
            "CI/CD integration",
            "Troubleshooting failures",
            "Enterprise landing zones",
        ],
    },
    {
        "course_slug": "packer-images-zero-hero",
        "course_title": "Packer Image Building: Zero to Hero",
        "topic": "Packer",
        "playground_slug": "devops",
        "modules": [
            "Packer workflow and builders",
            "Provisioners and templates",
            "Multi-cloud AMIs",
            "Golden image pipelines",
            "Testing and validation",
            "Secrets and variables",
            "CI/CD integration",
            "Versioning and promotion",
            "Security hardening",
            "Enterprise image factories",
        ],
    },
    {
        "course_slug": "bitbucket-git-zero-hero",
        "course_title": "Bitbucket & Git: Zero to Hero",
        "topic": "Bitbucket",
        "playground_slug": "git",
        "modules": [
            "Repositories and branching",
            "Pull requests and merge checks",
            "Bitbucket Pipelines",
            "Runners and caches",
            "Deployment environments",
            "Security scanning",
            "Integrations and webhooks",
            "Monorepo patterns",
            "Data center vs cloud",
            "Enterprise Git governance",
        ],
    },
    {
        "course_slug": "pfsense-firewall-zero-hero",
        "course_title": "pfSense Firewall: Zero to Hero",
        "topic": "pfSense",
        "playground_slug": "networking",
        "modules": [
            "Installation and interfaces",
            "Firewall rules and NAT",
            "VPN IPsec and OpenVPN",
            "Routing and VLANs",
            "High availability CARP",
            "Traffic shaping",
            "Monitoring and logs",
            "Package ecosystem",
            "Backup and restore",
            "Enterprise edge design",
        ],
    },
    {
        "course_slug": "mikrotik-router-zero-hero",
        "course_title": "MikroTik RouterOS: Zero to Hero",
        "topic": "MikroTik",
        "playground_slug": "networking",
        "modules": [
            "RouterOS basics and Winbox",
            "Interfaces and bridging",
            "Firewall and mangle",
            "Routing and OSPF",
            "BGP for ISPs",
            "Wireless and CAPsMAN",
            "VPN and tunneling",
            "Scripts and automation",
            "Monitoring and Netwatch",
            "Enterprise WISP design",
        ],
    },
    {
        "course_slug": "tcpip-networking-zero-hero",
        "course_title": "TCP/IP Networking: Zero to Hero",
        "topic": "Networking",
        "playground_slug": "networking",
        "modules": [
            "OSI and TCP/IP models",
            "IP addressing and subnetting",
            "Routing and switching",
            "DNS and DHCP",
            "Load balancers and proxies",
            "Firewalls and ACLs",
            "Wireless fundamentals",
            "Network troubleshooting",
            "Performance and QoS",
            "Enterprise WAN design",
        ],
    },
    {
        "course_slug": "typescript-zero-hero",
        "course_title": "TypeScript: Zero to Hero",
        "topic": "TypeScript",
        "playground_slug": "javascript",
        "modules": [
            "Types and interfaces",
            "Generics and utility types",
            "Modules and tooling",
            "Strict mode and linting",
            "Async patterns",
            "Testing with Vitest",
            "Node.js integration",
            "React + TypeScript",
            "API client patterns",
            "Enterprise TS monorepos",
        ],
    },
    {
        "course_slug": "react-frontend-zero-hero",
        "course_title": "React: Zero to Hero",
        "topic": "React",
        "playground_slug": "javascript",
        "modules": [
            "Components and JSX",
            "Props, state, and hooks",
            "Context and composition",
            "Routing and data fetching",
            "Forms and validation",
            "Testing with RTL",
            "Performance optimization",
            "Accessibility",
            "Security (XSS, CSP)",
            "Enterprise design systems",
        ],
    },
    {
        "course_slug": "nextjs-fullstack-zero-hero",
        "course_title": "Next.js: Zero to Hero",
        "topic": "Next.js",
        "playground_slug": "javascript",
        "modules": [
            "App Router and pages",
            "Server vs client components",
            "Data fetching and caching",
            "API routes and middleware",
            "Authentication patterns",
            "Deployment and edge",
            "SEO and performance",
            "Testing and CI",
            "Observability",
            "Enterprise Next.js platforms",
        ],
    },
    {
        "course_slug": "django-backend-zero-hero",
        "course_title": "Django: Zero to Hero",
        "topic": "Django",
        "playground_slug": "python",
        "modules": [
            "Models, ORM, and migrations",
            "Views, URLs, and templates",
            "Admin and auth",
            "REST with DRF",
            "Celery and async tasks",
            "Caching and sessions",
            "Testing and fixtures",
            "Security hardening",
            "Deployment and scaling",
            "Enterprise Django ops",
        ],
    },
    {
        "course_slug": "fastapi-backend-zero-hero",
        "course_title": "FastAPI: Zero to Hero",
        "topic": "FastAPI",
        "playground_slug": "python",
        "modules": [
            "Path and query params",
            "Pydantic models",
            "Dependency injection",
            "Async endpoints",
            "Authentication and OAuth2",
            "Database integration",
            "Testing with pytest",
            "OpenAPI and clients",
            "Deployment with Uvicorn",
            "Enterprise API platforms",
        ],
    },
    {
        "course_slug": "nodejs-express-zero-hero",
        "course_title": "Node.js & Express: Zero to Hero",
        "topic": "Node.js",
        "playground_slug": "javascript",
        "modules": [
            "Event loop and modules",
            "Express routing",
            "Middleware patterns",
            "Error handling",
            "Authentication JWT",
            "Database drivers",
            "Testing with Jest",
            "Performance profiling",
            "Security best practices",
            "Enterprise Node services",
        ],
    },
    {
        "course_slug": "fixitlab-simulation-zero-hero",
        "course_title": "FixitLab Simulation Platform",
        "topic": "Simulation",
        "playground_slug": "simulation",
        "modules": [
            "Simulation engine overview",
            "Terminal vs GUI labs",
            "Validation and grading",
            "Cross-technology sessions",
            "Hints and scoring",
            "Simulator launcher",
            "Terraform and AWX sims",
            "Monitoring simulators",
            "Windows and VMware GUI",
            "Enterprise training deployment",
        ],
    },
    {
        "course_slug": "html-web-zero-hero",
        "course_title": "HTML: Zero to Hero",
        "topic": "HTML",
        "playground_slug": "html",
        "modules": [
            "Document structure and DOCTYPE",
            "Semantic elements and accessibility",
            "Forms, inputs, and validation",
            "Tables and structured data",
            "Media, audio, and video",
            "Meta tags and SEO basics",
            "Microdata and schema.org",
            "Email HTML constraints",
            "Security (CSP, sanitization)",
            "Enterprise content standards",
        ],
    },
    {
        "course_slug": "css-styling-zero-hero",
        "course_title": "CSS: Zero to Hero",
        "topic": "CSS",
        "playground_slug": "html",
        "modules": [
            "Selectors and the cascade",
            "Box model and layout flow",
            "Flexbox for components",
            "CSS Grid for pages",
            "Responsive design and media queries",
            "Typography and color systems",
            "Animations and transitions",
            "CSS variables and theming",
            "Performance and critical CSS",
            "Enterprise design tokens",
        ],
    },
    {
        "course_slug": "javascript-language-zero-hero",
        "course_title": "JavaScript: Zero to Hero",
        "topic": "JavaScript",
        "playground_slug": "javascript",
        "modules": [
            "Syntax, types, and variables",
            "Functions, scope, and closures",
            "Objects, arrays, and prototypes",
            "Async: promises and async/await",
            "Modules ESM and bundlers",
            "DOM manipulation and events",
            "Fetch API and HTTP clients",
            "Testing with Vitest/Jest",
            "Security (XSS, CORS, CSP)",
            "Enterprise JS codebases",
        ],
    },
    {
        "course_slug": "expressjs-api-zero-hero",
        "course_title": "Express.js: Zero to Hero",
        "topic": "Express.js",
        "playground_slug": "javascript",
        "modules": [
            "Express app structure",
            "Routing and route params",
            "Middleware chain patterns",
            "Body parsing and validation",
            "Error handling middleware",
            "Authentication and sessions",
            "REST API design",
            "Testing with supertest",
            "Production hardening",
            "Enterprise Node APIs",
        ],
    },
    {
        "course_slug": "containerd-runtime-zero-hero",
        "course_title": "Containerd: Zero to Hero",
        "topic": "Containerd",
        "playground_slug": "docker",
        "modules": [
            "Containerd architecture",
            "ctr CLI and namespaces",
            "CRI with Kubernetes",
            "Image pull and unpack",
            "Snapshots and overlays",
            "crictl debugging pods",
            "Registry configuration",
            "Security and seccomp",
            "Performance tuning",
            "Enterprise container hosts",
        ],
    },
    {
        "course_slug": "devsecops-zero-hero",
        "course_title": "DevSecOps: Zero to Hero",
        "topic": "DevSecOps",
        "playground_slug": "security",
        "modules": [
            "Shift-left security culture",
            "SAST in CI pipelines",
            "Dependency and SCA scanning",
            "Container image scanning",
            "Secrets detection in Git",
            "DAST and penetration testing",
            "SBOM and supply chain",
            "Policy as code (OPA)",
            "Runtime security (Falco)",
            "Enterprise DevSecOps programs",
        ],
    },
    {
        "course_slug": "iam-identity-zero-hero",
        "course_title": "IAM & Identity: Zero to Hero",
        "topic": "IAM",
        "playground_slug": "security",
        "modules": [
            "Identity lifecycle",
            "Authentication factors and MFA",
            "SSO with SAML and OIDC",
            "RBAC and ABAC models",
            "Cloud IAM (AWS, Azure, GCP)",
            "Service accounts and workload ID",
            "Privileged access management",
            "Access reviews and audits",
            "Zero trust identity",
            "Enterprise IAM architecture",
        ],
    },
    {
        "course_slug": "soc-operations-zero-hero",
        "course_title": "SOC Operations: Zero to Hero",
        "topic": "SOC",
        "playground_slug": "security",
        "modules": [
            "SOC tiers and workflows",
            "Alert triage and prioritization",
            "Playbooks and runbooks",
            "Threat intelligence feeds",
            "EDR and network detection",
            "Phishing analysis",
            "Escalation and comms",
            "Metrics: MTTD, MTTR",
            "Purple team exercises",
            "Enterprise SOC design",
        ],
    },
    {
        "course_slug": "siem-engineering-zero-hero",
        "course_title": "SIEM Engineering: Zero to Hero",
        "topic": "SIEM",
        "playground_slug": "security",
        "modules": [
            "Log ingestion pipelines",
            "Normalization and parsing",
            "Correlation rules",
            "MITRE ATT&CK mapping",
            "Use cases and detection engineering",
            "False positive tuning",
            "SOAR automation",
            "Retention and compliance",
            "High-volume scaling",
            "Enterprise SIEM architecture",
        ],
    },
    {
        "course_slug": "github-actions-zero-hero",
        "course_title": "GitHub Actions: Zero to Hero",
        "topic": "GitHub",
        "playground_slug": "github",
        "modules": [
            "Workflow syntax and triggers",
            "Jobs, steps, and actions",
            "Runners and environments",
            "Secrets and OIDC to cloud",
            "Matrix builds and caching",
            "Reusable workflows",
            "Container and service jobs",
            "Security scanning in CI",
            "Deployment strategies",
            "Enterprise Actions governance",
        ],
    },
    {
        "course_slug": "gitlab-cicd-pipelines-zero-hero",
        "course_title": "GitLab CI/CD Pipelines: Zero to Hero",
        "topic": "GitLab",
        "playground_slug": "gitlab",
        "modules": [
            "Pipeline architecture",
            "Stages, jobs, and artifacts",
            "Runners and executors",
            "Variables and environments",
            "Container registry in CI",
            "Security and compliance jobs",
            "Multi-project pipelines",
            "Review apps and merge trains",
            "Performance and caching",
            "Enterprise GitLab CI ops",
        ],
    },
    {
        "course_slug": "java-zero-hero",
        "course_title": "Java Development: Zero to Hero",
        "topic": "Java",
        "playground_slug": "java",
        "modules": [
            "JDK, JVM, and project structure",
            "Types, control flow, and OOP basics",
            "Collections, generics, and streams",
            "Exceptions, logging, and testing",
            "Build tools: Maven and Gradle",
            "Spring Boot foundations",
            "REST APIs and validation",
            "Persistence with JPA",
            "Security and configuration",
            "Production deployment and troubleshooting",
        ],
    },
    {
        "course_slug": "nmap-zero-hero",
        "course_title": "Nmap Network Scanning: Zero to Hero",
        "topic": "Nmap",
        "playground_slug": "networking",
        "modules": [
            "Host discovery and port scanning",
            "Service and version detection",
            "OS fingerprinting",
            "NSE scripts and automation",
            "Firewall and IDS evasion basics",
            "Scan timing and performance",
            "Output formats and reporting",
            "Network inventory workflows",
            "Security assessment patterns",
            "Enterprise scanning governance",
        ],
    },
    {
        "course_slug": "wireshark-zero-hero",
        "course_title": "Wireshark Packet Analysis: Zero to Hero",
        "topic": "Wireshark",
        "playground_slug": "networking",
        "modules": [
            "Capture filters and interfaces",
            "Display filters and coloring",
            "TCP/UDP session analysis",
            "DNS, HTTP, and TLS inspection",
            "VoIP and application protocols",
            "Latency and retransmission analysis",
            "Malware and anomaly hunting",
            "Capture file management",
            "Troubleshooting production incidents",
            "Enterprise packet capture design",
        ],
    },
    {
        "course_slug": "peoplesoft-zero-hero",
        "course_title": "PeopleSoft Administration: Zero to Hero",
        "topic": "PeopleSoft",
        "playground_slug": "peoplesoft",
        "modules": [
            "Architecture and app server tiers",
            "Web, app, and process scheduler",
            "Domain configuration",
            "Integration Broker basics",
            "Security roles and sign-on",
            "Batch jobs and process monitor",
            "Troubleshooting app server logs",
            "Performance and caching",
            "Migration and cloning",
            "Production operations runbook",
        ],
    },
    {
        "course_slug": "prompt-engineering-zero-hero",
        "course_title": "Prompt Engineering: Zero to Hero",
        "topic": "Prompt Engineering",
        "playground_slug": "python",
        "modules": [
            "LLM fundamentals and tokens",
            "Zero-shot and few-shot prompting",
            "Chain-of-thought and reasoning",
            "System prompts and guardrails",
            "Structured output and JSON mode",
            "RAG and context windows",
            "Tool use and function calling",
            "Evaluation and regression testing",
            "Cost, latency, and safety",
            "Production prompt operations",
        ],
    },
    {
        "course_slug": "rhel-linux-zero-hero",
        "course_title": "RHEL Linux: Zero to Hero",
        "topic": "RHEL Linux",
        "playground_slug": "linux",
        "modules": [
            "RHEL subscription and repositories",
            "Package management with dnf",
            "systemd targets and services",
            "firewalld and SELinux",
            "Storage and LVM on RHEL",
            "SSSD and identity integration",
            "Kernel tuning and kdump",
            "auditd and compliance",
            "Patching and lifecycle",
            "Enterprise RHEL operations",
        ],
    },
    {
        "course_slug": "nodejs-zero-hero",
        "course_title": "Node.js: Zero to Hero",
        "topic": "Node.js",
        "playground_slug": "nodejs",
        "modules": [
            "Node runtime and npm",
            "Modules, ESM, and package.json",
            "HTTP servers and Express",
            "Async patterns and error handling",
            "File I/O and streams",
            "Testing with Jest",
            "Environment and configuration",
            "Security middleware",
            "Performance and clustering",
            "Production deployment",
        ],
    },
    {
        "course_slug": "gpu-nvidia-zero-hero",
        "course_title": "GPU & NVIDIA: Zero to Hero",
        "topic": "GPU",
        "playground_slug": "gpu",
        "modules": [
            "GPU architecture overview",
            "NVIDIA drivers and CUDA toolkit",
            "nvidia-smi and monitoring",
            "Container GPU passthrough",
            "Kubernetes GPU scheduling",
            "MIG and multi-tenant GPUs",
            "AI training workload basics",
            "Inference optimization",
            "Troubleshooting GPU nodes",
            "Enterprise GPU operations",
        ],
    },
]
