# Generated by Django 5.2.12 on 2026-03-30 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name (lucide icon) or URL', max_length=255)),
                ('color', models.CharField(blank=True, default='cyan', help_text='Theme color key', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Short tagline like SadServers city names', max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('scenario_type', models.CharField(choices=[('fix', 'Fix'), ('do', 'Do'), ('hack', 'Hack')], default='fix', max_length=10)),
                ('description', models.TextField()),
                ('objectives', models.JSONField(blank=True, default=list, help_text='List of objectives')),
                ('initial_state', models.TextField(blank=True, help_text='Description of the broken state')),
                ('validation_script', models.TextField(blank=True, help_text='Bash script to validate the fix')),
                ('solution_explanation', models.TextField(blank=True, help_text='Explanation shown after solving')),
                ('docker_image', models.CharField(blank=True, help_text='Custom Docker image override', max_length=255)),
                ('time_limit', models.PositiveIntegerField(default=900, help_text='Time limit in seconds')),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('definition_path', models.CharField(blank=True, max_length=255)),
                ('is_free', models.BooleanField(default=False, help_text='Available without login')),
                ('is_active', models.BooleanField(default=True)),
                ('attempts_count', models.PositiveIntegerField(default=0, help_text='Cached total attempts')),
                ('completions_count', models.PositiveIntegerField(default=0, help_text='Cached total completions')),
                ('avg_completion_time', models.PositiveIntegerField(default=0, help_text='Average solve time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='scenarios', to='question_bank.tag')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='question_bank.technology')),
            ],
            options={
                'ordering': ['technology', 'difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='question_bank.scenario')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'scenario')},
            },
        ),
    ]
