# Generated by Django 5.2.12 on 2026-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='cloud_ami',
            field=models.CharField(blank=True, help_text='AWS AMI ID for EC2-based scenarios (default: Ubuntu 22.04)', max_length=100),
        ),
        migrations.AddField(
            model_name='scenario',
            name='cloud_image',
            field=models.CharField(blank=True, help_text='DigitalOcean image slug for droplet-based scenarios (default: ubuntu-22-04-x64)', max_length=100),
        ),
        migrations.AddField(
            model_name='scenario',
            name='cloud_setup_script',
            field=models.TextField(blank=True, help_text='Bash script to set up the broken state on a cloud instance (runs via cloud-init)'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='infrastructure_type',
            field=models.CharField(choices=[('docker', 'Docker Container'), ('aws_ec2', 'AWS EC2 Instance'), ('digitalocean', 'DigitalOcean Droplet')], default='docker', help_text='Where to run this scenario: docker, aws_ec2, or digitalocean', max_length=20),
        ),
    ]
