# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_scenario_cloud_ami_scenario_cloud_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='price',
            field=models.DecimalField(decimal_places=2, default=499, help_text='Price in INR for technology subscription', max_digits=8),
        ),
    ]
