# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0003_technology_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='blocked_commands',
            field=models.JSONField(blank=True, default=list, help_text='List of command patterns blocked in this scenario (e.g. reboot, shutdown, rm -rf /)'),
        ),
    ]
