# Generated by Django 5.2.15 on 2026-06-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0009_scenario_time_limit_default_600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='simulation_type',
            field=models.CharField(choices=[('generic', 'Normal Simulation (full RHEL)'), ('rhel', 'RHEL Linux Simulation'), ('kubernetes', 'Kubernetes Simulation'), ('gpu', 'GPU / NVIDIA Simulation'), ('baremetal', 'Bare Metal / IPMI / VMware'), ('database', 'Database Simulation'), ('ansible', 'Ansible Simulation'), ('python', 'Python Simulation')], default='generic', help_text='Technology persona when lab_mode=simulation (one unified engine)', max_length=20),
        ),
    ]
