# Generated by Django 5.2.15 on 2026-06-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0013_technology_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='coding_mode',
            field=models.BooleanField(default=False, help_text='Open a browser coding IDE (CodeMirror + sandboxed run) instead of a terminal'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='coding_spec',
            field=models.JSONField(blank=True, default=dict, help_text='Coding scenario definition: {language, files:[{path,content,readonly}], entrypoint, visible_tests:[...], hidden_tests:[...]}. hidden_tests are stripped from public API responses and only run on the backend.'),
        ),
    ]
