# Generated by Django 5.2.15 on 2026-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0014_scenario_coding_mode_scenario_coding_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='cross_technology',
            field=models.BooleanField(default=False, help_text='Server is shared across the VMware simulator and the Linux terminal in one session'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='vmware_link',
            field=models.BooleanField(default=False, help_text="Surface an 'Open VMware' link in the lab so the user can perform the hypervisor-side action"),
        ),
    ]
