# Generated by Django 5.2.15 on 2026-06-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0016_alter_project_slug_alter_scenario_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='itsm_config',
            field=models.JSONField(blank=True, default=dict, help_text='ITSM tuning: {ticket_type, short_description, description, priority, assignment_group, teams:[...], allowed_actions:[add_disk,add_nic,...]}. Drives the opened ticket and the sub-ticket actions surfaced in the panel.'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='itsm_enabled',
            field=models.BooleanField(default=False, help_text='Open a ServiceNow-style ITSM ticket for this scenario in the lab runner'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='itsm_ticket_type',
            field=models.CharField(blank=True, choices=[('incident', 'Incident'), ('request', 'Service Request'), ('change', 'Change'), ('problem', 'Problem')], default='incident', help_text='ServiceNow ticket type opened for this scenario', max_length=20),
        ),
    ]
