# Generated by Django 5.2.15 on 2026-06-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0017_scenario_itsm_config_scenario_itsm_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lab_scenario',
            field=models.ForeignKey(blank=True, help_text='Scenario whose lab environment this project launches on Start.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_using', to='question_bank.scenario'),
        ),
    ]
