# Generated by Django 6.0.6 on 2026-06-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0018_project_lab_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Make the whole technology (and all its labs) free — no subscription required. Forces price to 0.'),
        ),
    ]
