# Generated by Django 6.0.6 on 2026-06-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0020_scenario_certification_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='simulation_type',
            field=models.CharField(choices=[('generic', 'Normal Simulation (full RHEL)'), ('rhel', 'RHEL Linux Simulation'), ('kubernetes', 'Kubernetes Simulation'), ('gpu', 'GPU / NVIDIA Simulation'), ('baremetal', 'Bare Metal / IPMI / VMware'), ('database', 'Database Simulation'), ('ansible', 'Ansible Simulation'), ('ansible-awx', 'Ansible AWX / Tower Simulation'), ('terraform', 'Terraform / AWS CLI Simulation'), ('python', 'Python Simulation'), ('java', 'Java Development Simulation')], default='generic', help_text='Technology persona when lab_mode=simulation (one unified engine)', max_length=20),
        ),
    ]
