# Generated by Django 6.0.6 on 2026-07-14 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0021_alter_scenario_simulation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='validation_scenario',
            field=models.ForeignKey(blank=True, help_text='Scenario whose validator proves this task. When set, marking the task done requires a passed lab session for this scenario; when null, the task is self-attested (backward-compatible).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validating_project_tasks', to='question_bank.scenario'),
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Stage sequence within the project')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('handoff_artifact', models.JSONField(blank=True, default=dict, help_text="What this stage produces for the next one (e.g. {'name': 'SLO definition', 'description': 'p99<300ms yardstick'}). Free-form; empty dict = nothing handed off.")),
                ('breakpoint_note', models.TextField(blank=True, help_text="The 'where real pipelines break' lesson threaded through this stage.")),
                ('lab_scenario', models.ForeignKey(blank=True, help_text='Scenario whose lab environment this stage opens (null = no launchable lab for this stage yet).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stages_using', to='question_bank.scenario')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='question_bank.project')),
                ('stage_technology', models.ForeignKey(blank=True, help_text='The technology this stage exercises (nullable — a stage may be doc/postmortem-only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_stages', to='question_bank.technology')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project', 'order')},
            },
        ),
        migrations.AddField(
            model_name='projecttask',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='The stage this task belongs to (null on flat projects).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='question_bank.projectstage'),
        ),
    ]
