# Generated by Django 6.0.6 on 2026-07-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0023_scenario_fulltext_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('role_label', models.CharField(blank=True, default='', help_text="Target role, e.g. 'Junior Linux Admin', 'Cloud Engineer', 'Kubernetes SRE'", max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_technology', models.ForeignKey(blank=True, help_text='Primary technology for branding (membership is the steps, not this FK).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_journeys', to='question_bank.technology')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('tutorial_course', 'Tutorial Course'), ('scenarios', 'Scenarios'), ('project', 'Project / Capstone'), ('certification', 'Certification'), ('milestone', 'Milestone')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('ref_slug', models.CharField(blank=True, default='', help_text='Slug of the single referenced content (course/project/cert). Empty for milestones.', max_length=200)),
                ('ref_slugs', models.JSONField(blank=True, default=list, help_text="Ordered Scenario slugs for the 'scenarios' kind (difficulty-ramped).")),
                ('est_minutes', models.PositiveIntegerField(blank=True, help_text='Optional estimated time to complete this step, in minutes', null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='question_bank.learningjourney')),
            ],
            options={
                'ordering': ['journey', 'order'],
                'unique_together': {('journey', 'order')},
            },
        ),
    ]
