# Generated by Django 6.0.6 on 2026-07-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0025_alter_scenario_simulation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='datacenter_link',
            field=models.BooleanField(default=False, help_text="Surface an 'Open Datacenter' link for physical rack / BMC / PDU steps on the same server"),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='simulation_type',
            field=models.CharField(choices=[('generic', 'Normal Simulation (full RHEL)'), ('rhel', 'RHEL Linux Simulation'), ('kubernetes', 'Kubernetes Simulation'), ('gpu', 'GPU / NVIDIA Simulation'), ('baremetal', 'Bare Metal / IPMI / VMware'), ('database', 'Database Simulation'), ('ansible', 'Ansible Simulation'), ('ansible-awx', 'Ansible AWX / Tower Simulation'), ('terraform', 'Terraform / AWS CLI Simulation'), ('python', 'Python Simulation'), ('java', 'Java Development Simulation'), ('commvault', 'Commvault Backup Simulation'), ('netapp', 'NetApp ONTAP Storage Simulation'), ('dellemc', 'Dell EMC Unisphere / PowerMax Simulation'), ('datacenter', 'Physical Datacenter (DCIM) Simulation'), ('soc', 'SOC / SIEM Cybersecurity Simulation'), ('aws', 'AWS Console'), ('azure', 'Microsoft Azure Portal'), ('gcp', 'Google Cloud Console'), ('openstack', 'OpenStack Horizon'), ('vmware', 'VMware vSphere')], default='generic', help_text='Technology persona when lab_mode=simulation (one unified engine)', max_length=20),
        ),
    ]
