# Generated by Django 6.0.6 on 2026-08-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0027_scenario_consoles_lab_servers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='cross_technology',
            field=models.BooleanField(default=False, help_text='Curriculum stamp: shared guest story across technologies (does not unlock consoles)'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='datacenter_link',
            field=models.BooleanField(default=False, help_text='Opt-in: surface Open Datacenter for rack / BMC / PDU steps. Still requires an active Datacenter technology subscription.'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='simulation_type',
            field=models.CharField(choices=[('generic', 'Linux Lab Server (full RHEL)'), ('rhel', 'RHEL Linux Lab Server'), ('kubernetes', 'Kubernetes Cluster Lab'), ('gpu', 'GPU / NVIDIA Lab Server'), ('baremetal', 'Bare Metal / IPMI Lab'), ('vmware', 'VMware vCenter Lab'), ('database', 'Database Lab Server'), ('ansible', 'Ansible Control Lab'), ('ansible-awx', 'Ansible AWX / Tower Lab'), ('terraform', 'Terraform / AWS IaC Lab'), ('python', 'Python Development Lab'), ('java', 'Java Development Lab'), ('javascript', 'JavaScript Coding Lab'), ('react', 'React Coding Lab'), ('html', 'HTML / CSS Coding Lab'), ('shell_script', 'Shell Scripting Lab'), ('windows', 'Windows Server Lab'), ('windows-server', 'Windows Server Lab'), ('devops', 'DevOps / CI-CD Lab'), ('docker', 'Docker Host Lab'), ('networking', 'Networking / BGP Lab'), ('grafana', 'Grafana Observability Lab'), ('prometheus', 'Prometheus Monitoring Lab'), ('commvault', 'Commvault CommCell Lab'), ('netapp', 'NetApp ONTAP System Manager Lab'), ('dellemc', 'Dell EMC Unisphere / PowerMax Lab'), ('datacenter', 'Physical Data Center (DCIM) Lab'), ('soc', 'SOC / SIEM Analyst Lab'), ('aws', 'AWS Management Console Lab'), ('azure', 'Microsoft Azure Portal Lab'), ('gcp', 'Google Cloud Console Lab'), ('openstack', 'OpenStack Horizon Lab'), ('peoplesoft', 'PeopleSoft Application Server Lab'), ('nmap', 'Nmap Network Scan Lab'), ('wireshark', 'Wireshark Packet Analysis Lab'), ('data-dashboard', 'Data Dashboard / Chart Lab'), ('ai-agent', 'AI Agent Lab')], default='generic', help_text='Technology persona when lab_mode=simulation (one unified engine)', max_length=20),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='vmware_link',
            field=models.BooleanField(default=False, help_text='Opt-in: surface Open VMware for this session. Still requires an active VMware technology subscription (Linux-only subs cannot open vCenter).'),
        ),
    ]
