# Generated by Django 6.0.6 on 2026-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0028_alter_scenario_cross_technology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='linked_tutorial',
            field=models.SlugField(blank=True, default='', help_text='tutorials course_slug for the theory course backing this lab (blank = none)', max_length=255),
        ),
    ]
