# Generated by Django 6.0.6 on 2026-08-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0029_scenario_linked_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10),
        ),
    ]
