# Generated by Django 5.2.15 on 2026-06-19 22:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_support_bot_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('campaign', 'Campaign'), ('announcement', 'Announcement'), ('offer', 'Offer')], default='campaign', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='', help_text='Rich text / markdown body')),
                ('media_type', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video')], default='none', max_length=10)),
                ('media_url', models.URLField(blank=True, default='')),
                ('placement', models.CharField(choices=[('banner_top', 'Top banner'), ('modal', 'Modal'), ('dashboard', 'Dashboard card'), ('pricing', 'Pricing strip')], default='banner_top', max_length=20)),
                ('bg_color', models.CharField(blank=True, default='', help_text='CSS color or gradient', max_length=120)),
                ('text_color', models.CharField(blank=True, default='', max_length=40)),
                ('text_style', models.JSONField(blank=True, default=dict, help_text='Text style overrides: {"font_size": "15px", "font_weight": 600, "text_align": "left"}')),
                ('cta_label', models.CharField(blank=True, default='', max_length=80)),
                ('cta_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('enabled', 'Enabled'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('free', 'Free users'), ('paid', 'Paid users')], default='all', max_length=8)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('dismissible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'placement'], name='adminpanel__status_473090_idx')],
            },
        ),
    ]
