# Generated by Django 5.2.15 on 2026-06-22 19:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='business_gstin',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='business_legal_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='business_state',
            field=models.CharField(blank=True, default='', help_text='Place of supply (seller state) — decides CGST+SGST vs IGST.', max_length=64),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='gst_enabled',
            field=models.BooleanField(default=False, help_text="Levy GST on orders. Requires business_gstin to actually charge (you cannot levy GST without a registration). Off = 'skip GST', payments still work at the bare price."),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.18'), help_text='Combined GST fraction, e.g. 0.18 for 18%.', max_digits=4),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='payments_enabled',
            field=models.BooleanField(default=False, help_text="Master switch: when on AND a gateway is configured, paid checkout is live and the 'payment gateway not configured' warning clears."),
        ),
    ]
